### ISSUE TITLE
Modernize README

### ISSUE THREAD

**Issue by grant** [google/clasp#103]
- [x] Include centered title.
- [x] Update gif (gif for each method?)
  - Width: 890px
- [x] More badges (npm version, travis)
- [ ] Link TOC commands (update commands)
[ref](https://github.com/PetrochukM/PyTorch-NLP)

**Comment by campionfellin** [comment]
![clasp-create](https://user-images.githubusercontent.com/11984923/39343526-274651d0-4992-11e8-94c7-765b3ba0a438.gif)
![clasp-create-no-name](https://user-images.githubusercontent.com/11984923/39343529-2b655e64-4992-11e8-8c33-48294fbfdfa2.gif)

Uploading images here to get the link for them...

**Comment by grant** [comment]
I updated the header a bit.
Looking at other READMEs: https://github.com/matiassingers/awesome-readme

**Comment by grant** [comment]
With 0acd7bb035cb9c42b46733c21a86e0eb9356b53a (the updated GIF), I am going to close this issue.
I'm sure we could eventually design a logo, and improve the commands reference docs, but the README is a lot better than before.
