### ISSUE TITLE
Make clasp smaller

### ISSUE THREAD

**Issue by grant** [google/clasp#105]
## Expected Behavior

Clasp is <1000 lines of code.

## Actual Behavior

`index.ts` is ~1.1k SLOCs.

## Ways to shrink logic
- Inline `getFileType`, `getAPIFileType`, `manifestExists`
- Remove `commander` boilerplate.
- Make `getAPICredentials` async.
- Make online support required (unless specified).
- Make google API requests async
- Combine API call callback.
- Remove/shorten:
```ts
spinner.stop(true);
if (error) {
  logError(error);
}
```
- Extract dotfile logic in separate npm module.
- But keep to 1 file.

**Comment by sqrrrl** [comment]
Just curious -- why impose a 1000 loc limit on clasp?

**Comment by grant** [comment]
This issue is more of a suggestion. I think it would be good to extract some logic into npm modules.
I think ~1k is about the spot where a developer can fully understand what is happening within the code.
Also I've noticed `tsc` is getting slower the more lines we add.

**Comment by grant** [comment]
I think we'll break apart the single file with #134.
But there are some good ideas of keeping `clasp` small here.

**Comment by campionfellin** [comment]
This is being worked on in #133 and #134. Going to close this issue in favor of more specific issues like the others.
