### ISSUE TITLE
Feature Request: clasp diff

### ISSUE THREAD

**Issue by namelus** [google/clasp#109]
Great work. So very appreciative for this.
Wondering if you're entertaining a clasp diff functionality. I often wonder which code base is most current. And a clasp diff that brings the last updated at the header would help me know when i last pushed or pulled.

Thanks again!

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - Version (`npm list -g | grep clasp`):
  - OS (Mac/Linux/Windows)

**Comment by grant** [comment]
@namelus Good idea, I've wondered if this would be useful too.
However, I think once TypeScript development production-ready, I don't think there's a need to use the script editor.

It comes down to this: `git diff` will **always** be better than anything we can build.

We might want to add a section on working with `git` to the README. What do you think?

**Comment by grant** [comment]
As stated above, `git diff` will always be better anything in `clasp`. Closing, but feel free to add to the discussion here though.

**Comment by vladimir-virlan** [comment]
Moving to typescript doesn't stop you from using the online script editor and messing up the whole thing unless you have a `clasp diff`.
