### ISSUE TITLE
Move commands to src/commands.ts

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#134]
This will improve the readability and maintainability of `clasp`

* [ ] Move commands one at a time to `src/commands.ts`
* [ ] `clasp login`
* [ ] `clasp logout`
* [ ] `clasp create`
* [ ] `clasp clone`
* [ ] `clasp pull`
* [ ] `clasp push`
* [ ] `clasp open`
* [ ] `clasp deployments`
* [ ] `clasp deploy`
* [ ] `clasp redeploy`
* [ ] `clasp version`
* [ ] `clasp versions`
* [ ] `clasp list`
* [ ] `clasp logs`
* [ ] Integrate changes into `index.ts`
* [ ] Run all the tests (all are relevant)

**Comment by grant** [comment]
It would be cool if we reorganized the commands in a way where we could:
- Easily test commands
- Generate the command documentation
  - Since it's easy to miss optional args and new features

**Comment by campionfellin** [comment]
I agree... I think that an even better organization would be something like:

`src/commands/login.ts`
`src/commands/logout.ts`
`src/commands/list.ts`

etc...

Thus each command could be easily isolated and tested.

**Comment by campionfellin** [comment]
Yeah I like this idea, though a couple questions/comments:

1. Why would we be duplicating `LOG` and `ERROR`? Couldn't we just import them wherever we need?
2. I really like the idea of separating the command logic from the actual CLI library that we use, it'll be much easier to maintain and if we decide to switch to something like Vorpal that will make things easier.
3. This seems like quite a bit of work, should this be put into a major version? It might be more important to finish clasp 2.0 first, especially commands like `clasp run` before we work on this.

**Comment by grant** [comment]
1. Assuming `commands.ts` uses all ~50 `LOG`/`ERROR`s, if we moved them to a separate file outside `commands`, we'd have to import/export them.
1. Separating SGTM. Maybe we can even `module.export` them sometime.
1. I think the next public version of clasp will be 2.0. I think the last main thing for the `2.0` list is `--watch`.

**Comment by campionfellin** [comment]
1. Gotcha. I think it's also worth taking a look at reducing how many different `LOG`/`ERROR`s we have.
3. I think that much of this re-factoring should be pushed off to clasp 3.0 then (or maybe 2.1/2.2). In addition to `--watch`, we need to fix `clasp run`, as it doesn't seem to work at the moment. Probably related to finding a general solution to https://github.com/google/clasp/issues/131 / `getAPICredentials()`

**Comment by grant** [comment]
All commands have been moved to `commands.ts`.
