### ISSUE TITLE
Reduce 3rd party dependencies

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#137]
There's a lot of third party dependencies, like:

`find-parent-dir`
`split-lines`
`read-file`
`dotf` (sorry @grant )
`read-multiple-files`
`readline`

We should take a look at at least some of them and see what is actually needed and what we can roll on our own.

**Comment by grant** [comment]
If we can reduce them, sure.
I wrote `dotf` because I didn't find a good dotfile manager.

For Node, 3P dependencies are usually better than rolling-your-own.

**Comment by campionfellin** [comment]
Just might be worth looking at them

**Comment by grant** [comment]
Going to close this issue as we can't simply remove these dependencies easily.
- not specific (reducing dependencies)
- not actionable (we can't delete any of these afaik)

The filesystem modules are useful an probably necessary for a package that uses the filesystem heavily.

We can create a new issue if we find a specific module that can be removed.
