### ISSUE TITLE
Recursively ignore dotfiles

### ISSUE THREAD

**Issue by grant** [google/clasp#14]
Currently, only top-level dotfiles are ignored. Ignore dotfiles recursively.

**Comment by grant** [comment]
Something like: 
```js
if (getAPIFileType(name) && !anymatch(ignorePatterns, name) && nameWithoutExt.indexOf('.') === -1) {
```

**Comment by grant** [comment]
This bug should be made clearer when #73 (`clasp status`) is implemented.

**Comment by takanakahiko** [comment]
Is this issue still unresolved?
I feel like I'm solving it.

![image](https://user-images.githubusercontent.com/10114717/47607663-c2cf9d80-da5d-11e8-9d41-8f1d56cdc9cb.png)

**Comment by grant** [comment]
I think it's resolved. Thanks @takanakahiko.
