### ISSUE TITLE
All external libraries are removed when there is a new push

### ISSUE THREAD

**Issue by guelster** [google/clasp#157]
## Expected Behavior
All external libraries remain in the script after a code push

## Actual Behavior
All external libraries were removed from the script after a code push and had to manually add the libraries back to the script using respective library keys

## Steps to Reproduce the Problem

  1. run 'clasp push'
  2. code is pushed but all libraries are gone

## Specifications

  - Node version v6.3.0
  - Version: 1.1.5
  - OS: Mac

**Comment by grant** [comment]
Can you give me a small test case? `node_modules` are removed after `clasp push`?

**Comment by guelster** [comment]
@grant Thanks for the reply. the library I am referring to is the google app script library, not node libraries (i.e. if you go into Resources> Libraries in the script editor in google script).

The library I was trying to use was [LodashGS](https://github.com/oshliaer/lodashgs). It seems that after everytime I push, I have to manually go into app script editor and add this library back to the script.

**Comment by grant** [comment]
Can you copy your manifest file here?
With script.google.com: `View > Show manifest file`
With clasp: `appsscript.json`

Are they the same? Does updating the clasp version, then `clasp push` fix this?

**Comment by guelster** [comment]
ahh, I see the issue now. I am supposed to add the library into my appscript.json. Thanks @grant
