### ISSUE TITLE
Exit with an error on non-existing commands

### ISSUE THREAD

**Issue by FiloSottile** [google/clasp#159]
## Expected Behavior

On running a mispelled command, or `help` (instead of the flag) or `list` (unimplemented), the program should print a message and exit with code > 0.

## Actual Behavior

Nothing is printed and the exit code is 0.

This is particularly confusing for `list`, as that was the first command I tried and empty output suggests it can't find any projects.

## Specifications

  - Node version (`node -v`): v10.0.0
  - Version (`npm list -g | grep clasp`): @google/clasp@1.1.5
  - OS (Mac/Linux/Windows): Mac

**Comment by campionfellin** [comment]
@grant Does npm need to be updated? I was able to reproduce this if installing using `npm install @google/clasp -g`

**Comment by grant** [comment]
npm needs to be updated. I'm a bit busy preparing for I/O next week.
@campionfellin Is the build stable? I can publish but I won't be able to debug any build errors.

**Comment by campionfellin** [comment]
@grant please look at https://github.com/google/clasp/pull/160 which should make it stable, but also try to run all tests locally to make sure (make sure to `clasp login` before running tests). Also run the `clasp deployments`, `clasp deploy`, and `clasp versions` tests separately.

**Comment by campionfellin** [comment]
@grant time to update npm?

**Comment by grant** [comment]
I've successfully tested all clasp commands and published the latest release. I don't think errors exit the CLI with non-zero values though.

**Comment by grant** [comment]
Repro:
```
$ clasp aweg
🤔  Unknown command "aweg"

Forgot clasp commands? Get help:
  clasp --help

$ echo $?
0
```

**Comment by campionfellin** [comment]
Changing this https://github.com/google/clasp/blob/2d8ba8ee71edb2e84bfbfa10c601844d09d7212b/src/commands.ts#L92

to `logError(...)` should fix it.

**Comment by grant** [comment]
Ah, true.
