### ISSUE TITLE
Code Lab Typo

### ISSUE THREAD

**Issue by jvasallo** [google/clasp#161]
In the code lab on step 5, there is step to update the variable name in strings.gs but not the variable name in Code.gs.

```In your favorite text editor, navigate to util/strings.gs and replace the variable name world to mondo. To update the updated code on script.google.com, push your edited code.```

may need to become:
```In your favorite text editor, navigate to util/strings.gs and replace the variable name world to mondo. Also, update the Code.gs by replacing world to mondo. To update the updated code on script.google.com, push your edited code.```

**Comment by grant** [comment]
Thank you @jvasallo!
Updated https://codelabs.developers.google.com/codelabs/clasp/#4
