### ISSUE TITLE
clasp clone should show script name as well as ID

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#162]
## Expected Behavior
When running `clasp clone` without an argument, it lets you choose by scriptId. We should add something like `- myScript` to the right to make it easier to find your script.

## Actual Behavior
<img width="431" alt="screen shot 2018-05-10 at 6 31 07 pm" src="https://user-images.githubusercontent.com/11984923/39901994-6bb931d6-5480-11e8-86e2-8dff8f20f998.png">

## Steps to Reproduce the Problem

  1. `clasp clone`

**Comment by grant** [comment]
The chooser should probably allow you to fuzzy match your input on the id/script title.

**Comment by campionfellin** [comment]
Closing as per https://github.com/google/clasp/pull/170
