### ISSUE TITLE
Request: clasp status --json

### ISSUE THREAD

**Issue by ajlai** [google/clasp#163]
## Expected Behavior
clasp status has a `--json` switch to output status in a more parseable format (Currently would help with building out clasp status test cases).
```bash
> clasp status --json
{"filesToPush": ["Code.js", "appscript.json"], "untrackedFiles": ["ignored.txt"]}
```

## Actual Behavior
```bash
> clasp status
The following files will be pushed by clasp push:
└─ Code.js
└─ appsscript.json
Untracked files:
└─ ignored.txt
```

## Specifications

  - Node version (`node -v`)
  - Version (`npm list -g | grep clasp`):
  - OS (Mac/Linux/Windows)

**Comment by grant** [comment]
Seems like a fine FR but I don't see the value in it. What' the use case?
For example, `git status` doesn't have a json option, but I'm sure it's been requested.
What about a `deployments` or `versions` `--json` option?

I'd not want to build this feature just yet as we could expand to have all methods have a `json` option or export our results in an API as suggested before.

**Comment by ajlai** [comment]
While I'm building the clasp status tests, it'd be nice to not have to build additional (brittle) parsing just to deconstruct the status output to feed back into the tests.

**Comment by ajlai** [comment]
FWIW git status has a `--short` option that does make it easier to parse. https://git-scm.com/docs/git-status#_short_format
I considered that, but thought `--json` would be a much simpler approach for the same outcome.

**Comment by grant** [comment]
Above PR was merged. Closing.
