### ISSUE TITLE
node.js - DeprecationWarning [DEP0013]

### ISSUE THREAD

**Issue by Nirazul** [google/clasp#17]
First of all: Thank you for this project, this is a godsend! I really like the idea of google AppScript but it's just a pain to develop without a proper IDE.

Upon trying it out, I've come upon a deprecation warning when cloning a project with node `8.9.3`:

```
Cloned 4 files.
└─ Main.gs
(node:4835) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
└─ Api.gs
(node:4835) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
└─ Format.gs
(node:4835) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
└─ appsscript.json
(node:4835) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

The warning relates to this [Deprecation](https://nodejs.org/api/deprecations.html#deprecations_dep0013_fs_asynchronous_function_without_callback).

I've looked at the code but it seems that I'd have to dig into one of the dependencies. So for the time being, I'm just placing it here if anyone else stumbles upon it.

**Comment by Nirazul** [comment]
Ah, there's already an issue. Closing here.

**Comment by grant** [comment]
(#13) Good first issue if you want to contribute!
