### ISSUE TITLE
clasp push disables all 'Advanced Google Services'

### ISSUE THREAD

**Issue by msmialow** [google/clasp#171]
## Expected Behavior
clasp push has no effect of the on/off state of Advanced Google Services.

## Actual Behavior
clasp push turns all enabled advanced services to 'off'.

## Steps to Reproduce the Problem

  1.Enable any Advanced Google Service in script
  2.clasp push changes to script
  3.Advanced Services are all turned off

## Specifications

  - Node version (`node -v`) - **9.9.0**
  - Version (`npm list -g | grep clasp`) - **1.1.5**
  - OS (Mac/Linux/Windows) - **Linux Mint 18.3 - 4.15.0-20-generic**

## Notes

This is a super annoying bug as every single change pushed to the script using clasp requires you to go into the Advanced Google Services and re-enable the one(s) that you are using before you can run related code.  Not sure if this is something related to my specific environment or if it impacts others.  I originally noticed this using the Admin Directory API, but further testing shows that it disables anything that is turned on, so I doubt it is a factor.

![clasp-push-bug](https://user-images.githubusercontent.com/8192772/40089626-aba3b4e4-587a-11e8-8b58-d185c33b0c4f.gif)

**Comment by grant** [comment]
Thanks for the gif.
If you modify the project in the online editor, you must `clasp pull` to update your local environment.
`clasp push` overrides the content in the online editor.

`View > Show manifest file` to see your Advanced Services like this:

```js
{
  "timeZone": "America/Los_Angeles",
  "dependencies": {
    "enabledAdvancedServices": [{
      "userSymbol": "AdminDirectory",
      "serviceId": "admin",
      "version": "directory_v1"
    }, {
      "userSymbol": "AdminReports",
      "serviceId": "admin",
      "version": "reports_v1"
    }, {
      "userSymbol": "AndroidBuildInternal",
      "serviceId": "androidbuildinternal",
      "version": "v2beta1"
    }, {
      "userSymbol": "AdSense",
      "serviceId": "adsense",
      "version": "v1.4"
    }, {
      "userSymbol": "AppsAssistant",
      "serviceId": "appsassistant-pa",
      "version": "v1"
    }]
  },
  "exceptionLogging": "STACKDRIVER"
}
```

Are things still broken if you `clasp pull` first?

**Comment by grant** [comment]
Yeah, it's not at all intuitive. I think the manifest file should not be hidden from the script.google.com UI.

Pulling before pushing is usually a good habit like with git. Maybe we can add a note somewhere about manifests. PRs/issues welcome!
