### ISSUE TITLE
Versions command only lists first 50 versions

### ISSUE THREAD

**Issue by tombell** [google/clasp#173]
## Expected Behavior

Should be able to view all versions

## Actual Behavior

Only see versions 1 to 50

## Steps to Reproduce the Problem

  1. Have over 50 versions of a project
  1. `clasp versions`

## Specifications

  - Node version (`node -v`): 8.11.1
  - Version (`npm list -g | grep clasp`): 1.3.0
  - OS (Mac/Linux/Windows): macOS 10.13.4

Would be nice to see latest 50 versions, or all of them.

**Comment by grant** [comment]
PRs welcome!
`pageSize` here: https://github.com/google/clasp/blob/master/index.ts#L652
