### ISSUE TITLE
Simplify auth module usage

### ISSUE THREAD

**Issue by ajlai** [google/clasp#180]
Based on https://github.com/google/clasp/pull/177#issuecomment-390697852

## Expected Behavior
auth module exports authenticated `getScript() : Promise<Script>` and `getDrive() : Promise<Drive>` methods as ways to access script/drive resources.

## Actual Behavior
auth module exports `oauth2Client` and `getAPICredentials()` which needs to be called before anything which uses the `oauth2Client` (could be clearer)

## Specifications

  - Node version (`node -v`)
  - Version (`npm list -g | grep clasp`):
  - OS (Mac/Linux/Windows)

**Comment by grant** [comment]
At some point, #201 was implemented and now you just need to run 1 line, `await loadAPICredentials();` before any Google API method.

Thanks for the issue! I think this is as simple as we can get.
