### ISSUE TITLE
Limit to how many apps scripts you can create?

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#196]
While doing some testing, I ran into this error, specifically on any `clasp create` commands:

```
  errors:
   [ { message: 'Resource has been exhausted (e.g. check quota).',
       domain: 'global',
       reason: 'rateLimitExceeded' } ] }
```

Looks like I was rate limited on something. I can't find any rate limits anywhere that would suggest I should be though..

**Comment by grant** [comment]
For every Google API method (in these APIs at least), there is a rate limit/**user**/hour (per user per hour).

`create` looks fine to me so it looks like you've been creating many scripts in succession on the user's account. The limit is already increased for `clasp`, so I don't think any user will face the limit unless they're developing `clasp` or abusing the system.

Creating whole new Apps Script projects is rated heavily so I'm not surprised to see the error there.

Try logging in with different users.

See error 429: https://cloud.google.com/appengine/docs/admin-api/reference/rest/Shared.Types/Code

We could probably give a better error using the `statusCode` in `logError`.

We can reopen this issue if the above doesn't solve the issue.

**Comment by campionfellin** [comment]
Yeah I saw that and also some other documentation, but I couldn't find a solid number on it. I don't think there is anything wrong with `clasp create`, it'd just be nice to know what that limit is and where is it enforced. (Is it a Drive API limit, an Apps Script Limit, etc?)

**Comment by grant** [comment]
Just search quotas on console.google.com and you'll find something like this:

<img width="988" alt="screen shot 2018-05-29 at 21 54 41" src="https://user-images.githubusercontent.com/744973/40699743-fd03c50c-638a-11e8-8679-1d06ddd6003f.png">

It's probably not a detail I'd put in the repo, but happy to answer it here or on Slack.
