### ISSUE TITLE
Add an option for login --no-localhost

### ISSUE THREAD

**Issue by mhawksey** [google/clasp#2]
Interested in running this in Google Cloud Shell but currently `login` redirects to localhost. A `--no-localhost` option would be useful.

**Comment by rielzzapps** [comment]
If you receive the URL, copy it.

In cloud shell just paste:

wget [url] to call the service and authenticate.

I agree, a --no-localhost would be nice.

Riël Notermans
Dinsdags vrij • Zzapps B.V. • High Tech Campus 9, 5656 AE Eindhoven
<https://www.google.nl/maps/place/Zzapps/@51.4099441,5.4510368,16z/data=!4m5!1m2!3m1!2sZzapps!3m1!1s0x0000000000000000:0x3ad8d7839ef5a5dd>
•
T 040 711 41 94 <+31407114194> • E riel@zzapps.nl • www.zzapps.nl
WIJ MAKEN HET ONDENKBARE MOGELIJK

2018-01-12 15:22 GMT+01:00 mhawksey <notifications@github.com>:

**Comment by grant** [comment]
This is a good idea. Let's think about what the design should be:

```
$ clasp login --no-localhost
> Open: http://console.google.com/...
> Paste the token: ...
> Saved the credentials to ~/.clasp.rc.json.
```

[gcloud's browserless solution: `gcloud auth login --no-launch-browser`](https://cloud.google.com/sdk/gcloud/reference/auth/login)

Is there a common name for browserless login flag (`-f` and/or `--flag`) we should use?

## Temporary workaround:
Copy `~/.clasprc.json` to your machine.

**Comment by mhawksey** [comment]
The command/flag for the Firebase CLI is `login --no-localhost` As this is also Google Auth flow you might be able to reuse some of the code from their implementation https://github.com/firebase/firebase-tools

**Comment by grant** [comment]
The initial `login` command didn't use localhost. When we tackle this feature, we can just use the previous `login` via command line with the code here:

https://github.com/google/clasp/blob/75882839f152a6183c7c92a525069ea6bccecaa8/index.js#L336-L355

**Comment by grant** [comment]
Will close this issue in the next release.
