### ISSUE TITLE
TypeError: console.err is not a function

### ISSUE THREAD

**Issue by cwatson88** [google/clasp#20]
https://github.com/google/clasp/blob/4cf4cc95a83acdb9faf78d1b46a34f96ff309658/index.js#L417

This has logged an error in terminal(see below). Should be **console.error()** instead?

TypeError: console.err is not a function
    at fs.writeFile (/usr/local/lib/node_modules/@google/clasp/index.js:417:23)
    at /usr/local/lib/node_modules/@google/clasp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by grant** [comment]
Look like https://github.com/google/clasp/pull/19 fixed this though. Will close this issue and update the module soon.
