### ISSUE TITLE
Generate README Doc

### ISSUE THREAD

**Issue by grant** [google/clasp#200]
## Expected Behavior

The README methods should be generated from the TypeScript file.

## Actual Behavior

The README is slightly out of date, duplicates jsdoc comments, and must be hand edited.

## Solution

- Create a file called `generateDocs.ts`.
- Running `tsc generateDocs.ts && node generateDocs.js` should build the README without modifications needed.
  - This script should use the [TS Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) over index.ts. A header and footer would be added to the README.
- A test should check that the current README file matches the latest generated README file.

**Comment by grant** [comment]
This npm module (`esprima`) looks promising.

Example:
```ts
var esprima = require('esprima');
var program = `
const answer = 42
console.log('hi');

commander
  .command('create [scriptTitle] [scriptParentId]')
  .description('Create a script')
  .action(create);

/**
 * Fetches a project and saves the script id locally.
 */
commander
  .command('clone [scriptId] [versionNumber]')
  .description('Clone a project')
  .action(clone);
`;

var p = esprima.parse(program);
console.log(JSON.stringify(p, null, 2));
```

**Comment by campionfellin** [comment]
[jsdoc](https://github.com/jsdoc3/jsdoc) might be nice, since we write our comments using their format already. Looks like there is [jsdoc2md](https://github.com/jsdoc2md/jsdoc-to-markdown) to generate the ReadMe.

**Comment by grant** [comment]
The problem is most tools assume `js`, not `ts`.
For `jsdoc2md`, the parser only detects `function`s and not the `commander.command` syntax (it is blank).

**Comment by grant** [comment]
OK, so I think we can generate a README if we just parse the ts comments in one file.
We can use this library that doesn't care about the actual filetype or syntax, it just looks at the comments and provides a nice AST:

https://github.com/jonschlinkert/parse-comments
