### ISSUE TITLE
Clasp is not ignoring folder as well as specific files with extension like *.abc

### ISSUE THREAD

**Issue by last-stand** [google/clasp#207]
(Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.)

## Expected Behavior
I added **node_modules** folder in _.claspignore_ file and tried to run `clasp push` but its not working properly and showing error 
``` Push failed. Errors:
Invalid value at 'files[1].type' (TYPE_ENUM), "MD"
Invalid value at 'files[2].type' (TYPE_ENUM), "MD"  
```

I even tried  `node_modules/**/*.*` and `node_modules/**/*.MD` but no luck.

## Actual Behavior
If I add a folder to _.claspignore_ file it should ignore all folders and files in that parent folder here in this case **node_modules**. Or at least, it should follow `node_modules/**/*.*`  and `node_modules/**/*.MD` conventions to ignore specific files.

## Steps to Reproduce the Problem

  1. Setup a basic project using clasp which is using some npm packages like _jasmine js_.
  2. Now put node_modules in _.claspignore_ file.
  3. Try to push the code to script.google.com using `clasp push`
  4. You will get errors as mentioned above.

## Specifications

  - Node version (`v9.10.1`)
  - Version (`@google/clasp@1.1.5`):
  - OS (MacOS High Sierra v10.13.4)

**Comment by campionfellin** [comment]
Hey @last-stand , thanks for filing an issue! Can we see your `.claspignore` file?

My `.claspignore` starts with `node_modules/**` and that seems to work. Do you have any markdown files in your current directory that you are forgetting to ignore?

**Comment by grant** [comment]
Closing in favor of #58.
