### ISSUE TITLE
Enable Advanced Services for Apps Script projects via CLI

### ISSUE THREAD

**Issue by grant** [google/clasp#217]
## Expected Behavior

To use Google APIs (Advanced Services) in Apps Script, you must enable APIs in the online editor at `script.google.com > Resources > Advanced Google Services...`

You should be able to setup a project without having to go to the editor. I propose a function to enable APIs in `clasp` like the UI.

### Commands

```sh
clasp apis list
clasp apis enable "drive.googleapis.com"
clasp apis disable "drive.googleapis.com"
```

- `list` would list all Google API `serviceId`s
- `enable`/`disable` a API for the Cloud project

Eventually autocomplete:

```sh
clasp apis enable # select from list of all Google APIs that aren't enabled
clasp apis disable # select from list of enabled APIs in the manifest
```

### API

These commands would use the `serviceuser.projects.services` API. It would require a personal Cloud project.
`projects/project-id-0486239153690933627/services/drive.googleapis.com`

**EDIT:** User [serviceusage](https://developers.google.com/apis-explorer/#p/serviceusage/v1/) not serviceuser since that's the newer API.

- List Services API: https://developers.google.com/apis-explorer/#p/discovery/v1/discovery.apis.list
- Enable Service API: https://developers.google.com/apis-explorer/#p/serviceuser/v1/serviceuser.projects.services.enable
- Disable Service API: https://developers.google.com/apis-explorer/#p/serviceuser/v1/serviceuser.projects.services.disable

### Result

The result of enabling an advanced service via the UI is:

1. Enabling the API for your Cloud Console project
1. Adding some data to your `appsscript.json`.

```js
  "dependencies": {
    "enabledAdvancedServices": [{
      "userSymbol": "AdSenseOrWhatever",
      "serviceId": "adsense",
      "version": "v1.4"
    }]
  }
```

## Actual Behavior

Users have to go to script.google.com to enable advanced services.

**Comment by rdoursenaud** [comment]
The actual behavior is even more annoying since it disables the advanced services on `clasp push`!

**Comment by grant** [comment]
@rdoursenaud Advanced service aren't disabled on `push`. You need to `pull` after you enable an advanced service, because it changes the `appsscript.json` file. LMK if you're still seeing an error.

I should document this more.

**Comment by grant** [comment]
No worries, it's not intuitive (see #171).
I probably should add a warning if you try to `push` before `pull`ing like git.

**Comment by rdoursenaud** [comment]
@grant I don't think you meant to close this issue. Exposing the advanced services feature in CLASP is still a good idea!

**Comment by grant** [comment]
Right!

**Comment by grant** [comment]
I've authored most of this feature here: https://github.com/google/clasp/commit/faa4337752fee7484160f3fb8b6930c87dce1caf

I need to update the manifest file still.

**Comment by grant** [comment]
This feature has been added into `master`.
It'll appear in `clasp@2` in December.
Marking as fixed.
