### ISSUE TITLE
How to get logs when the script is a standalone library executed from a spreadsheet?

### ISSUE THREAD

**Issue by maximelebreton** [google/clasp#219]
Here is my case.

I have a standalone script (the library).
Who process data from spreadsheets (where i've installed the library).

So when I want to Logger.log() something, I need to execute the function from a Spreadsheet, and go to the **Spreadsheet Editor Script Journal** (and not the Standalone Journal or Stack Driver), to see it. 

So how can I get my standalone logs, but executed from a spreadsheet?

Or have you a better workflow for debugging in this kind of situation?

Thanks!

**Comment by grant** [comment]
Executed from a spreadsheet is technically a Spreadsheet Add-on.

Use StackDriver logging for persistent logs. Read up on this:
https://developers.google.com/apps-script/guides/logging

Use `console.log` and View > StackDriver Logs

**Comment by grant** [comment]
@maximelebreton Did you try that out?
I'm going to close this issue soon as it is related to Apps Script in general and not `clasp`.

**Comment by carlosonunez** [comment]
Can confirm that this worked for me!
