### ISSUE TITLE
A new tab is opened when `clasp open` is executed

### ISSUE THREAD

**Issue by NakajimaTakuya** [google/clasp#23]
## Expected Behavior

When I run `clasp open`, I want you to refresh the tab if there is a previously opened tab.

## Actual Behavior

Another tab opens.
That behavior makes it hard to tell which is the latest code.

## Steps to Reproduce the Problem

  1. invoke: `clasp open`
  1. invoke: `clasp open`

## Specifications

  - Node version (`node -v`): v8.9.3
  - Version (`npm list | grep clasp`): 1.0.7
  - OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
You can't really detect which internet browser tabs are open on your operating system due to security.

Also, this feature would be confusing if `clasp open` fails if you try to open the same script but a day apart.

**Comment by NakajimaTakuya** [comment]
I understand.
I will consider using `live-reload` like tools.
