### ISSUE TITLE
Display error message when Apps Script API usersettings are disabled

### ISSUE THREAD

**Issue by vavrecka** [google/clasp#244]
(Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.)

## Expected Behavior
"clasp push" should push all files.

## Actual Behavior
When I have a project with "README.md" file and it's not excluded in ".claspignore" it throws an error:
<img width="282" alt="screen shot 2018-06-28 at 15 26 36" src="https://user-images.githubusercontent.com/6089093/42037153-fa28e0e6-7ae7-11e8-901e-c5141672c1eb.png">

## Steps to Reproduce the Problem
Any project with README.md file does it. New OR cloned.

## Specifications

  - Node version (`node -v`): v8.11.3
  - Version (`clasp -v`): 1.4.0
  - OS (Mac/Linux/Windows): Mac OS High Sierra - 10.13.4 (17E199)

**Comment by campionfellin** [comment]
I don't think that Apps Scripts projects can have `.md` files. (https://developers.google.com/apps-script/guides/projects). Are you able to make one through the UI?

**Comment by campionfellin** [comment]
Hey, sorry about that! That issue where it didn't give an error message has been fixed (see https://github.com/google/clasp/pull/239/files). Essentially this is what was happening:

```
          // In the following code, we favor console.error()
          // over logError() because logError() exits, whereas
          // we want to log multiple lines of messages, and
          // eventually exit after logging everything.
```

I don't think it's been pushed out to `npm` yet, but should be coming soon!

**Comment by vavrecka** [comment]
Perfect! Glad to hear that. We can close this one then, thanks!

**Comment by campionfellin** [comment]
Thanks!

**Comment by IanWhalen** [comment]
Just a note that I think I'm running into the 'blank error message' issue as well on `clasp push`, so publishing a new version with the above fix or giving any kind of workaround here would be awesome.  Otherwise I'm just kind of drawing a blank on what's wrong.

**Comment by ryan-codingintrigue** [comment]
@IanWhalen Same here. The project is relatively easy to build from source:

```cmd
git clone https://github.com/google/clasp.git
cd clasp
npm install
npm run build
npm pack # google-clasp-1.4.1.tgz
cd ~/your-project/
npm install ~/clasp/google-clasp-1.4.1.tgz
```

Turns out I forgot to enable the Apps Script API !
https://script.google.com/home/usersettings

**Comment by grant** [comment]
I'll look into preventing these errors next week.

**Comment by IanWhalen** [comment]
Doh, usersettings was totally it.  I just skipped over that line in the readme.  Sorry!  But yes, an error message indicating that's the problem would certainly be helpful if possible.

**Comment by campionfellin** [comment]
Hey all, have you tried with version `1.4.1`? It seems to be working now giving this error if the API hasn't been enabled:

```
Push failed. Errors:
User has not enabled the Apps Script API. Enable it by visiting https://script.google.com/home/usersettings then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

This was fixed in this commit: https://github.com/google/clasp/commit/272c1df69dfdddc037dba5826524327370c949fa

See similar issue here: https://github.com/google/clasp/issues/256

**Comment by grant** [comment]
I think I'm going to close this issue in favor of #256 since the problem was usersettings.

**Comment by DamirMakhmudov** [comment]
Sorry, guys! I use 2.2.1 version but  I have the same problem on push: 

> Error: User has not enabled the Apps Script API. Enable it by visiting

node version is v10.16.0
vscode  as editor
