### ISSUE TITLE
Add doc for typescript modules

### ISSUE THREAD

**Issue by edwardfung123** [google/clasp#262]
Is it actually possible? if so, could you update the doc? Currently I am building an add-on and I would modularize the code. Or should I simply concat the files before `clasp push`?

After reading the doc about using typescript in clasp [here](https://github.com/google/clasp/tree/master/docs) and experiment with different code, I still cannot figure out a way to export and import functions in different files and works in the Apps Script environment. The major issues are:

1. undefined `exports` caused by the line `exports.__esModule = true;` after transpiling.
2. undefined `require()` method. 

My workaround for issue 1 is to add `var exports = exports || {};`. But issue #72 makes it a bit tedious...

**Comment by grant** [comment]
Currently node-like modules aren't supported in clasp. An idea would be to rollup the clasp code as one giant src file, but that isn't very ideal and isn't in alignment with the current developer model for clasp (ideally keeping separate files).

You can create separate classes, but they have to have a unique name. The file order issue is tricky, but should help this. Ideally most programs run scripts within functions making the file order not matter.

**Comment by edwardfung123** [comment]
OK. Since I am new to apps script and typescript. I am not sure whether I am not doing something right. 

> You can create separate classes, but they have to have a unique name. The file order issue is tricky, but should help this. Ideally most programs run scripts within functions making the file order not matter.

Yes my code is converging to this approach and it works so far. Thank you very much. `claps` really makes the development a lot easier.

**Comment by grant** [comment]
I've updated [the doc](https://github.com/google/clasp/blob/master/docs/typescript.md) to describe how you cannot use terms like `require` or `exports`.

The best way to modularize code is via functions (they are global).

Does that answer the question, or should there be any other warning in the TypeScript doc?

**Comment by edwardfung123** [comment]
It is OK.

**Comment by grant** [comment]
Please try `clasp@1.5.1` and see if the update works for your environment. `exports` shouldn't fail now. If it doesn't work to your liking, please state the expected and actual results in the comment.

Node-like modules aren't supported, although you may be able to use scripts that are also Node modules.

I'm going to close this issue since Node modules aren't supported (I've updated the doc), but feel free to continue to discuss in this thread.
