### ISSUE TITLE
Push failed. Errors:

### ISSUE THREAD

**Issue by techjeffharris** [google/clasp#264]
## Expected Behavior
Upload my changes, or provide useful error.

## Actual Behavior
Fails to upload providing "empty" error. 

```
Jeffs-MacBook-700:temp jeffharris$ clasp push
Push failed. Errors:
Jeffs-MacBook-700:temp jeffharris$ clasp status
The following files will be pushed by clasp push:
└─ Constants.js
└─ Utils.js
└─ appsscript.json
└─ new-bogus-file.js
Untracked files:
```

## Steps to Reproduce the Problem

  1. `mkdir test && cd test`
  1. `clasp clone <scriptId>`
  1. `touch new-bogus-file.js`
  1. `echo $(date) > new-bogus-file.js`
  1. `clasp push`

## Specifications

  - Node version (`node -v`): v8.9.0
  - Version (`clasp -v`): 1.4.0
  - OS (Mac/Linux/Windows): Darwin Jeffs-MacBook-700.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by techjeffharris** [comment]
I thought I had the latest version installed, but I found 1.5 in the releases section.  

Updated and now I can push just fine, so I'll just close this.... after 5 minutes. 👍

**Comment by grant** [comment]
Glad updating worked!
