### ISSUE TITLE
IntelliJ creates import statements which fail on runtime after (ts) transpile

### ISSUE THREAD

**Issue by logemann** [google/clasp#268]
When coding with IntelliJ which is fully typescript capable, when coding a line like this:

```ts
let message:GmailMessage = getCurrentMessage(event);
```

IntelliJ generates an import statement like this:

```ts
import GmailMessage = GoogleAppsScript.Gmail.GmailMessage;
```

This import statement becomes after transpiling and pushing: 

```ts
var GmailMessage = GoogleAppsScript.Gmail.GmailMessage;
```

But this statement fails during script runtime. Problem is, without the import, I don't have any autocomplete in my IDE and of course the IDE flags the source as invalid.

How to handle that situation? I simply can't remove those lines manually in the Online Editor every time I have pushed. That would be a nightmare :)

## Expected Behavior

No runtime error.

## Actual Behavior

ReferenceError: "GoogleAppsScript" is not defined. [line: 9, function: , file: src/GetContextualAddOn]

## Steps to Reproduce the Problem

  1. use IDEA to code typed source code against Gmail AppsScript API
  2. push the results
  
## Specifications

  - latest IntelliJ IDEA on Mac
  - Version (`clasp -v`): clasp 1.5.0
  - OS (Mac/Linux/Windows): Mac

**Comment by logemann** [comment]
a different style of import results in error both in VSCode and IntelliJ.

<img width="930" alt="bildschirmfoto 2018-07-28 um 13 16 41" src="https://user-images.githubusercontent.com/346353/43356004-a110a73a-9268-11e8-8979-78194787d0e2.png">

**Comment by grant** [comment]
I've updated the above comment with syntax highlighting.
I believe you should not need to use import statements, just install the types. I've tried with VSC.

I'll check about handling `import`s better, perhaps removing them before transpiling/pushing.

Does deleting them, then pushing work? (aside from the lack of autocompletion)

**Comment by logemann** [comment]
When i dont use imports, i dont get any autocompletion at all and the code is flagged with lots of errors. This is kind of unusable then.

VSC flags also errors but doe autocompletion nevertheless. 

To your question. Yes, deleting the imports and pushing works. But thats really an ugly coding workflow. Of course i can tell IDEA not to do imports at all which gives a bad coding experience in any case. I mean, using typescript and then dont having types and completion on coding? :-)

**Comment by grant** [comment]
I will experiment with a solution that comments out the import line when pushing.

```ts
// import GmailMessage = GoogleAppsScript.Gmail.GmailMessage;
var greeter = function (person) {
    return "Hello, " + person + "!";
};
function testGreeter(event) {
  let message:GmailMessage = getCurrentMessage(event);
}
```

I created the 3rd party lib, so I can follow-up there.

**Comment by grant** [comment]
Can you try installing the latest version of clasp `1.5.1`, and see if the IntelliJ setup works?

**Comment by logemann** [comment]
grant.. you rock! Now it works like a dream. You comment out the imports right? 

Had some trouble testing. Can it be that you need to deploy a new version to see changes in effect in the addon? A little bit weird because in the online editor i could just change the source and i was ready to go. Now with the need to create versions, i also need to install the addon again and again because a new version generates a new addon-Id which i need to install.

Shouldnt be this way i assume. Perhaps its also a weird caching thing on browser side. But thats a different story. I would put up a blog entry pretty soon to showcase the clasp way of developing addons with typescript. This is huge.

**Comment by grant** [comment]
Yay! I'll close this issue. The imports are commented so you can still see them but they won't mess up the code.

Do note that multi-line imports don't work, but it doesn't look like the types have that for IntelliJ. i.e.
```ts
import {
  ...
} from '@types/google-apps-script';
```

Please create a new one if you see any other issues or have feature requests.
