### ISSUE TITLE
Clasp commands should have consistent order to standard checks

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#278]
So far I see these 3 checks most commonly appearing:

`checkIfOnline()`
`loadAPICredentials()`
`getProjectSettings()`

However, we call them in different orders on different commands (look at `clasp pull` vs `clasp push` for example.

We should pick an order and standardize, or create a wrapper that does all three.

**Comment by grant** [comment]
Why does this matter? It looks like we are relatively straightforward with the order we test these checks.

It looks like we could do a `loadAPICredentials` check in the above order for `pull`, but that's the only case where I see we could add it.

We could also probably change these checks into decorators, but I don't see a huge benefit.

**Comment by campionfellin** [comment]
It is not super important, more of a stylistic thing and I think `pull` is the only one that is in a different order from everything else. Closing as it's not as important as other issues.
