### ISSUE TITLE
Clasp deploy doesn't work as expected

### ISSUE THREAD

**Issue by lgordey** [google/clasp#286]
## Expected Behavior
After making local changes in `someFunction` I expect that after
```
clasp push
clasp deploy
clasp run someFunction
```
I'll see the result with just pushed local changes.

## Actual Behavior
In fact after `clasp push` I should go to script gui and deploy it as API executable (followed instructions from here https://github.com/google/clasp/pull/172) using the mouse

![image](https://user-images.githubusercontent.com/5946242/43946316-bef5a604-9ca6-11e8-826d-f03e1c6de91f.png)

Only after that action I can run 
```
clasp run someFunction
```
and see the actual result.

Making `clasp deploy` or `clasp redeploy` doesn't help me to solve this.
Actually It adds new version (I can see it in gui) but `clasp run someFunction` shows me the old results of previous function state.

## Steps to Reproduce the Problem

  1. Change function code 
  1. `clasp push`
  1. `clasp deploy`
  1. `clasp run someFunction`

## Specifications

  - Node version: `10.3.0`
  - Version: `1.5.2`
  - OS: macOS High Sierra `10.13.5`

Maybe I'm doing something wrong?

**Comment by lgordey** [comment]
I guess it's related to https://github.com/google/clasp/issues/63

**Comment by grant** [comment]
I think `redeploy` should work. I believe modifications to the `appsscript.json` are required.
The web UI changes the `appsscript.json`, it's a bit confusing.

**Comment by grant** [comment]
I think this issue should be fixed. The main issue being the manifest is out of sync between the local code and server code.

Please re-open with more specific instructions to reproduce the error.
