### ISSUE TITLE
clasp create --rootDir ./dist

### ISSUE THREAD

**Issue by fossamagna** [google/clasp#288]
## Expected Behavior

You should be able to create specify `rootDir`. `rootDir` is specified the local directory in which clasp will store your project files. Also `rootDir` is store in `.clasp.json`.

```
clasp create --rootDir ./dist
```

.clasp.json
```json
{
    "scriptId": "<SCRIPT_ID>",
    "rootDir": "./dist"
}
```

## Actual Behavior

After `clasp create`, You must move pulled files and edit .clasp.json.

```
clasp create --rootDir ./dist
mkdir ./dist
mv appsscritp.json ./dist/
```

**Comment by grant** [comment]
Valid issue, wouldn't be hard to add.
