### ISSUE TITLE
Custom file extension on `clasp pull`

### ISSUE THREAD

**Issue by grant** [google/clasp#293]
## Expected Behavior

Right now `clasp pull` defaults Apps Script files to `.js`.

A user should be able to specify which file extension should be used when pulling new files.

Solution: Add a new property to `.clasp.json`:

```
{
  'fileExtension': 'gs'
}
```

Other values could be `'js'` or `'ts'` (or anything else).

## Actual Behavior

All pulled files have `.js`.

**Comment by DimuDesigns** [comment]
@grant With Apps Script slated for an upgrade to the V8 engine, will the *.gs extension be changed to *.js? If that is the case then this issue is moot. However, if the *.gs file extension is going to be retained then it makes sense to support this feature.

**Comment by grant** [comment]
Technically, the server stores [`SERVER_JS` in the `FileType` field](https://developers.google.com/apps-script/api/reference/rest/v1/File#filetype). The `gs` is just displayed in the old UI, and that is historically what our samples have as the file extension. I'm recommending the file extension to be renamed from `gs` to `js` at some point, since in reality, Apps Script is not a whole new language. It's JavaScript.

The V8 change would be a nice point to say "let's use js like everyone else, rather than gs".

The `gs` name was chosen a few years ago for some reason, and so we have historically used that extension for all samples and in the online IDE.

**Comment by rubenrivera** [comment]
I thought that the `.gs` extension is used to prevent confusions between server-side code and client-side code.

**Comment by grant** [comment]
> I thought that the `.gs` extension is used to prevent confusions between server-side code and client-side code. 

I think the the original choice was to make the distinction between Apps Script (special Google integrations, globally-scoped functions) and web JavaScript or Node.

You cannot create client-side `JS` files in Apps Script, only `HTML` files with inline `CSS` and `JS` in them.

**Comment by sat0yu** [comment]
I created a PR https://github.com/google/clasp/pull/304 for this issue
could you check that whether I'm heading the right direction or not, thanks.

**Comment by grant** [comment]
@sat0yu created #304 which should fix this.
I will close this issue when clasp is published on npm (probably next week).

**Comment by grant** [comment]
This should have been added in one of the recent versions of clasp.
