### ISSUE TITLE
What is head and what is web app meta-version?

### ISSUE THREAD

**Issue by nitrocode** [google/clasp#299]
When I run `clasp deployments` I get the following output

```
5 Deployments.
- AK... @HEAD
- AK... @20
- AK... @21
- AK... @28 - web app meta-version
- AK... @22
```

what is `HEAD` and what is the `web app meta version`? I deployed new and that created 28 so I'm assuming the `web app meta version` is the currently released version and if that's true what could `HEAD` possibly be?

**Comment by grant** [comment]
`HEAD` is described here: https://developers.google.com/apps-script/concepts/deployments#head_deployments
"web app meta-version" is a description for that deployment.
