### ISSUE TITLE
Install on mac fails

### ISSUE THREAD

**Issue by whitecoop** [google/clasp#3]
I'm running MacOS 10.11.6.

I ran the install with `npm i @google/clasp -g`.  After the install `clasp -h` output `-bash: clasp: command not found`.

I then tried `sudo npm i @google/clasp -g` and got the same result.

I also restarted my terminal after both installs.

Looks like a path thing, but I haven't dug further. `node -v` gives `v5.4.0` and `npm -v` gives `v3.3.12`

**Comment by grant** [comment]
Can you see anything in `/usr/local/bin/clasp`?
Have you installed other global node modules successfully?

**Comment by deinspanjer** [comment]
I just installed on OSX 10.12.6 (16G1114) with the commands listed in the readme and it seems to work fine.

**Comment by whitecoop** [comment]
> Can you see anything in /usr/local/bin/clasp?

I didn't, but there were odd things going on with another global module that I had installed (install was successful, but commands weren't found) to test global modules, so I ended up doing a clean install of my mac (it's been overdue for a while and this happened to be a good time to do it) and clasp is now installed successfully. Your guess is as good as mine on what was up before, but everything is running now.

**Comment by chechedotmx** [comment]
Fails if you installed node with brew.. check this link 
https://stackoverflow.com/questions/53161693/unable-to-run-clasp-from-command-line

Re-installing directly with node installer https://nodejs.org/en/download/ fix this issue
