### ISSUE TITLE
Empty files have "undefined" as contents

### ISSUE THREAD

**Issue by michaelwdemo** [google/clasp#30]
## Expected Behavior
Empty gs files in apps script should be empty on local filesystem

## Actual Behavior
Local file contains "undefined"

## Steps to Reproduce the Problem

  1. create an empty gs file in apps script
  1. clasp clone the apps script project
  1. observe that the local file contains "undefined"

## Specifications

  - Node version (`node -v`): 5.8.0
  - Version (`npm list | grep clasp`): Unknown but from https://github.com/google/clasp/commit/bbf93d714ca6f8ea788f1081f54bb4483162e4bc
  - OS (Mac/Linux/Windows): Linux

**Comment by grant** [comment]
Thanks for the bug report @michaelwdemo! I'll be sure to address this one in the next release.
