### ISSUE TITLE
Built and test locally?

### ISSUE THREAD

**Issue by grant** [google/clasp#306]
## Expected Behavior

Would it be possible to built and test Apps Script/HTMLService locally?

## Actual Behavior

You can't test HTMLService locally today.

**Comment by labnol** [comment]
Thanks, @grant!

**Comment by grant** [comment]
Note: This would require extensive effort in rebuilding the HtmlService infrastructure.

**Comment by sqrrrl** [comment]
Closing as this is out of scope for clasp. The idea of an apps script local emulator is a good one, but it's better done as an independent project.
