### ISSUE TITLE
Unknown option:  --ownkey 

### ISSUE THREAD

**Issue by glittle** [google/clasp#308]
(Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.)

## Expected Behavior
Login and store credentials locally.

## Actual Behavior
  error: unknown option `--ownkey'

## Steps to Reproduce the Problem

  1. Run "clasp login --ownkey"

## Specifications

  - Node version (`node -v`):  v6.11.3
  - Version (`clasp -v`):  1.5.3
  - OS (Mac/Linux/Windows):  Windows 10.0.17134.228

**Comment by grant** [comment]
Hi @glittle, I think this is an issue with the docs, which I updated above.
Can you try `clasp login --creds "./creds.json"` where `creds.json` is in the path you run the command from?
