### ISSUE TITLE
Make Travis Pass

### ISSUE THREAD

**Issue by grant** [google/clasp#309]
## Expected Behavior

Travis should be green.

## Actual Behavior

Travis is failing due to a [simple error](https://travis-ci.org/google/clasp):
```
  1) Test clasp logs function
       should prompt for logs setup:
     AssertionError: expected null to equal 0
      at Context.<anonymous> (tests/test.js:8:11002)
```

**Comment by campionfellin** [comment]
According to the the Node docs here 

(https://nodejs.org/api/child_process.html#child_process_event_exit) only one of `code` or `signal` needs to be non-null for child processes, which is what we use for testing.

Looks like only the Node7 tests are failing. Using v7.10.1 I get the exit `code` to be `null` and the exit `signal` to be `SIGINT`.

Using Node10 (v10.9.0) the exit `code` is `0` and the `signal` is `null`.

Not sure why this is breaking all of the sudden with Node7, though it looks related to this commit: https://github.com/google/clasp/commit/a47a2a7e02c1ef3d1df1fc2d7ecbec49ea9e44d0

**Comment by campionfellin** [comment]
Fixed with: https://github.com/google/clasp/pull/328

Closing.
