### ISSUE TITLE
outdated npm version

### ISSUE THREAD

**Issue by hassansin** [google/clasp#324]
## Expected Behavior
 `clasp create --rootDir` command should recognise `rootDir` option.

## Actual Behavior

Throws error saying: 
```
error: unknown option `--rootDir'
```

## Steps to Reproduce the Problem

  1. `npm i @google/clasp -g`
  2. `clasp create some-project --rootDir './dist'`

## Specifications

  - Node version (`node -v`): v8.7.0
  - Version (`clasp -v`): 1.5.3
  - OS (Mac/Linux/Windows): Linux

**Comment by grant** [comment]
This is a known issue. I'm trying to finish merging @mainmode1 PRs/features before publishing.
