### ISSUE TITLE
Re-add `logs --setup` functionality

### ISSUE THREAD

**Issue by grant** [google/clasp#326]
## Expected Behavior

It should be easy to add a project id from a command line.

## Actual Behavior

`--setup` was removed in this commit: https://github.com/google/clasp/commit/8b65ad7978ab436bbcb461b611d60f6cead1441e#diff-0430413d1b6fa9f0e832eb2c7dfd0a37L213
Also see: https://github.com/google/clasp/pull/301#discussion_r213118716

**Comment by mainmode1** [comment]
Agreed, better to have a means of manual settings overwrite via interactive prompts or CLI options for scripting. Per #301 ([comment](https://github.com/google/clasp/pull/301#discussion_r213118716) & [follow-up reply](https://github.com/google/clasp/pull/301#discussion_r213534114)) perhaps include in scope of issue:

`clasp logs [--setup | --projectid <id>]`
`clasp run --setup`

and also:

`clasp create --ext <ext>`
`clasp clone --rootdir <dir> --projectid <id> --ext <ext>`
`clasp pull --ext <ext>`

...then refactor [saveProject({ options })](https://github.com/google/clasp/blob/master/src/utils.ts#L387) to merge settings.
