### ISSUE TITLE
Looks like you are offline || Error: read ECONNRESET proxyIpAddress:port

### ISSUE THREAD

**Issue by sjlee-jlp** [google/clasp#332]
Two issues.
While hard wired in, on the corporate proxies I get the first error.
While on our open WiFi, I get the second error.

##
 # Error 1

## Expected Behavior
Logged in! You may close this page.

## Actual Behavior
Error: Looks like you are offline.

## Steps to Reproduce the Problem

  1. clasp login

## Specifications

  - Node version: v10.9.0
  - Version: 1.5.3
  - OS: Windows 10 Version 1709 (OS Build 16299.611)

##
# Error 2

## Expected Behavior
Logged in! You may close this page.

## Actual Behavior
Error retrieving access token: Error: read ECONNRESET proxyIpAddress:port

## Steps to Reproduce the Problem

  1. clasp login
  1. log in to account via browser window that opened
  1. wait

## Specifications

  - Node version: v10.9.0
  - Version: 1.5.3
  - OS: Windows 10 Version 1709 (OS Build 16299.611)

**Comment by puentesdiaz** [comment]
Me too. 
`clasp login` 
return
`Error: Looks like you are offline.`

Iam behind proxy corporative, too

**Comment by grant** [comment]
@sjlee-jlp or @puentesdiaz Can you file a bug in https://github.com/sindresorhus/is-online?

**Comment by sjlee-jlp** [comment]
Installed is-online and the is-online-cli.

CLI returns:

> c:\>is-online
> × Offline

However, I'm quite clearly online...

**Comment by grant** [comment]
Can you let me know when you filed the bug in `is-online` and link the bug here so we can see if we can solve the root issue?
We may have to disable it if it is really not working.

**Comment by campionfellin** [comment]
May not necessarily be a bug in `is-online`. That package checks 3 sites:

https://github.com/sindresorhus/is-online#how-it-works

Could just be that all 3 are blocked on your network.

**Comment by sjlee-jlp** [comment]
Going through and checking against each of these manually:

Each of these return as expected icanhazip.com, icanhazptr.com, icanhaztrace.com, icanhaztraceroute.com, icanhazepoch.com.

icanhazproxy.com doesn't return anything.

https://diagnostic.opendns.com/myip returns as expected.

http://captive.apple.com/hotspot-detect.html returns as expected.

So could be something weird happening with is-online.

**Comment by grant** [comment]
I think this issue is fixed.
You shouldn't get the error `Error: Looks like you are offline` if you have a proxy.
https://github.com/google/clasp/commit/cec4eeb8d879dd8ac97bf7e394e852a5c1426c7a

Please re-open if this is still an issue.

**Comment by Nu11u5** [comment]
Make sure that the `https_proxy` environment variable is set correctly.  This value is typically used by terminal applications for proxy settings and is used by clasp.
