### ISSUE TITLE
Can I set Time-driven triggers with `clasp`?

### ISSUE THREAD

**Issue by abetomo** [google/clasp#335]
## Expected Behavior

https://developers.google.com/apps-script/guides/triggers/installable#time-driven_triggers

I want to set time-driven triggers with `clasp`.

## Actual Behavior

Is there no option for setting?

## Steps to Reproduce the Problem

-

## Specifications

```
% clasp --version
1.5.3
```

**Comment by grant** [comment]
Trigger management isn't supported programmatically afaik.

Please file an issue here:
https://issuetracker.google.com/issues?q=componentid:191640

Then comment with the link to the issue and upvote it.

---

Perhaps when `clasp run` is working, we could create triggers from the CLI by running a function that invokes `ScriptApp.newTrigger`. Can you check if running Apps Script to create a trigger works?

**Comment by abetomo** [comment]
Thank you for your reply.
I created an issue.
https://issuetracker.google.com/issues/116677273

Also thank you for your advice to use `ScriptApp.newTrigger`!

**Comment by mTorres** [comment]
> Can you check if running Apps Script to create a trigger works?

I can confirm that creating triggers dinamically from Apps script works. I have a quite complex Spreadsheet that collects answers from a Google Form and I automatically install a trigger for the onAnswerRecived (this is not the name but hope you get what I mean).

**Comment by abetomo** [comment]
An error occurred when executing `ScriptApp.newTrigger`.

```js
function setTrigger () {
  ScriptApp.newTrigger('funcName')
  .timeBased()
  .everyHours(4)
  .create();
}
```

```
% clasp --version
1.6.3
% clasp run setTrigger
Exception: ScriptError Script has attempted to perform an action that is not allowed when invoked through the Google Apps Script Execution API. [ { function: 'setTrigger', lineNumber: 5 } ]
```

**Comment by takanakahiko** [comment]
Execution API cannot create Apps Script triggers.
See https://developers.google.com/apps-script/api/how-tos/execute#limitations

**Comment by abetomo** [comment]
@takanakahiko Thank you.
