### ISSUE TITLE
clasp login return offline

### ISSUE THREAD

**Issue by puentesdiaz** [google/clasp#336]
After install clasp via npm over corporate proxy, i have no problem
i can run : clasp -v  ..fine...
but ...
## Steps to Reproduce the Problem
  1. clasp login
  >Error: Looks like you are offline.

## Specifications

  - Node version (`node -v`): 10.10.0
  - Version (`clasp -v`): 1.5.3
  - OS :Windows

**Comment by grant** [comment]
I'll have to make the internet check optional.
Can you try:
`clasp login --no-localhost`

**Comment by puentesdiaz** [comment]
> clasp login --no-localhost



> I'll have to make the internet check optional.
> Can you try:
> `clasp login --no-localhost`

Yes i can, but throw same error

**Comment by grant** [comment]
OK, I'll fix this issue.

Remove this line:
https://github.com/google/clasp/blob/master/src/auth.ts#L165

**Comment by aakasaka** [comment]
I have the same problem with login under the proxy.  
When I comment out the lines using `is-online` , the message "Looks like you are offline" disappeared and my browser open google auth page, but error showed in console and login failed.

```
Error retrieving access token: Error: write EPROTO 19024:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252:
```

Is that a same problem with #8 ?

**Comment by grant** [comment]
I think this is fixed with the proxy support referenced above.
We skip checking is-offline when there's a proxy.

**Comment by thedrs** [comment]
I solved this issue - here is the story:

I am on windows in a very restricted corporate enterprise which has to use an http and https proxy.
We do have normal google services accessible in the browser.
Obviously 'clasp login' does not work without a proxy, it gives:
**_Error retrieving access token: FetchError: request to https://oauth2.googleapis.com/token failed, reason: connect ETIMEDOUT 216.58.212.202:443_**
 (It does work if i disconnect my computer from corporate and connect to public internet)

So i defined these two env variables in cmd (you can also do it in git bash console, just replace "set" with "export"):
set HTTP_PROXY=http://proxy.mycompany.com:80
set HTTPS_PROXY=https://proxy.mycompany.com:80
(our corporate proxy uses port 80 for both http and https !)

this is the error i got:
**_Error retrieving access token: FetchError: request to https://oauth2.googleapis.com/token failed, reason: write EPROTO EC110000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:_**

The solution to my problem was that our https proxy used an http address, so i fixed the set to the following :
set HTTPS_PROXY=http://proxy.mycompany.com:80
(note the http:// and not https:// on the right hand side)

Hope i helped others here too
