### ISSUE TITLE
Feature Request - Additions to CLI UI

### ISSUE THREAD

**Issue by cwatson88** [google/clasp#34]
@grant 
Would you be open to adding some stying to the CLI like Firebase CLI? 
_If so, it would be great to be involved!_

![image](https://user-images.githubusercontent.com/2564574/35770719-5a6ee816-0918-11e8-8abc-5f29318b0fde.png)

I have some suggestions using the same NPM packages that are used in the Firebase CLI. 

Firstly is to add something to make the main clasp text stand out using **figlet.js** (possibly something like the images below but other suggestions are welcome): 
![clasp-cli](https://user-images.githubusercontent.com/2564574/35770836-07600774-091b-11e8-8db0-f48944f96ae3.png)

Second is to add some styling to errors and user input with **chalk** and **Inquirer.js**. An example of this might be to ask the user to set a name for otherwise undefined projects or to get them to select deployment versions. Similar to the Firebase CLI and Webpack CLI.

Thanks 👍

**Comment by grant** [comment]
Hi @cwatson88, I don't think it's necessary to add a huge "CLASP" ASCII art to the root command.

If there is somewhere specific where using chalk would be useful, we could maybe add that.

**Comment by cwatson88** [comment]
Yep, I agree with you @grant  (I tried 😅). 

Yeah maybe with chalk just to allow the console log errors and warnings to stand out but it's not urgent at the moment.

Thanks for the reply!
