### ISSUE TITLE
Question from a beginner

### ISSUE THREAD

**Issue by codesurfer1** [google/clasp#341]
Hi.

Answer please about clasp:
1. Is it possible to develop on pure JavaScript, or do I have to write on TypeScript only?
2. In what IDE is better to developing Apps Script with clasp: VSCode or WebStorm?
3. I read the documentation, but still do not understand why my project does not see such classes as SpreadsheetApp, DocumentApp and other?

Thank you.

![123-2](https://user-images.githubusercontent.com/43304244/46297739-160d1800-c5a6-11e8-890f-78a00782e222.png)

**Comment by grant** [comment]
1. I believe you can write plain JavaScript, but I think you should install `@types/google-apps-script` to get the autocompletion. Using `.ts` seems like it's required. There may be a config fo have types with just `.js`, but I'm not sure of editor settings. The definitions are in TS so it makes sense if TS is required.
2. I like VSCode, but I think WebStorm should work just as well.
3. I think you need to use `.ts`

**Comment by codesurfer1** [comment]
I understood.
Thank you.

I will leave this topic open for now, in case there are more questions.

**Comment by codesurfer1** [comment]
I understood.
Thank you.
