### ISSUE TITLE
API Library Typings Support

### ISSUE THREAD

**Issue by j-frost** [google/clasp#342]
Currently there seems to be no support for APIs that Google Cloud users may activate from https://console.cloud.google.com/apis/library. In AppsScripts, users may make these APIs accessible after having activated them. This enables auto-completion as well. 

Are there typings for those anywhere and if yes, are they bundled in external npm packages? I wasn't able to find any. 

## Expected Behavior
Some way (maybe additional packages?) exists to enable auto-completion for APIs like `AdminReseller`. 

## Actual Behavior
There seems to be no way other than adding `: any` typings yourself to use these APIs. 

## Steps to Reproduce the Problem

  1. Activate an advanced API via console.cloud.google.com/apis/library
  2. Go to Resources > Advanced Google Services... in any Google Apps Script and activate that same API
  3. Observe auto-completion (and of course lack thereof offline)

## Specifications

  - Node version (`node -v`): v.10.11.0
  - Version (`clasp -v`): 1.6.0
  - OS (Mac/Linux/Windows): Linux

**Comment by j-frost** [comment]
Workaround to appease the compiler btw is to comment it `// @ts-ignore`. Depending on setup you'll have to do that multiple times though, so it's not a great solution I don't think.

**Comment by j-frost** [comment]
@grant Absolutely, I'd love to help. Is there anything in particular that comes to mind?

**Comment by grant** [comment]
@j-frost Great.

- Can you create a **list** of the Advanced Services that you use in your application? i.e. AdminReseller, Slides, Calendar...
  - I'll create these types first.
- Can you create a **sample that uses the Advanced Service** that we can include in [`google-apps-script-tests.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script-tests.ts)? i.e. should be an example function. It should be annotated with ideal  typescript types.

I'm going to be in the process of making types for all the services (which takes a lot of time). The way I create it uses confidential Google code, so I cannot share it.

However, the best thing you can do is:
- Verify the types that I do publish are correct
- The order in which the types are added.
- If you write a blogpost about this too, that'd be great!

**Comment by grant** [comment]
Typings are being tracked in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29349.
Clasp doesn't have any extra features to add as we already support TS and have a guide for setting it up.

Let's follow up on the above issue.
