### ISSUE TITLE
unhandled promise rejection

### ISSUE THREAD

**Issue by JaimeChavarriaga** [google/clasp#344]
When I try to run some commands with a wrong user, the `clasp` shows error messages caused by problems with the permissions but remains frozen.

## Expected Behavior

Trying to run a command, `clasp` must show an error message and end.

```
$ clasp logs --json
Error: User has not been authorized
(end)
```

*NOTE:* This happens also with other commands such as `clasp deploy`.

## Actual Behavior

The `clasp` application shows an error...

```
 clasp logs --json
- Using local credentials: ./clasprc.json 🔐 Grabbing logs...(node:16843) UnhandledPromiseRejectionWarning: Error: The caller does not have permission
    at createError (/usr/lib/node_modules/@google/clasp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/@google/clasp/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/usr/lib/node_modules/@google/clasp/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:16843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/ Using local credentials: ./clasprc.json 
🔐 Grabbing logs...
```

but remains frozen. I must stop the `clasp` using `[Ctrl]+[C]`

## Steps to Reproduce the Problem

  1. Create an App Script project where users can see the project if they have the link
  1. Login using `clasp`:  `clasp login`
  1. Clone/Pull the content of the above mentioned project:  `clasp clone ....`
  1. Run commands such as `clasp deploy` or `clasp login --json`

## Specifications

  - Node version (`node -v`): v10.11.0  
  - Version (`clasp -v`): 1.6.3
  - OS (Mac/Linux/Windows): Linux -- Ubuntu 18.04.1 LTS

**Comment by grant** [comment]
Thanks for reporting.
There was a recent change in using JS promises (async/await). I'll have to make the error handling a bit better.

Ideally, this is mitigated when multi-user support #42.

**Comment by takanakahiko** [comment]
I think that it is better to use `try/catch` for error handling.

like this.

```js
try {
  deployments = await script.projects.deployments.update({
    scriptId,
    deploymentId,
    requestBody: {
      deploymentConfig: {
        versionNumber,
        manifestFileName: PROJECT_MANIFEST_BASENAME,
        description,
      },
    },
  })
}catch(err){
  return logError(null, err.message);
}
```

**Comment by grant** [comment]
This error shouldn't happen anymore in the next clasp release.
