### ISSUE TITLE
clasp login fails

### ISSUE THREAD

**Issue by topconnector** [google/clasp#345]
(Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.)

## Expected Behavior
clasp login

## Actual Behavior
*** ERROR: (clasp): Can not read from 'login'

## Specifications

  - Node version (`node -v`):v8.9.1
  - Version (`clasp -v`):3.2.0
  - OS (Mac/Linux/Windows):macOS Mojave, 10.14

**Comment by grant** [comment]
@topconnector Can you print the `clasp -v` again? Clasp is only at `1.6.3` right now. I can't reproduce the problem yet.

**Comment by grant** [comment]
Upgrade clasp and post here if you're still seeing the problem.
