### ISSUE TITLE
Error retrieving access token: Error: invalid_grant

### ISSUE THREAD

**Issue by csell5** [google/clasp#35]
I'm getting an odd error when trying to call `clasp login`. I'm successfully logged in and redirected but clasp is claiming an invalid token. I've also tried a few different accounts.

## Steps to Reproduce the Problem

  1. clasp login
  2. allow the right account
  3. login successful return to terminal.
  4. Error retrieving access token: Error: invalid_grant

## Specifications
  - Node version: 8.9.2
  - Version (`npm list | grep clasp`):

⟩ npm list -g | grep clasp
├─┬ @google/clasp@1.1.0

  - OS mac

**Comment by grant** [comment]
Thanks for letting me know @csell5. 1.1.1 should fix this.

Install the latest `clasp` and it should work now.

**Comment by csell5** [comment]
and indeed it did! Thanks!

**Comment by froggr** [comment]
This error is happening for me on clasp@1.1.4 (MacOs) with Node 9.6.1.

**Comment by grant** [comment]
@froggr looking into it, in the meantime please install `npm i -g @google/clasp@1.1.1`.

**Comment by grant** [comment]
@froggr Try to install the latest version (1.1.5).

**Comment by NicholasKobald** [comment]
Thanks! that worked for me

**Comment by froggr** [comment]
@grant thanks! Confirmed working with 1.1.5

**Comment by seeker1983** [comment]
I'm getting this on clasp 2.3.0 / OSX 10.13.6.

Can anyone explain what the error is about and how to workaround this?

**Comment by OptimusRahul** [comment]
I'm getting this on clasp 2.4.1 / OSX 12.2.1

Can anyone please help me, I tried re-installing the clasp but it's not working.

Browser sign-in is successful, getting issues in the terminal.
<img width="1728" alt="Screenshot 2022-02-14 at 12 45 46" src="https://user-images.githubusercontent.com/25546644/153817177-3a778999-d7ff-4a2e-a1b6-bc587d6a8210.png">

**Comment by seeker1983** [comment]
Delete file with access token and run "clasp login --creds XXX" again.

I do this pretty often, cause the old token seem to expire in ~week.

Also, when in browser make sure to check all checkboxes cause sometime they
seem to unchecked by default

пн, 14 февр. 2022 г., 09:18 Rahul Srivastava ***@***.***>:

**Comment by OptimusRahul** [comment]
I was having `.clasprc.json` in another machine, used that same file resolved my issue.

Thanks for the help @seeker1983 🙂, will look into the `--creds` flag also.

**Comment by Divide-By-0** [comment]
Running `clasp login` again worked.

**Comment by muthukumars** [comment]
clasp@2.4.2 latest version , is show as below

Error retrieving access token: Error: invalid_grant

my previous .clasprc.json exists and the expiry_date of the token is expired. so I need to get this refresh token. I cannot do clasp login because it will popup browser.

I would like to implement this clasp login in jenkins and uses refresh token to refresh it. but refresh token is not happening.  I tried 1.1.5. but some of the methods are deprecated and is not working. this is happen in 2.4.2 too
