### ISSUE TITLE
@types/google-apps-script

### ISSUE THREAD

**Issue by KurtWAndrews** [google/clasp#352]
I'm pouring over all the documentation I can find on developing Google Apps Script using Typescript.  I'm trying to set up my Pixelbook for local development in a Crostini container.  The thing I'm not sure about is, do I have to install @types/google-apps-script in each project directory?  My project directory will end up looking something like this:
```
/home/kurtandrews
|__/client_1
   |__/project_1
   |__    .
   |__    .
   |__    .
   |__/project_n
|__/client_2
|__   .
|__   .
|__   .
|__/client_n
```
Can the types be installed at a higher level, or globally so that vscode can use them? Thanks in advance for your help.

**Comment by grant** [comment]
I'm not sure. Did you try it out?
You probably need to install per project.

**Comment by grant** [comment]
This is more of a TypeScript question than a clasp question.
You'll need to install the types per every npm module you have. It really depends on your directory/npm structure.

**Comment by KurtWAndrews** [comment]
Right now, I'm only using npm to install clasp and Typescript to develop
Google App Scripts.  I have some questions about GAS project structure, but
I'm not sure where to ask them.

Thanks for your help.

Regards,

Kurt

**Comment by grant** [comment]
Stackoverflow is a good resource for general questions.
