### ISSUE TITLE
Provide Available Function Names in clasp run

### ISSUE THREAD

**Issue by grant** [google/clasp#354]
## Expected Behavior

- `clasp run` by itself should give a list of possible function names.
  - This would be possible by the newish [`functionSet`](https://developers.google.com/apps-script/api/reference/rest/v1/File#functionset) property. (8/2/2018)

## Actual Behavior

We don't use functionSet.

**Comment by takanakahiko** [comment]
How do we display function names?

example :

1. switch arg `functionName` to optional : `clasp run [functionName] [--nondev]`
2. If we don't provide a `functionName` ,  use [Inquirer](https://github.com/SBoudrias/Inquirer.js/) to list function names.

**Comment by grant** [comment]
Use `inquirer` to `prompt` the user for function names, like we do for [`create`](https://github.com/google/clasp/blob/b867738b87fe39e78a43691bc3c840fd648a7860/src/commands.ts#L119), `clone`, etc.

1. `clasp run [functionName]`
1. If we don't have the `functionName`, use inquirer#prompt to get the name. Provide a list of possible names from here: [`script.projects.getContent#files[N]#functionSet[O]#name`](https://developers.google.com/apps-script/api/reference/rest/v1/projects/getContent) (map over all files)
1. `script.run` with the name.

Eventually add autocompletion like this:
https://www.npmjs.com/package/inquirer-autocomplete-prompt#example
![inquirer](https://user-images.githubusercontent.com/744973/48404998-1c141e00-e73a-11e8-9d1e-d6bd052e1d1a.gif)

**Comment by grant** [comment]
I added fuzzy filtering to the autocompletion. For some reason, the inquirer prompt wasn't quite working when I tried it.

<img width="550" alt="screen shot 2018-11-23 at 15 43 17" src="https://user-images.githubusercontent.com/744973/48962603-a62c6580-ef36-11e8-9df8-d53d28efa7ea.png">
