### ISSUE TITLE
clasp redeploy without version specified

### ISSUE THREAD

**Issue by jsarafajr** [google/clasp#366]
## Expected Behavior
It would be good to have the ability to use `clasp redeploy` command without version specified so that clasp would create one for us. Same as `clasp deploy` works - it creates a new version when no version passed as an argument. The use case for this is deploying from CI systems (see below)

## Actual Behavior 
Not sure about other Apps Script projects, but for Gmail add-ons you have to specify a particular Deployment ID which will be available to the users through G Suite marketplace. So every time you're delivering the updates you'll have to update existed deployment instead of creating a new one, which is not that easy to do programmatically, as basically you need:
1. to create a new script version `clasp version ...`
1. somehow retrieve created version number (parse clasp output of the previous command or use googleapis directly)
1. and then you can finally use `clasp redeploy <deploymentId> <created version> <description>`

Probably it would be reasonable to make version parameter optional, e.g.
`clasp redeploy <deploymentId> <description>` - creates new version and updates deployment with that version
`clasp redeploy <deploymentId> <version> <description>` - updates deployment with specified version

**Comment by grant** [comment]
I'll have to make redeploy easier in `clasp@2`.

**Comment by jsarafajr** [comment]
Nice! Good to know @grant 🙂
Is there an ETA for v2?

**Comment by grant** [comment]
Hoping for ~December 14th.
I've been a bit busy giving talks about Apps Script recently. Big talk next week at angularconnect.com

**Comment by takanakahiko** [comment]
I agree with this plan. ( https://github.com/google/clasp/pull/372#issuecomment-435435683 )

Is this plan yet to be decided?
If so, I will create a PR to modify the deploy command.

**Comment by takanakahiko** [comment]
If you do not specify `deployment ID`, we deploy the latest deployment, right?
In that case, I think there is no way to create a new deployment.

**Comment by grant** [comment]
If there's no `deploymentId`, [create a deployment](https://developers.google.com/apps-script/api/reference/rest/v1/projects.deployments/create) with the latest version.

**Comment by takanakahiko** [comment]
@grant 

Umm...
`--description [description]` and `--version [version]` can not be executed on `commander.js`
We seems necessary to change the name of the arguments.

https://github.com/tj/commander.js/issues/516

Example:

`--verrsion [version]` -> `--versionNumber [version]`
`--description [description]` -> `--desc [description]`
