### ISSUE TITLE
Override appsscript.json Warning

### ISSUE THREAD

**Issue by grant** [google/clasp#368]
## Expected Behavior

Report warning if the user will override `appsscript.json` when pushing.

## Actual Behavior

Users get confused why using the UI to deploy or add libs don't work when using clasp.

## Steps to Reproduce the Problem

  1. clasp create
  1. add a lib
  1. clasp push
  1. Observe the lib is "deleted" with push. (You first must pull)

**Comment by takanakahiko** [comment]
Fixed by #431 . OK?
