### ISSUE TITLE
Missing Type Definitions for OverGridImage

### ISSUE THREAD

**Issue by dustinmichels** [google/clasp#370]
Not sure if this is the right place for this comment, but I'm using Clasp and Typescript installed via:
```
npm install -g @google/clasp
npm i -S @types/google-apps-script
```
The type system seems to be missing a definition for [ `OverGridImage`](https://developers.google.com/apps-script/reference/spreadsheet/over-grid-image).

- It thinks [`sheet.insertImage()`](https://developers.google.com/apps-script/reference/spreadsheet/sheet#insertImage(String,Integer,Integer)) returns `void` when it actually returns  `OverGridImage`.
- I want to declare an object to be type `GoogleAppsScript.Spreadsheet.OverGridImage` but it doesn't seem to exist.
- The type system doesn't seem to know about the [`sheet.getImages()`](https://developers.google.com/apps-script/reference/spreadsheet/sheet#getImages()) function either, which returns an array of  `OverGridImage` objects.

Can this be updated? Thanks!

**Comment by grant** [comment]
@dustinmichels Closing in favor of DT. `@` me if needed, but file type issues with the source there.
