### ISSUE TITLE
Warnings / Alternate instructions for Windows users in Codelabs tutorial

### ISSUE THREAD

**Issue by ianhyzy** [google/clasp#375]
## Expected Behavior
The command `mkdir clasp_codelab && cd clasp_codelab` makes a directory and enters it

## Actual Behavior
The command fails as Windows doesn't support the `&&` operator
![image](https://user-images.githubusercontent.com/3400872/47934432-3f6edb80-dea5-11e8-9bb8-d0a4e60d9449.png)

## Steps to Reproduce the Problem

  1. Run the command on any Windows machine
  2. Observe the error

## Specifications

  - Node version (`node -v`): 10.13.0
  - Version (`clasp -v`): 1.6.3
  - OS (Mac/Linux/Windows): Windows 10

Adding a note that says Windows users need to run these separately might be best?

**Comment by grant** [comment]
Thanks.
Can you try the codelab again and see if there's still a problem?
Feel free to re-open the issue if there's some more work to do.
