### ISSUE TITLE
How does CLASP know which project to push to?

### ISSUE THREAD

**Issue by dustinmichels** [google/clasp#379]
I am managing several different CLASP projects, and I am having problems with local files getting pushed to the wrong Google project. I am confused about how `clasp push` knows which project to push to, since I don't see any hidden, `.clasp` files in my local directories with that kind of info, as one sees with Git.

Can I get more information about how CLASP associates local directories with remote projects, to reduce problems with pushing to the wrong project?

**Comment by grant** [comment]
We navigate up the folder heirarchy to find the parent folder with a `.clasp` file. Defaults to current dir.

https://github.com/google/clasp/blob/master/src/dotfile.ts#L95

Be sure parent directories don't have a `.clasp` file.

**Comment by dustinmichels** [comment]
Thanks a lot for your reply. I don't see any `.clasp` files in my project directories or in parent directories.

To fix the issue of pushing to the wrong project, I copy my local project to a `tmp` folder, re-clone the Google project by its script ID, delete all the contents in the cloned folder, copy the contents over from the `tmp` folder then push.

This pushes the files to the correct project, but then I switch to a different directory (representing a different project) and when I type `clasp push` again it uploads to the same Google project as the previous project.

**Comment by dustinmichels** [comment]
I know see I have a single `.clasp.json` file in my user folder, storing a single scriptId. Should I have a file like this in each clasp project directory, or just delete this one in my user folder?

**Comment by grant** [comment]
Each project should have it's own `.clasp.json` file.
It like `.git`. In most cases, you'll want 1 of these per project.

**Comment by dustinmichels** [comment]
Okay, great. These files don't seem to get created automatically by `clasp clone`. Could that be a feature request or a bug?

**Comment by grant** [comment]
`clasp clone https://script.google.com/d/1rAssKxAPxDbHQgawGvDDvPBXNZexODl1-q7qTbB_3qLivZU6ZQd7DBf4/edit`

Should create a `.clasp.json` file. Does it not? If not, please file a new bug.

**Comment by dustinmichels** [comment]
I think the problem was that I had a sneaky `.clasp.json` file lingering in a parent directory.

With that file gone, `clasp clone <scriptId>` _does_ generate a `.clasp.json`, but when I put that file back in the parent directory, `clasp clone <scriptId>` _does not_ generate it.

Thanks for your help.

**Comment by grant** [comment]
Can you file a new bug with specific steps to reproduce the issue? What version are you running?

**Comment by dustinmichels** [comment]
I created a new bug report here: https://github.com/google/clasp/issues/384

Let me know if that is useful!

**Comment by grant** [comment]
OK will continue the conversation on #384.

**Comment by progettazionemauro** [comment]
Suppose that you are managing the project in VSC. Here the fatastic things that you can do with CLASP:
1) I have a GAS project with (let's say) ID "A" after clasp login you can clone the project from GAS to VSC with clasp clone ID ("A")
2) I have a GAS project with ID "A" after clasp clone in VSC you can pull (from inside VSC) the project from GAS to VSC with clasp pull
3) I have a GAS project with ID "A"  in VSC you can push (from inside VSC) the project from VSC to GAS with clasp push
4) I have a GAS project with ID "A"  in VSC you can push (from inside VSC) in another GAS project (let's say ) ID "B" the whole project: the steps are - modifiy clasp.json inside VSC (change ID from A to B) and into the VSC terminal run clasp push. Important! you have to create project with ID "B" before to run clasp command

**Comment by ipcampbell12** [comment]
@progettazionemauro I would like to do number 4 from your list, but I keep getting this output on my terminal: 

No valid /Users/iancampbell/Desktop/GAS/test_app/.clasp.json project file. You may need to `create` or `clone` a project first.
