### ISSUE TITLE
found 2 low severity vulnerabilities ( `npm i` )

### ISSUE THREAD

**Issue by takanakahiko** [google/clasp#380]
## Expected Behavior

`npm i` return no error.

## Actual Behavior

`npm i` return the following result.

```bash
$ npm i
added 733 packages from 867 contributors and audited 2974 packages in 10.883s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

![image](https://user-images.githubusercontent.com/10114717/48039924-3e49f100-e1ba-11e8-8ffd-0ba68ed237cf.png)

## Steps to Reproduce the Problem

  1. clone this repository.
  1. run `npm i` 

## Specifications

  - Node version (`node -v`): `6.4.1`
  - OS (Mac/Linux/Windows): `Mac`

**Comment by takanakahiko** [comment]
Question:
  - Is the npm version for contributor specified?
  - Can I send a PR to fix these?

**Comment by grant** [comment]
Please send a PR. Thanks!

**Comment by takanakahiko** [comment]
@grant Thank you! Is the npm version for contributor specified?

**Comment by grant** [comment]
No. Use the latest version.
