### ISSUE TITLE
`clasp push --watch` pushes even when ignored files change

### ISSUE THREAD

**Issue by pghalliday** [google/clasp#389]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> Ideally, after filing the issue, try to fix the issue with a PR!

## Expected Behavior

`clasp push --watch` only pushes when a file that will be pushed changes

## Actual Behavior

`clasp push --watch` pushes when any file changes and even pushes multiple times when multiple files change (eg. when `.git/*` files change on commits, etc)

## Steps to Reproduce the Problem

  1. run `clasp push --watch`
  1. change `README.md`
  1. All files get pushed even though the `README.md` is automatically ignored

## Specifications

  - Node version (`node -v`): v9.10.1
  - Version (`clasp -v`): 1.6.3
  - OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
Thanks for the report. This is a known issue. PRs welcome!

Solution:
https://github.com/google/clasp/blob/master/src/commands.ts#L82
Check that the file is not an ignored file. Then push.

**Comment by PopGoesTheWza** [comment]
@pghalliday  can you try with clasp 2.2.0 if the issue still occurs?
