### ISSUE TITLE
[Support Request] clasp run fails even though API deployment exists

### ISSUE THREAD

**Issue by j-frost** [google/clasp#391]
## Expected Behavior

`clasp run --dev main` runs function main on the most current API deployment. 

## Actual Behavior

Fails with `Script API executable not published/deployed.`, altough 

```bash
$ clasp deployments   
2 Deployments.
- AKfycbzykaL...qI2EwL1TI @HEAD 
- AKfycbw2xHzsTN8...vUq8CE @2 - oneplatform api meta-version
```

## Steps to Reproduce the Problem

  1. Have project and `clasp push` it
  1. Add version
  1. Deploy version as API executable
  1. Try to run it

## Specifications

  - Node version (`node -v`): v11.1.0
  - Version (`clasp -v`): 1.6.0
  - OS (Mac/Linux/Windows): Linux

**Comment by grant** [comment]
Thanks for the report.
`clasp run` is pretty fragile right now and so I'll check this when I finish `clasp run`.
It would be helpful if you provided more specific repro steps. I.e. what code did your files include?

**Comment by j-frost** [comment]
I've revamped the project into an editor add-on now, so the `main` function is gone. What it did was connect to Sheets and Drive and copy files based on row entries. 

I'm not sure I understand correctly what you mean when you say "what code". It's a customer project, so I can't post the code unfortunately, but I can make a list of which services it uses if that helps you. Is that what you need?

**Comment by grant** [comment]
It’s hard for me to debug without seeing any code or appsscript.json files.

What does your manifest include? Does is have the correct configuration? Deploy via script.google.com to see what you need in your manifest.

**Comment by grant** [comment]
Bump. Can you post some of the `appsscript.json`?

**Comment by grant** [comment]
OK thanks. I'll look into this issue.

**Comment by obelic2** [comment]
Hi, I'm not sure if you have resolved this or not, but I had the same problem of "Script API executable not published/deployed". 

The thing that solved if for me is adding the following in the manifest:
```
"executionApi": {
  "access": "ANYONE"
}
 ```
Before adding this, it only worked on non-dev.

The step is now in the Readme.

<img width="978" alt="screenshot 2018-12-21 13 54 15" src="https://user-images.githubusercontent.com/30458968/50343881-f5ab8480-0528-11e9-90bc-d3ab09776af7.png">

Was run on the latest clasp
Version (clasp -v): 1.7.0

**Comment by grant** [comment]
Please re-open or file a new issue is the instructions are incorrect.
`clasp run` is not super simple to set-up, given many requirements, but the instructions should work.

**Comment by dandv** [comment]
I got the same `Script API executable not published/deployed.` error, because the `clasp run` documentation page didn't mention creating a new API executable deployment. Submitted #1004 to fix this.
