### ISSUE TITLE
Resolve Apps Script Libraries With Clasp+Typescript

### ISSUE THREAD

**Issue by atbmatt** [google/clasp#392]
Is there any way to resolve google apps script libraries in my local IDE (VSCode) using clasp and typescript? Is there any import that can be done? Or is the only way to resolve the library locally to copy the OAuth2 library source code into my project?

## Expected Behavior
Resolve the dependant libraries locally using clasp (if possible). This way linting can pass correctly for testing and debugging.

## Actual Behavior
After installing typescript, referred libraries are not resolved. In this case I am using OAuth2, and I get
`[ts] Cannot find name 'OAuth2'. [2304]`

The script still works once pushed.

## Steps to Reproduce the Problem

  1. Install typescript and @types/google-apps-script `npm install --save typescript @types/google-apps-script`
  2. Configure project to use typescript:
  .clasp.json
  ```
  {
    "scriptId":"id...",
    "rootDir": "src/",
    "fileExtension": "ts"
  }
  ```

  tsconfig.json  
  ```
  { 
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true,
        "types": ["google-apps-script"]
      }
  }  
  ```

  jsconfig.json
  ```
  { 
    "compilerOptions": {
        "checkJs": true
      }
  } 
  ```
  3. Add OAuth2 library to appsscript.json

  ```
  {
    "dependencies": {
      "libraries": [{
        "userSymbol": "OAuth2",
        "libraryId": "1B7FSrk5Zi6L1rSxxTDgDEUsPzlukDsi4KGuTMorsTQHhGBzBkMun4iDF",
        "version": "30"
      }]
    },
  ...
  }
  ```

## Specifications

  - Node version (`node -v`): v8.9.4
  - Version (`clasp -v`):  1.6.3
  - OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
You can use DefinitelyTyped and install types like normal npm modules. Most types are missing currently, so you'll probably need to create your own at the moment.

There are no type definitions for OAuth2 or other libraries afaik.
The way the TS community add TS types is by adding them to DefinitelyTyped. However, this is for npm libraries.

Unfortunately AS libraries are totally separate from npm (they aren't published there). I'd first ask the OAuth2 repo to have a public npm package, then we can proceed to add the types.

**Comment by atbmatt** [comment]
The easiest work around for now was to just insert ts-ignore like so:

```
    // Ignore OAuth2 library resolution when working with clasp
    // @ts-ignore
    return OAuth2.createService('Auth0')
    ...
```
Closing the issue.

**Comment by grant** [comment]
@atbmatt If you want to make a PR to add the ts-ignore suggestion to the typescript guide for future users, that would be great!

**Comment by msembinelli** [comment]
@grant Okay I'm going to do it from this account here in a bit!
