### ISSUE TITLE
command options not work, ie. --title

### ISSUE THREAD

**Issue by machinefriendly** [google/clasp#399]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> Ideally, after filing the issue, try to fix the issue with a PR!

## Expected Behavior
according to the example in doc:  
clasp create --title "My Script" --parentid "1D_Gxyv*****************************NXO7o" --rootDir ./dist  
I use command `clasp create --title "abc"` to create a standalone gas file as shown in README file, 

## Actual Behavior
I got "error: unknown option '--title", then I find [this video tuto](https://youtu.be/-eYK6jG8uEU?t=96) from Jordan Rhea, it looks that '--title' '--type' should not used, but '--rootDir' could be used. 
Am I wrong in document reading or doc should be updated?

## Steps to Reproduce the Problem

  1. clasp create --title "abc"
  1.
  1.

## Specifications

  - Node version (`node -v`): v.8.5.0
  - Version (`clasp -v`): v1.6.3
  - OS (Mac/Linux/Windows): Mac

**Comment by takanakahiko** [comment]
Docs in GitHub repository (ex: readme.md ) is based on version in develop.
If you use v1.6.3(latest),  look the [document on npm](https://www.npmjs.com/package/@google/clasp) .

The option `--title` will probably be available in the next release.

**Comment by grant** [comment]
Yes, please see npm for the currently published version of clasp. GitHub currently has the dev build of clasp. There may be some things that are currently in development that will be published mid December.

Thanks!
