### ISSUE TITLE
'clasp list' Shows ' EPERM: operation not permitted' Error When Installed as None Admin User

### ISSUE THREAD

**Issue by bv-vd** [google/clasp#409]
## Expected Behavior

`clasp list` should list projects

## Actual Behavior

Showing error message
Error retrieving access token: Error: EPERM: operation not permitted, open '%USERPROFILE%\.clasprc.json'

Fixed by change the permission of '.clasprc.json' file from 'read only' to 'read-write'

## Steps to Reproduce the Problem

  1. Install nodejs (with npm) from the zipped package to %USERPROFILE% folder (as Windows local user, not admin)
  1. npm install clasp (and verify)
  1. run `clasp list`
  1. Error message shown
  1. Examine the permission of .clasprc.json file, it should be 'read only'
  1. Uncheck the 'read only' option
  1. run `clasp list` again. Issue should be gone

## Specifications

  - Node version (`node -v`): v11.2.0
  - Version (`clasp -v`): 1.6.3
  - OS (Mac/Linux/Windows): Windows 10 v1803

**Comment by grant** [comment]
OK. I'm not sure why `.clasprc.json` when writing the file. Maybe an issue here: https://github.com/grant/dotf/blob/master/index.js#L37
PRs welcome to `dotf`.

It seems like a Windows issue too.

**Comment by prprhyt** [comment]
> It seems like a Windows issue too.

I think too.  
chmod/chmodSync occurred to unexpected behavior in Windows.  
So, I suggest that we should modify dotf to prevent executing chmodSync when dotf is running on Windows.

See:
https://github.com/nodejs/node-v0.x-archive/issues/4812

**Comment by prprhyt** [comment]
> That looks like a very old issue in Node.

Oops. I'm sorry.

I found description about mode of fs.chmod() on Windows.

@grant 
Do you think it is related to this issue?

> Caveats: on Windows only the write permission can be changed, and the distinction among the permissions of group, owner or others is not implemented.

https://github.com/nodejs/node/blob/master/doc/api/fs.md#fschmodpath-mode-callback

**Comment by grant** [comment]
@prprhyt @bv-vd Looks related to Windows/the linked issue.
Can you make a PR to not `chmod/chmodSync` on Windows for `dotf`?

**Comment by grant** [comment]
@prprhyt I added `dotf@1.2` that includes the patch you wrote.
Can you try updating `clasp` with this version and see if the Windows issue is fixed?

**Comment by grant** [comment]
@bv-vd The fix should be applied in the `master` branch of this repo. If you see it still occurring there, please reopen this issue.
@prprhyt Created PRs to fix this issue.

**Comment by imthenachoman** [comment]
I don't know if I should open a new issue but I was getting a similar error when I had hidden the `.clasprc.json` file through Windows. 

    Error retrieving access token: Error: EPERM: operation not permitted, open 'C:\Users\nacho\.clasprc.json'

I had to un-hide the file for it to work. Not sure why `clasp` run from PowerShell would need the file to be un-hidden?

**Comment by PopGoesTheWza** [comment]
@imthenachoman Looks like a NodeJS limitation: https://github.com/nodejs/node/issues/14553
Not sure yet how to implement a fix

**Comment by imthenachoman** [comment]
@PopGoesTheWza Yeah. Very strange issue. I don't fully understand the technical reason but I assume it has something to do with how Microsoft did something. Oh well. Not a big deal.

**Comment by PopGoesTheWza** [comment]
I'd adventure a wild guess: Linux and Mac OS have similar POSIX compliant file systems which do not have an `hidden` attribute. Such attribute I only encounter on Microsoft OSes (DOS and Windows) and a few long since forgotten systems. In order to fully support Windows differences, one would need to either introduce in the NodeJS code base too much specific code, or leave up to apps and package developer to handle it.
https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory
