### ISSUE TITLE
clasp -v errors out with SyntaxError

### ISSUE THREAD

**Issue by oneness** [google/clasp#413]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> Ideally, after filing the issue, try to fix the issue with a PR!

## Expected Behavior
`clasp` command should work

## Actual Behavior
Fails with 
```
....google-auth-library/build/src/auth/googleauth.js:107
    getApplicationDefault(optionsOrCallback = {}, callback) {
                                            ^

SyntaxError: Unexpected token =

```

## Steps to Reproduce the Problem

  1.  Follow instruction on https://codelabs.developers.google.com/codelabs/clasp/#1 to install
  2. Run `clasp -v` or `clasp login`

## Specifications

  - Node version (v5.12.0):
  - Version (clasp -v errors out as above):
  - OS (Mac 10.14):

**Comment by oneness** [comment]
I found this only exists in node version v5.12.0.  So this needs to be updated to reflect that. https://codelabs.developers.google.com/codelabs/clasp/#1

**Comment by grant** [comment]
@oneness Thanks for the report. It looks like we actually need Node >= v6 that includes object destructuring. I've updated the README and codelab.
