### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by piotaixr** [google/clasp#415]
The contributing guide does not state if a particular code should be used for the clasp codebase.

Would it be pertinent to enforce one? (like prettier, which seems to be already integrated to all popular IDEs)

**Comment by grant** [comment]
The tslint is enforced in Travis tests. Maybe we could add an instruction to npm run lint in the README too.

**Comment by grant** [comment]
Thanks for the issue.
I've added `prettier` to the codebase.

If you know how to prevent this from occurring, LMK.
```ts
[
  {
    key: 'value'
  }
]
```

See https://github.com/google/clasp/commit/efd94f021ef1b58887f2d9de3fddcf49c491a5f0#diff-0430413d1b6fa9f0e832eb2c7dfd0a37R226.
