### ISSUE TITLE
`npm run docs` can't be executed 

### ISSUE THREAD

**Issue by takanakahiko** [google/clasp#419]
## Expected Behavior

In `docs/develop.md` it is written that run `npm run docs` to build the "How To" section.
But , `npm run docs` can't be executed . 

## Actual Behavior

```
error TS6053: File 'src/docs.ts' not found.
```

## Steps to Reproduce the Problem

  1. fork this repository.
  1. `npm i`
  1. `npm run docs`

## Specifications

  - Node version (`node -v`): v11.2.0
  - Version (`clasp -v`): 
  - OS (Mac/Linux/Windows): Mac

## Comment

`src/docs.ts` has been removed in 10baa86740c8254644cfe03b92a6ee4ea08f5a33 .
Are you planning to no longer use `npm run docs`? @grant 
If so, I will make a PR that includes document modifications and deletion unnecessary packages.

**Comment by grant** [comment]
@takanakahiko You can remove `npm run docs`.
It's easier to manually tweak the docs since machine generated docs aren't perfect.

**Comment by takanakahiko** [comment]
@grant OK, I'll make PR later.
