### ISSUE TITLE
clasp push warns if you have a different manifest locally

### ISSUE THREAD

**Issue by takanakahiko** [google/clasp#424]
## Expected Behavior

I want command line option of `clasp pull` that pulls `appsscript.json` only.

example : `clasp pull --setting-only`

Using this command after setting 

## Actual Behavior

There is a problem with the management method of `appsscript.json`.

If you run `clasp push` after setting something in the web GUI, the local `appsscript.json` is outdated.
Pushing old `appsscript.json` will unexpectedly change setting by web GUI .

## Steps to Reproduce the Problem

Example

  1. `clasp create`
  1. create `Code.js` in local
  1. `clasp push`
  1. Configure to publish to web by web GUI .
  1. `clasp push`

Web publishing is disabled.

## Specifications

  - Node version (`node -v`):  v11.2.0
  - Version (`clasp -v`): 4927ee4 
  - OS (Mac/Linux/Windows): Mac

What do you think about this proposal?

**Comment by takanakahiko** [comment]
See also: #176 #286 #391

**Comment by takanakahiko** [comment]
Thank you for your reply.

## Plan of `pulls only manifest`

command : `clasp pull --setting-only` or `clasp pull appsscript.json`

`clasp pull [filename]` is a nice idea!
I was concerned about becoming complicated by increasing options.

Disadvantage: We need to run `clasp pull appsscript.json` each time setting by web GUI.

## Plan of `warn when push`

command : `clasp push` warns if you have a different manifest locally.

I think that it is a good idea. Because users are not forced to do extra operations.

Check manifest using [Method: projects.getContent](https://developers.google.com/apps-script/api/reference/rest/v1/projects/getContent) before push, OK?

Disadvantage: Processing becomes heavy since it checks Remote's manifest each time running `clasp push`


Which do you think is a good idea?

**Comment by grant** [comment]
I think we should stop a user from pushing if it will override their manifest file. `prompt when push`:

1. clasp push
- clasp pulls to check manifest
- If manifest is different, use `inquirer` to ask the user if they want to use the remote manifest.
  - If yes, override the manifest.
- Push like normal

We can skip force pushing or diffing files as I think this would be rare.

**Comment by takanakahiko** [comment]
I agree with that plan.

What if you want to push a manifest without using `inquire` ? (ex: CI system)
How about skipping `inquirer` with the `-f` or `--force` option?

**Comment by takanakahiko** [comment]
Thanks! I will make a PR later.
