### ISSUE TITLE
Only `.prettierrc.js` is not ignored

### ISSUE THREAD

**Issue by macoshita** [google/clasp#430]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> Ideally, after filing the issue, try to fix the issue with a PR!

## Expected Behavior

I want to ignore everything and except src files.

```
**/**
!build/main.js
!appsscript.json
```

## Actual Behavior

Only `.prettierrc.js` is not ignored.

## Steps to Reproduce the Problem

  1. `clasp create`
  1. `echo 'module.exports={}' > .prettierrc.js`
  1. create .claspignore as above
  1. `clasp push`

```
$ clasp push
└─ .prettierrc.js
└─ appsscript.json
Pushed 2 files.
```

## Specifications

  - Node version (`node -v`): v10.13.0
  - Version (`clasp -v`): 1.6.3
  - OS (Mac/Linux/Windows): Mac

**Comment by takanakahiko** [comment]
Thanks for the report!
There was an error in my implementation.

I forgot to add a flag for checking dot files when matching.
https://github.com/isaacs/minimatch#dot

I will make a PR to fix it later!
