### ISSUE TITLE
`clasp status` ignores `.claspignore`

### ISSUE THREAD

**Issue by paxperscientiam** [google/clasp#439]
## Expected Behavior
Lists files to be pushed.

## Actual Behavior
Lists files to be pushed AND ignored files. 

## Steps to Reproduce the Problem

  1. Add patterns to `.claspignore`
  2. Execute `clasp status`
  3. See incorrect results.

## Specifications

  - Node version (`node -v`): v9.11.2
  - Version (`clasp -v`): 1.6.3
  - OS (Mac/Linux/Windows): 10.14.1

**Comment by johnnyasantoss** [comment]
I'm seeing the same behavior on `1.7.0`

**Comment by johnnyasantoss** [comment]
@grant Can this be pushed to a new version?
This also fixes `clasp push` for files that shouldn't be ignored.
