### ISSUE TITLE
Support official deployment procedures for updating a deployed version of Gmail Add-on

### ISSUE THREAD

**Issue by wulftone** [google/clasp#44]
On the script GUI, we can have multiple versions of a deployment, and specify which version applies to which deployment id: See https://developers.google.com/gmail/add-ons/how-tos/publish#publish_an_add-on.

`clasp` doesn't seem to support this yet.  Would love to have it!

**Comment by grant** [comment]
Can you be more specific with this request and follow the issue template?

`clasp redeploy <deploymentId> <version> <description>` doesn't update a deployed version?

**Comment by grant** [comment]
Not sure what the specific ask is here. Going to close this older issue.
Feel free to open a new one with more details of what `clasp` is missing.
