### ISSUE TITLE
npm install fails on Windows 10

### ISSUE THREAD

**Issue by libertybell95** [google/clasp#441]
## Expected Behavior
Successful package install of clasp from NPM

## Actual Behavior
Upon execution of `npm i @google/clasp -g` in Windows CMD, install runs for a few seconds then outputs: 
```
npm ERR! Unexpected end of JSON input while parsing near '...DzCwGtdVc/u4hFqJRaI0d'

npm ERR! A complete log of this run can be found in:
npm ERR!       AppData\Roaming\npm-cache\_logs\2018-12-07T18_06_25_632Z-debug.log
```

Debug log: [2018-12-07T18_06_25_632Z-debug.log](https://github.com/google/clasp/files/2658395/2018-12-07T18_06_25_632Z-debug.log)

Have attempted to run install with and without administrator permissions without success. Also attempted `npm i -g grpc @google/clasp --unsafe-perm` and received identical error message.

## Steps to Reproduce the Problem

  1. Execute `npm i @google/clasp -g` in Command Line

## Specifications

  - Node version (`node -v`): 10.14.1
  - Version (`clasp -v`): N/A
  - OS (Mac/Linux/Windows): Windows 10

**Comment by grant** [comment]
Perhaps try different versions:

```
npm i -g @google/clasp@1.6.0
# or
npm i -g @google/clasp@1.5.0
```

Maybe upgrade Node to 11.4.0?
Clear the npm cache like @kenchan0130 suggested?

**Comment by libertybell95** [comment]
**Resolved**

Steps Taken:
1. Uninstalled Node.JS and reinstalled with 11.4.0.
2. Performed regular 'npm i @google/clasp -g' with no success
3. Cleared and verified npm cache successfully
4. Ran npm install for clasp v1.6.0 successfully
