### ISSUE TITLE
`clasp clone` shouldn't rely on `.clasp.json`

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#452]
## Expected Behavior

`clasp clone 1Q3zCVgK53kEiacR0qvBYFr-A4d720UgZh3cdfDF2oFVJE5SgFiXO0AVZ`

`clasp` clones the project.

## Actual Behavior

```
🐷  clasp clone 1Q3zCVgK53kEiacR0qvBYFr-A4d720UgZh3cdfDF2oFVJE5SgFiXO0AVZ
(node:11110) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.clasp.json'
(node:11110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Cloned 2 files.

No .clasp.json settings found. `create` or `clone` a project first.
```

## Proposed solution:

Looks like the clone function uses `getProjectSettings` to determine the type of file it should clone, see here: https://github.com/google/clasp/blob/master/src/files.ts#L240-L243

I propose that if there are no `.clasp.json` file found, then it defaults to filetype of `js` (let user change to `ts` if they want.

**Comment by grant** [comment]
Ah yes, this is a big issue, let's fix this!

**Comment by campionfellin** [comment]
Note: it appears the `clasp create` is also broken, due to a similar error. Will try to find how `.clasp.json` file used to be created.
