### ISSUE TITLE
Cannot read property 'expiry_date' of undefined - v1.7.0

### ISSUE THREAD

**Issue by aandis** [google/clasp#457]
I upgraded to `1.7.0` from `1.5.3` today  with `sudo npm update -g @google/clasp`. Running any clasp command now throws the following error -

```
Error retrieving access token: TypeError: Cannot read property 'expiry_date' of undefined
```

**Comment by grant** [comment]
What's your Node version?
Can you fill out the issue template?

**Comment by gersonsosa** [comment]
This happened to me today but after logout and login again it worked

**Comment by fnlctrl** [comment]
Happened to me too. This is obviously a breaking change.

Pre-1.7 .clasprc.json:
```json
{
  "access_token": "****",
  "scope": "****",
  "token_type": "****",
  "expiry_date": 1545361708619,
  "refresh_token": "****"
}
```

1.7 .clasprc.json
```json
{
  "token": {
    "access_token": "****",
    "refresh_token": "****",
    "scope": "****",
    "token_type": "****",
    "expiry_date": 1545366408997
  },
  "oauth2ClientSettings": {
    "clientId": "****",
    "clientSecret": "****",
    "redirectUri": "****"
  },
  "isLocalCreds": false
}
```

**Comment by grant** [comment]
Yeah, at that point I broke the credential file to accommodate for login —creds easily.
I really should have bumped the major version at that point.
Will need to do that at some point. But yes, logout and login to fix.

**Comment by aandis** [comment]
@grant I'm still seeing https://github.com/google/clasp/issues/457#issuecomment-447238670

```
Node - v6.2.2
Clasp - 1.7.0
OS - Linux/Ubuntu 14.04.5 LTS
```

**Comment by grant** [comment]
I'm going to move on and close this issue.

Please login again to fix the problem.

See this comment for the reason why the problem exists if your curious:
https://github.com/google/clasp/issues/457#issuecomment-449252592
