### ISSUE TITLE
Notify user to logout, login after upgrading to version 1.7

### ISSUE THREAD

**Issue by paxperscientiam** [google/clasp#459]
## Expected Behavior
Can push without error after uprade.

## Actual Behavior
Mysterious error.
```
clasp push
Error retrieving access token: TypeError: Cannot read property 'expiry_date' of undefined
```

## Steps to Reproduce the Problem
  1. Update to 1.7 (from 1.6.3 in my case)
  2. From an existing project, `clasp push`

## Specifications

  - Node version (`node -v`): v9.11.2
  - Version (`clasp -v`): 1.6.3 -> 1.7
  - OS (Mac/Linux/Windows): macos 10.14.1

**Comment by PopGoesTheWza** [comment]
Indeed this error is very cryptic and confusing

**Comment by grant** [comment]
Yeah, sorry about that.
See: https://github.com/google/clasp/issues/457#issuecomment-449252592

**Comment by paxperscientiam** [comment]
Thanks @grant. I'll close this since that other comment covers same issue.
