### ISSUE TITLE
FR: test if PWD is descendent directory of project root

### ISSUE THREAD

**Issue by paxperscientiam** [google/clasp#460]
## Expected Behavior
clasp tests if pwd is child or grandchild directory of project root before attempting to push.

## Actual Behavior
When pwd is descendent of project root, clasp fails because it does not find `appsscript.json`.
```
$ clasp push
ENOENT: no such file or directory, open 'appsscript.json'
```

## Steps to Reproduce the Problem

  1. Go to descendent of project root.
  2. Attempt push.

## Specifications

  - Node version (`node -v`): v9.11.2 
  - Version (`clasp -v`): 1.7
  - OS (Mac/Linux/Windows): macos 10.14.1

**Comment by paxperscientiam** [comment]
It seems this is address by `ts2gas` version 1.5.2 per @grant  https://github.com/grant/ts2gas/issues/25#issuecomment-456178833

**Comment by grant** [comment]
Re-open if this is still an issue.
Thanks @paxperscientiam.
