### ISSUE TITLE
Suppress "Manifest file has been updated. Do you want to push and overwrite?" message when pushing

### ISSUE THREAD

**Issue by fnlctrl** [google/clasp#468]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
Some way to suppress this message, tried `clasp push -y`, no luck 

## Actual Behavior
A message saying `Manifest file has been updated. Do you want to push and overwrite?`

## Steps to Reproduce the Problem

1. make some changes to local appscript.json
2. clasp push

We're currently using a separate GAS project for development, with a build script that puts compiled time into `appscript.json` so we know it's up-to-date when debugging, something like.
```js
{
  gmail: {
    name: isProduction ? 'Foo' : `Foo (Dev-${compileTime})`
  }
}
```
This message is annoying as it requires you to wait for the webpack build to finish (wepback -p && clasp push), and then extra two keystrokes (y, enter) to push code.

## Specifications
- Version (`clasp -v`): 1.7.0

**Comment by grant** [comment]
I think
Clasp push -f
Should work

**Comment by fnlctrl** [comment]
`-f` worked, thanks!
I should have checked the docs again after the update.

**Comment by claudiomf1** [comment]
The problem is that if you use force, it keeps sending the file to google.
how would he not send this file to google?
because every time he sends it to google he needs to redeploy the project again.
I already added the appsscript to claspignore but it doesn't solve it. it always detects it anyway

How to solve this???

**Comment by Vinivrd** [comment]
Hello everyone, I solved this problem by changing my appsscript.json
before:
{
  "timeZone": "America/Sao_Paulo",
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8"
}
after:
{
  "timeZone": "America/Sao_Paulo",
  "dependencies": {},
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "webapp": {
    "executeAs": "USER_DEPLOYING",
    "access": "MYSELF"
  }
}

You just have to change your timezone and it works.
