### ISSUE TITLE
Allow manual override of tsconfig used by ts2gas

### ISSUE THREAD

**Issue by lugehorsam** [google/clasp#473]
It appears that clasp uses a hardcoded config object here to transpile its Typescript:
https://github.com/grant/ts2gas/blob/master/index.js#L24

This means I cannot use my own .tsconfig to get read by `clasp push`.

One good use case is concatenating all my files into a single Google Apps Script to avoid execution order issues (I know that can be specified separately) and variables going out of scope depending on their script. 

There are workarounds to this.

## Expected Behavior

Adding the following tsconfig to my project does not strip out comments in the uploaded .gs files:
```
{
	"compilerOptions": {
		"removeComments": true
	},
}

```
## Actual Behavior

Adding the above tsconfig to my project should strip out comments in the uploaded .gs files:

## Specifications

- Node version (`node -v`): v11.5.0
- Version (`clasp -v`): 1.7
- OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
Good issue.
Can you modify ts2gas to accept overridden params?

**Comment by PopGoesTheWza** [comment]
@grant ts2gas could accept a second parameter, a subset of the compilerOptions object (we do not want to expose every options to override.

I let you decide how this compilerOptions should be specified and managed by clasp.
Ideally it could be a dot file (.ts2gas.json comes to mind) set at the root of the project, possibly locally overridden in subfolder.

It likely requires changes in how sources files are collected and passed to ts2gas... which could be the opportunity to also implement a bundling/concatenate feature.

**Comment by grant** [comment]
I don't think we need a `.ts2gas.json`.
We should just use the default way developers specify `compilerOptions`, using the tsconfig.

For changing how source files are passed into ts2gas, it seems like a good opportunity to add a different option of an object full of all files rather than one file.

**Comment by PopGoesTheWza** [comment]
indeed, relying on .tsconfig is better design

**Comment by PopGoesTheWza** [comment]
About the bundling/concatenation, how would you see it?
What about  a `flag` which make all *.ts files inside a subfolder being bundled in a single sourceFile for ts2gas and output as on .js/gs named as the subdirectory?

**Comment by grant** [comment]
Let's not add a bundling feature right now.
The online AS editor is very fragile is unusable if there's ~10k lines of code. Other tools are better to bundle gas/ts than anything we could add.

> It likely requires changes in how sources files are collected and passed to ts2gas... 

If the compiler requires all source files rather than one source file at a time, let's pass an object with `fileName` to `fileSource` to `ts2gas`.

---

I don't know specifics of how to do this, but I can say what we shouldn't do from a design perspective.

**Comment by grant** [comment]
@lugehorsam 
> avoid execution order issues

FYI: There's `filePushOrder` specifically for this issue.
https://github.com/google/clasp#project-settings-file-claspjson

**Comment by PopGoesTheWza** [comment]
@grant given the adherence between *clasp* and *ts2gas*, I wonder if merging *ts2gas* inside *clasp* wouldn’t make more sense.

**Comment by grant** [comment]
I'm in favor of splitting clasp more (into smaller modules) rather than adding more code to the repo. It easier to manage issues and stable versions.
If I started clasp from scratch, I'd use `lerna` for this management.

You can also use `ts2gas` separate from `clasp` with webpack or your favorite tool if you'd like.

**Comment by PopGoesTheWza** [comment]
lerna sounds nice indeed.
Then I’ll try to think on how ts2gas should be changed in order to provide more than (string, compileOptions) => string function

**Comment by PopGoesTheWza** [comment]
@grant I submitted for comments a possible implementation under ts2gas.

**Comment by grant** [comment]
The last step is for clasp to read the `tsconfig.json` and pass it to the new `ts2gas@1.5`.

**Comment by PopGoesTheWza** [comment]
@grant one more radical approach could be to get rid of ts2gas and its transpileModule interface and switch to calling TypeScript compiler directly.
This should make the compiling and transpiling process more standard, relying on typescript standard dot and config files "transparently".

ref. https://dev.doctorevidence.com/how-to-write-a-typescript-transform-plugin-fc5308fdd943
