### ISSUE TITLE
improve error message of `clasp push` outside of project

### ISSUE THREAD

**Issue by wildeyes** [google/clasp#475]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
```
~/C/l/google-test-project ❯❯❯ clasp push
Error: It seems you're running outside of a project - there's no 'appsscript.json' in this directory.
```
## Actual Behavior
```
~/C/l/google-test-project ❯❯❯ clasp push
ENOENT: no such file or directory, open 'appsscript.json'
```

## Steps to Reproduce the Problem

1. run `clasp push` outside of project

## Specifications

- Node version (`node -v`): 11.2
- Version (`clasp -v`): 1.7.0
- OS (Mac/Linux/Windows):

**Comment by grant** [comment]
Seems like a good issue.

Ideally we call `readManifest` and catch the error there:
https://github.com/google/clasp/blob/master/src/manifest.ts#L20

**Comment by PopGoesTheWza** [comment]
@wildeyes @grant While testing this with latest npm release of clasp:
```
~/meteor-dev/importerTs$ clasp push

No .clasp.json settings found. `create` or `clone` a project first.
```
So I guess this issue has been resolved.

**Comment by grant** [comment]
Cool.
Thanks @PopGoesTheWza.
