### ISSUE TITLE
Structure code: use the SAME structure char '/' for both window and other OS

### ISSUE THREAD

**Issue by JeanRemiDelteil** [google/clasp#48]
## Expected Behavior
The structure separator char should always be the same ('/') not depending on the OS you are running CLASP.

On script.google.com:
- tests/slides.js
- tests/sheets.js

locally:
- tests/
  - slides.js
  - sheets.js

## Actual Behavior
On Windows:

On script.google.com:
- tests\slides.js
- tests\sheets.js

locally on window:
- tests/
  - slides.js
  - sheets.js

## Steps to Reproduce the Problem

  1. On a computer with windows
  2. push your clasp project to a script file
  3. open the project on script.google.com

## Specifications

  - OS (Windows)

**Comment by grant** [comment]
Thank you for the PR @JeanRemiDelteil!

**Comment by JeanRemiDelteil** [comment]
You are welcome !

Once it will be published to NPM we will be able to use CLASP in our GAS add-on projects !
This will save us so much time

**Comment by valen22br** [comment]
I have the same problem.
