### ISSUE TITLE
FR: Push & Deploy

### ISSUE THREAD

**Issue by Novack** [google/clasp#481]
I find myself continuosly needing to send this two commands one after the other. Im still not sure if my workflow understanding is wrong, but seems to me a combined command for this two actions would be great.

**Comment by grant** [comment]
I'd make a bash script to do these things. There are too many combinations of push, deploy, run, open, that would be useful, that it's best that clasp separates the actions.

**Comment by Novack** [comment]
Makes sense, thank you.
