### ISSUE TITLE
clasp login issue on remote server

### ISSUE THREAD

**Issue by zffocussss** [google/clasp#482]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

Login to scrit project
## Actual Behavior
login fail

when using clasp login,and I can see the url including "redirect_uri=http%3A%2F%2Flocalhost%3A42145",is it something wrong?

(node:1375) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/lib/node_modules/@google/clasp/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:276:13)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:188:13)
    at Pipe._handle.close (net.js:610:12)
(node:1375) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

## Steps to Reproduce the Problem

1.clasp login

## Specifications

- Node version (`node -v`):v11.6.0
- Version (`clasp -v`):1.7.0
- OS (Mac/Linux/Windows):Ubuntu 16.04.4

**Comment by grant** [comment]
Try `clasp login --no-localhost`

**Comment by zffocussss** [comment]
> Try `clasp login --no-localhost`

Hi grant,I use this ,but it ask me to paste a code which show in browser.What I want to know is if there is a way to login without by hand?

**Comment by zffocussss** [comment]
> > Try `clasp login --no-localhost`
> 
> Hi grant,I use this ,but it ask me to paste a code which show in browser.What I want to know is if there is a way to login without by hand?

Because I want to do this job in pipeline of a deployment.

**Comment by grant** [comment]
Good question.
Just `login` once, then copy your credentials (`~/.clasprc.json`) to the remote server.
The server will then use those credentials.

Please re-open the issue if this doesn't work and you have questions.
