### ISSUE TITLE
appsscript.json is ignored when `rootDir` is indicated at windows 10 git bash, powershell

### ISSUE THREAD

**Issue by mildc055ee** [google/clasp#487]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
at git bash & powershell
```
> clasp status
Not ignored files:
└─ ....
└─ src/appsscript.json
```
## Actual Behavior

```
> clasp status
Not ignored files:
└─ ....

Ignored files:
└─ src/appsscript.json
```
## Steps to Reproduce the Problem
1. set  `./src` at `rootDir`
``` 
{
        "scriptId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "rootDir": "./src"
}
```
2. at gitbash, or powershell, `clasp status`
3. then get actual behavior

## Specifications
at WSL (same node version, clasp version), `src/appsscript.json` is NOT ignored.

- Node version (`node -v`): v10.15.0
- Version (`clasp -v`): 1.7.0
- OS (Mac/Linux/Windows): windows 10

**Comment by johnnyasantoss** [comment]
Related to #439 which is fixed but not released. You can build this package locally using `npm run build-fresh` and it should work.

**Comment by mildc055ee** [comment]
I think that this might be caused by difference of windows and unix path, too. but then it's a little odd behavior that roodDir `src` is correctly set while `src/appsscript.json` is ignored.
sorry for my poor english

**Comment by johnnyasantoss** [comment]
Did you try to use the last version of this package by building it locally?

**Comment by grant** [comment]
Please re-open if the latest clasp doesn't fix this issue. Thanks!
