### ISSUE TITLE
TypeScript documentation on adding "node" types causes errors

### ISSUE THREAD

**Issue by JeanMertz** [google/clasp#490]
## Expected Behavior

When following the [Typescript tutorial/documentation](https://github.com/google/clasp/blob/61b2f41a454185d7fda59807f11af6402c0aba8a/docs/typescript.md), I expected things to work out of the box, but instead I ran into an issue.

## Actual Behavior

Pushing the code works as expected:

```
$ clasp push

└─ src/appsscript.json
└─ src/hello.ts
Pushed 2 files.
```

but compiling it using `typescript@2.9.2` fails:

```
$ ./node_modules/.bin/tsc

node_modules/@types/node/index.d.ts:228:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'console' must be of type 'console', but here has type 'Console'.

228 declare var console: Console;
```

Here is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "types": ["google-apps-script", "node"],
    "lib": ["esnext"],
    "target": "esnext",
    "module": "commonjs",
    "outDir": "dist",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,

    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true
  }
}
```

And here's my `package.json`:

```json
{
  "devDependencies": {
    "@types/google-apps-script": "^0.0.35",
    "@types/node": "^10.12.18",
    "typescript": "2.9.2"
  }
}
```

I managed to remove the error by _only_ using the `google-apps-script` types, but this goes counter to [the latest commit in the documentation](https://github.com/google/clasp/commit/c16a58a1622db3d8a2ff7353ffcb57d55907d485#diff-bf950c781cf511cc1467e5ada132f4fa), which added:
> `npm i -S @types/node # may be useful for types like console.log`

It looks like both node and google-apps-script add their own definitions for `console`, which makes this not work.

I'm not that familiar with JavaScript or TypeScript, so perhaps the solution is obvious (other than _not_ including the node types), but I haven't been able to solve it yet.

I realise that compiling the `ts` files isn't needed, as clasp does that for me before pushing, using `ts2gas`, but I need to get this working for proper editor support while working on the script.

## Specifications

- Node version (`node -v`): `v11.6.0`
- Version (`clasp -v`): `1.7.0`
- OS (Mac/Linux/Windows): macOS

**Comment by grant** [comment]
Yes, I think we should remove the recommendation to install Node types as `console` is duplicated.
I can try following the tutorial without that step at some point.
