### ISSUE TITLE
Clasp clone gives error of did you provide the correct scriptId?

### ISSUE THREAD

**Issue by alirezastack** [google/clasp#491]
## Expected Behavior
To clone a project

## Actual Behavior
`clasp clone` displays the below information:

```
% clasp clone                                                                        
? Clone which script?  (Use arrow keys)
❯ Untitled project     – https://script.google.com/d/MY_PROJECT_SCRIPT_ID/edit
```

I use arrow keys and select the only project which is in the list, then hit enter and get the below error:

`> Did you provide the correct scriptId?`

## Steps to Reproduce the Problem

1. clasp clone
2. select a project from the list and hit enter

## Specifications

- Node version (`node -v`): v10.6.0
- Version (`clasp -v`): 1.7.0
- OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
Hmm, I didn't get this error when trying. You probably have multiple Google accounts and are logged into clasp with an account that doesn't have access to that script. Maybe the script is shared with you but view-only?

Try logging out and logging in? Check which account owns that script?

```
? Clone which script? Clasprunpersonal     – https://script.google.com/d/15ImUCp
yi1Jsd8yF8Z6wey_7cw793CymWTLxOqwMka3P1CzE5hQun6qiC/edit
Cloned 3 files.
└─ appsscript.json
└─ Code.js
└─ emails.js
timmerman @ ~/Documents/trash/cloneright
❤ clasp -v
1.7.0
timmerman @ ~/Documents/trash/cloneright
❤ node -v
v11.6.0
```

**Comment by alirezastack** [comment]
@grant thanks for your response. List of projects are displayed by `clasp` itself, so cannot happen to see a project from another account. I created the project myself, so I cannot have a view-only project.

**Comment by grant** [comment]
Well, can you create a project and then clone it? Can I do anything to help?

Maybe your G Suite domain is restricted.

**Comment by grant** [comment]
I don't have enough details to recreate this issue.
Closing due to lack of other people having the issue.
