### ISSUE TITLE
Multiple project push 

### ISSUE THREAD

**Issue by ivanpestov** [google/clasp#50]
## Expected Behavior

Abiliy pushing a project to multiple destination over add anoder id in  '.clasp.json'
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - Version (`npm list | grep clasp`):
  - OS (Mac/Linux/Windows)

**Comment by grant** [comment]
Related to #38.

**Comment by grant** [comment]
For pushing to multiple project, you'll need to swap your `clasp.json` files.

Maybe have two settings: `.project1.clasp.json` and `.project2.clasp.json`.
Then `cp .project2.clasp.json .clasp.json`.

I won't support modifying dotfile settings inside `clasp` at the moment. Feel free these instructions to the README.
