### ISSUE TITLE
Refactor Commands code

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#501]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

The `commands.ts` file is getting quite large and could use some refactoring. This will speed up development and keep a higher quality codebase.

## Actual Behavior

All commands are in the single file.

## Proposed Solution

Move each command under `/src/commands/<command>.ts`

See previous discussion here: https://github.com/google/clasp/issues/134

**Comment by grant** [comment]
Unless @campionfellin refactors all the commands, I don't think this issue will be finished. 🙁

**Comment by grant** [comment]
Re-opened it.

**Comment by grant** [comment]
@campionfellin This suggestion turned out great. Done.

**Comment by campionfellin** [comment]
Great to hear! It's also  interesting to see that many of the commands we're having troubles with, like `clasp logs, push, run` don't have great coverage. Probably by flushing that out we can see what's going wrong.

<img width="469" alt="screen shot 2019-02-17 at 4 58 43 pm" src="https://user-images.githubusercontent.com/11984923/52922330-6f67b080-32d5-11e9-82f3-673cabd831f2.png">
