### ISSUE TITLE
Advanced Service TypeScript autocompletion.

### ISSUE THREAD

**Issue by darul75** [google/clasp#508]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

Get autocompletion for the Sheets Advanced Services

## Actual Behavior

No autocompletion available

## Steps to Reproduce the Problem

1. Go to your favorite IDE and create a new ts script
2. Type "Sheets." and activate completion
3. No options are displayed

## Specifications

- Latest typescript definition installed "@types/google-apps-script": "0.0.33"

**Comment by Cerlancism** [comment]
Do you mean `GoogleAppsScript.Spreadsheet.Sheet`, it works for for me? Its a interface you can only use on type assertions like declaring a variable type

**Comment by grant** [comment]
Yes, there are very limited types for Advanced Services.

**Comment by grant** [comment]
We should use @mtgto's generator: https://github.com/mtgto/dts-google-apps-script-advanced

**Comment by grant** [comment]
See this fix:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34212

**Comment by grant** [comment]
The fix was merged yesterday.

You may need to alias `Sheets` to `Sheets_v4` with these options but it should work fine.

- `const Sheets = Sheets_v4;`
- `appsscript.json`'s `enabledAdvancedServices[0]#userSymbol: 'Sheets_v4'`
