### ISSUE TITLE
Min node version required is 6.3

### ISSUE THREAD

**Issue by aandis** [google/clasp#510]
Reticketed from https://github.com/google/clasp/issues/457#issuecomment-447238670
## Expected Behavior
Login should work after [upgrade](https://github.com/google/clasp/issues/457) if you logout and log back in.

## Actual Behavior
```bash
$ clasp login
Warning: You seem to already be logged in *globally*. You have a ~/.clasprc.json

$ clasp logout
$ clasp login
Logging in globally...
Authorize clasp by visiting this url:
https://accounts.google.com/o/oauth2/v2/auth?...

Authorization successful.

/usr/local/lib/node_modules/@google/clasp/node_modules/dotf/index.js:39
          fs.chmodSync(fullpath, fs.constants.S_IRUSR | fs.constants.S_IWUSR);
                                             ^

TypeError: Cannot read property 'S_IRUSR' of undefined
    at jsonfile.writeFile (/usr/local/lib/node_modules/@google/clasp/node_modules/dotf/index.js:39:46)
    at /usr/local/lib/node_modules/@google/clasp/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/@google/clasp/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:117:15)
```

## Steps to Reproduce the Problem

This only occurs on node <= `6.2`. 
On login, you see the above error.

## Cause
On login, [dotf](https://github.com/google/clasp/blob/363e6d45954d9f2251f5d7c1d5ed1eb16b8d69cc/package.json#L46) tries to access [`fs.constants.S_IRUSR`](https://github.com/grant/dotf/blob/e46351a42a310844be2eabbd57c67d65e4089d51/index.js#L39) which is only [available](https://github.com/nodejs/node/issues/8044#issuecomment-247518992) in `6.3` and above. Whereas [README](https://github.com/google/clasp/blob/363e6d45954d9f2251f5d7c1d5ed1eb16b8d69cc/README.md#troubleshooting) states min node version required as `6.0.0`.

## Possible fixes
1. Bump the min version requirement in README.
1. Directly specify the [mode](https://nodejs.org/api/fs.html#fs_file_modes) as an octal value `0o600` in [dotf](https://github.com/grant/dotf/blob/e46351a42a310844be2eabbd57c67d65e4089d51/index.js#L39) instead of relying on the constant. From [docs](https://nodejs.org/api/fs.html#fs_file_modes)
> An easier method of constructing the mode is to use a sequence of three octal digits.

## Specifications

- Node version (`node -v`): `6.2.2`
- Version (`clasp -v`): `1.7.0`
- OS (Mac/Linux/Windows): `Linux/Ubuntu 14.04.5 LTS`

**Comment by grant** [comment]
OK. Do you want to upgrade the guide to state 6.3 is required?

**Comment by aandis** [comment]
@grant #511
