### ISSUE TITLE
Terminal error when calling clasp logs with invalid projectId

### ISSUE THREAD

**Issue by brianscodery** [google/clasp#518]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

When calling "clasp logs" with an invalid projectId, an error should be thrown, but the terminal should not lock down while perpetually trying to access logs that it can't find.

## Actual Behavior

When executing "clasp logs" with an invalid projectId,  an error code is thrown like the following:
```
(node:8314) UnhandledPromiseRejectionWarning: Error: field [name] has issue [Invalid project resource name]
    at createError (/usr/local/lib/node_modules/@google/clasp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/@google/clasp/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/usr/local/lib/node_modules/@google/clasp/node_modules/axios/lib/adapters/http.js:201:11)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are nothandled will terminate the Node.js process with a non-zero exit code.
```

**but then the terminal continues to be locked on "Grabbing logs..."**

## Steps to Reproduce the Problem

1. Provide an invalid projectId string (for example, with a leading space)
2. execute "clasp logs"

## Specifications

- Node version (`node -v`): v10.15.1
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Mac

**Comment by campionfellin** [comment]
Thanks for the report! I can take a look at this.

**Comment by campionfellin** [comment]
Ok, I've looked into this, and see a handful of errors. 

`UnhandledPromiseRejectionWarning: Error: Project does not exist: project-id-396147393262364424`
`UnhandledPromiseRejectionWarning: Error: The caller does not have permission`
`UnhandledPromiseRejectionWarning: Error: field [name] has issue [Invalid project resource name]`

The place this is failing is here:

https://github.com/google/clasp/blob/master/src/commands.ts#L450-L456

```
const logs = await logger.entries.list({
  requestBody: {
    resourceNames: [`projects/${projectId}`],
    filter,
    orderBy: 'timestamp desc',
  },
});
```

We can wrap this with a `try/catch` and additionally do some validation on `projectId` on our side.

I'm going to tag this as a `good first issue` and allow someone else to fix it.

**Comment by caputchinefrobles** [comment]
Hi. Thanks for the fix. Do you have any idea when the next release with the fix will be available? I'm having such a hard time without `clasp logs`. 

Thank's again.
