### ISSUE TITLE
clasp push —watch

### ISSUE THREAD

**Issue by grant** [google/clasp#52]
Add an option to watch local file changes and clasp push on file change.

```sh
clasp push —-watch
```

Use: https://www.npmjs.com/package/node-watch
Something like:

```ts
const watch = require('node-watch');
getProjectSettings().then(({ scriptId, rootDir }: ProjectSettings) => {
  watch(rootDir, { recursive: true }, (e, name) => {
    console.log(`${name} changed. Pushing...`);
    // Push...
    console.log('Pushed');
  });
}
```

**Comment by DimuDesigns** [comment]
Hopefully this will address an issue I came across. 

When a file is renamed locally and then pushed the order of the files in the project changes in the App Script Editor, with the renamed file re-positioned at the bottom of the file menu on the left. I suspect clasp assumes that the file was deleted and considers the renamed file as a new file.

This can have adverse effects when code execution is dependent on the order of the files in the Apps Script editor.

Now I take care to rename the files first in the Apps Script editor and then follow up with a pull. But that feels somewhat clunky. Hopefully you can address this moving forward.

**Comment by grant** [comment]
Renaming files is an extremely difficult use case for clasp, I don't know a good way to solve it. Right now we treat renamed files as new files.

Ideally, the 2 versions of the script are always in sync with `--watch`.

**Comment by DimuDesigns** [comment]
Adding an explicit command to `clasp` might be the way to go; kinda like what git does with its [`git mv`](https://git-scm.com/docs/git-mv) command.

**Comment by grant** [comment]
Let's at least publish this to `npm` before closing for good.

**Comment by grant** [comment]
npm was updated yesterday with this change. Install the lastest clasp to get this feature.
Closing!
