### ISSUE TITLE
Ignore typescript export and export default

### ISSUE THREAD

**Issue by angrykoala** [google/clasp#521]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

According to [docs](https://github.com/google/clasp/blob/master/docs/typescript.md) typescript's export should are ignored (like imports), however, they are transpiled into variables inside exports object.

Because ts imports are commented after transpile, appscript can't find the exported variables as these are no longer in the global scope. it would make more sense to simply ignore or comment export keywords. This renders my appscript code unusable if I have the export keyword in typescript

I'm not sure if there is a workaround or a way to make the appscript works without relying on manually accessing the "exports" variable in typescript.
Related to #263 

## Expected Behavior

```ts
export const foo="baar";
```

transpiled into

```js
var foo="baar";
```

## Actual Behavior

```ts
export const foo="baar";
```
transpiled into

```js
exports.foo="baar";
```

## Steps to Reproduce the Problem

1. use export
1. Transpile and check transpiled code

## Specifications

- Node version (`node -v`): 10.15.0
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Linux

**Comment by erickoledadevrel** [comment]
This appears to be an issue with the module [ts2gas](https://github.com/grant/ts2gas), which clasp depends on. Please file an issue there instead.
