### ISSUE TITLE
"clasp run" doesn't run for functions containing Apps Script triggers

### ISSUE THREAD

**Issue by sahilsk** [google/clasp#522]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

I"m not able to execute "clasp run" command if function is using `ScriptApp` class. But from UI(script editor) it works.

## Expected Behavior
- should execution function

## Actual Behavior
error

```
Script has attempted to perform an action that is not allowed when invoked through the Google Apps Script Execution API.
    at registerTriggers(g-forms/form1:88)
    at createOrUpdateForm(g-forms/form1:41)
```
registerTrigger Function definition

``` js
function registerTriggers(form){
  //create onFormSubmit Trigger  
  ScriptApp.newTrigger('onSubmit')
  .forForm(form)
  .onFormSubmit()
  .create();  // Error line: 88
}
```

appsscript.json file
```json
{
  "timeZone": "Asia/Kolkata",
  "dependencies": {},
  "executionApi": {
    "access": "ANYONE"
  },
  "exceptionLogging": "STACKDRIVER",
  "oauthScopes": [
    "https://www.googleapis.com/auth/forms",
    "https://www.googleapis.com/auth/script.external_request",
    "https://www.googleapis.com/auth/script.scriptapp",
    "https://www.googleapis.com/auth/script.send_mail",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/script.webapp.deploy",
    "https://www.googleapis.com/auth/script.deployments",
    "https://www.googleapis.com/auth/script.projects",
    "https://www.googleapis.com/auth/service.management",
    "https://www.googleapis.com/auth/logging.read",
    "https://www.googleapis.com/auth/cloud-platform"
  ]
}
```

## Steps to Reproduce the Problem

1. `clasp run 'createOrUpdateForm'`
1.

## Specifications

- Node version (`node -v`):  v10.10.0
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): windows (powershell)

**Comment by grant** [comment]
Triggers aren't allowed by the API:
https://developers.google.com/apps-script/api/how-tos/execute#limitations

**Comment by sahilsk** [comment]
Yeah, i came across similar issue: https://github.com/google/clasp/issues/335

That's very disappointing. I wanted to have a complete Ci/Cd setup for 1000s forms we need to create and maintain. Creating trigger for reach of them by logging in the script editor and executing the function gonna be very painful. :(

Any suggestion?

**Comment by grant** [comment]
Well, the form submits to a sheet.
Maybe check all the sheets every so often with some Apps Script?
