### ISSUE TITLE
`found 10 vulnerabilities` in `npm i`

### ISSUE THREAD

**Issue by takanakahiko** [google/clasp#529]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

vulnerabilities not found

## Actual Behavior

If run `npm i`, the following message will be displayed.

```
added 700 packages from 831 contributors and audited 2921 packages in 6.358s
found 10 vulnerabilities (9 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

details : 
![image](https://user-images.githubusercontent.com/10114717/52792716-6bf2e000-30af-11e9-9fdc-893fc1f334b7.png)

## Steps to Reproduce the Problem

1. clone this repository `git clone git@github.com:google/clasp.git`
1. `cd clasp`
1. `npm i`

## Specifications

- Node version (`node -v`): v11.9.0
- Version (`clasp -v`): https://github.com/google/clasp/tree/b6a57db9a829284e91ea97adb01656d031b5e32b
- OS (Mac/Linux/Windows): Mac

**Comment by takanakahiko** [comment]
There are two proposals. If OK, I'll create PR.

 - Update the dependency package version
 - Use `david-dm.org` to monitor the status of dependent packages

To use `david-dm.org` just set a badge on the README like https://github.com/takanakahiko/sao-clasp (my repository).

**Comment by erickoledadevrel** [comment]
@takanakahiko - That plan sounds good to me.

**Comment by grant** [comment]
david-dm sounds good. For example, the [Node client](https://github.com/googleapis/google-api-nodejs-client) uses this.
