### ISSUE TITLE
Claspignore does not work with directories 

### ISSUE THREAD

**Issue by krank** [google/clasp#551]
## Expected Behavior
Adding `**/foldername/**` to claspignore should make clasp status / clasp push ignore that folder and its files.

## Actual Behavior
It does not.

## Steps to Reproduce the Problem

1. Create new GAS project
2. Clone it using clasp clone
3. Add a folder named "test"
4. Add a file inside that folder, named "ignoreme.html"
5. Add the following code to .claspignore:
`**/test/**`
6. Run clasp status or clasp push
7. Result is: test/ignoreme.html is still in the "Not ignored files" pile

I have tried all the combinations of asterisks and forward/back slashes I can think of – I've tried writing out the literal file name (both as "ignoreme.html" and "test/ignoreme.html" and "test\ignoreme.html" and "**test**/ignoreme.html"... et cetera.

I have as of yet found no way to get clasp to ignore a file inside a directory, much less all files inside a specific directory.

It is completely possible I am missing something here. I have read through the various issues that apply to the claspignore; none of the ones I've found seem to fit. I have confirmed this problem on separate accounts, separate machines, separate projects (including one created for the sole purpose of testing this). It might even just be a case of the documentation not being updated.

## Specifications

- Node version (`node -v`): v11.1.0
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Windows 10 Pro 1809

**Comment by grant** [comment]
Yeah, sorry, ignore doesn't work properly.
I'm working on changing the way `push` works to fix this.

I believe there are other threads to provide workarounds in the meantime.
Thanks for your patience.

**Comment by erickoledadevrel** [comment]
This appears to be the same issue as #67. Closing this issue, please follow that one instead.
