### ISSUE TITLE
JSDoc Information Between Libraries

### ISSUE THREAD

**Issue by johnpvitale** [google/clasp#557]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

My apologies if this is not the right place for this discussion/question. I have an Apps Script project that is referencing an Apps Script library that I have created. Is it possible to get JS Doc/Type information from the library to appear in VS Code when working on the project?

**Comment by grant** [comment]
It is not possible.
I personally do not recommend using the AS library system.
Rather, just copy/paste the files in your project.

I'm closing this issue, but you can still ask questions. You may want to use StackOverflow for other questions.
