### ISSUE TITLE
Missing clasp support for People API

### ISSUE THREAD

**Issue by a-bormark** [google/clasp#559]
## Expected Behavior
People API can be enabled via the web UI. The API should be on when adding it to `appsscript.json` like this
`...
"dependencies": {
    "enabledAdvancedServices": [      {
        "userSymbol": "People",
        "serviceId": "people",
        "version": "v1"
      }
    ]
  }
...`

## Actual Behavior
After `clasp push` PEOPLE API is switched off. Looks like this happens because the `people` constant is not added to the `PUBLIC_ADVANCED_SERVICES` (https://github.com/google/clasp/blob/f00bbbf019befd79e5d82790c5647bdfb82c534c/src/apis.ts#L38)

## Steps to Reproduce the Problem

1. In appscript.json add a snippet from above 
2. `clasp push`
3. In project's web UI -> Resources -> Advanced Google services... 
4. People API is OFF

## Specifications

- Node version (`node -v`): v10.14.2
- Version (`clasp -v`): 1.6.3
- OS (Mac/Linux/Windows): Windows

**Comment by grant** [comment]
Thanks for the report @aleks-b.
Feel free to add the JSON to fix the issue.

**Comment by tawAsh1** [comment]
Hi.
I think `"serviceId": "people"` is maybe wrong.
serviceId should be `"peopleapi"`. not `"people" `.
