### ISSUE TITLE
'console' produces typescript error: "Cannot find name 'console'.ts(2304)"

### ISSUE THREAD

**Issue by GitTom** [google/clasp#566]
## Expected Behavior

Using 'console' should not produce an error.  It is useful for logging to stackdriver.

## Actual Behavior

Typescript marks all occurances of 'console' as an error, specifically "Cannot find name 'console'.ts(2304)".

## Steps to Reproduce the Problem

1.  Create a clasp/typescript project as per the instructions given in this repo's readme.
1.  Setup dev environment with components and versions listed below - I believe these are all pretty standard for clasp.

## Specifications

- Node version (`node -v`):  8.14
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Windows 10
- Typescript: 2.92

## package.json

```
  "devDependencies": {
    "@types/google-apps-script": "0.0.38",
    "tslint": "^5.13.1",
    "typescript": "^2.9.2"
  },
```
## tsconfig.json

```
  // Got this from a random example in 'clasp' discussion.
  "compilerOptions": {
    "types": [ "google-apps-script" ],
    "lib": ["esnext"],
    "target": "esnext",
    "module": "commonjs",
    "outDir": "dist",
    "strict": true
```
## Discussion

The clasp TS [instructions here](https://github.com/google/clasp/blob/61b2f41a454185d7fda59807f11af6402c0aba8a/docs/typescript.md#prerequisites) suggest using the node types to overcome this problem.  

But, [this issue/comment](https://github.com/google/clasp/issues/490#issuecomment-454112910) suggests that console actually is included in @types/google-apps-script so node types should not be included.  This makes sense to me - I don't want to include node types since node API's are not supported - and, based on [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script.base.d.ts#L308), it looks to me like 'console' is in fact included in 'google-apps-script' types. 

So maybe I'm just doing something wrong - I'm new to TS.

**Comment by grant** [comment]
This DT PR should fix `console`:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34042

We need to upgrade the guides to make sure we do not use `@types/node` anywhere.

**Comment by GitTom** [comment]
Excellent.  Thanks.
