### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by motin** [google/clasp#567]
Found this: https://github.com/google/clasp/blob/46576af8094bbe115bc856117beb50c7b2b685ca/src/commands/login.ts#L56

you're -> your

Should I open a PR for this single typo, or maybe someone will check through the strings and docs and fix several potential grammatical nits in one sweep?

**Comment by takanakahiko** [comment]
@motin 
@grant does not want PR that include multiple problems.
So, I think that it will be welcomed for you to create a PR to resolve typos.
