### ISSUE TITLE
Multi-line import statements creates invalid Apps Script

### ISSUE THREAD

**Issue by byerun** [google/clasp#568]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
Multi-line typescript import statements translated correctly

## Actual Behavior
The translated Apps Script code is invalid

## Steps to Reproduce the Problem

1. Create a multi-line typscript import statement such as
~~~~
import {
  FinancialTransactionFromSpreadsheet,
  SpreadSheetDef
} from "./financial.transaction.from.spreadsheet";
~~~~
2. Have clasp push to remote project

The translated code will have a "\n" embedded along with invalid lines:
~~~~ 
//import {
\n  FinancialTransactionFromSpreadsheet,
  SpreadSheetDef
} from "./financial.transaction.from.spreadsheet";
~~~~ 

Attempting to run the code will produce the error message
Illegal character.

## Specifications

- Node version (`node -v`): 11.8.0
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Windows

**Comment by takanakahiko** [comment]
@byerun This is a problem of `ts2gas` .
Could you make an Issue in `ts2gas` repository ?

https://github.com/grant/ts2gas

**Comment by byerun** [comment]
Created [ts2gas issue](https://github.com/grant/ts2gas/issues/29)
