### ISSUE TITLE
Switch from `commander` to `inquirer` 

### ISSUE THREAD

**Issue by grant** [google/clasp#57]
Give autocompletion for `clasp commands.
- List commands `clasp <tab>`
- Give options when choosing environments. Like [select shell](https://www.npmjs.com/package/select-shell) or [inquirer](https://www.npmjs.com/package/inquirer).

[Vorpal](https://github.com/dthree/vorpal#introduction) seems to be based on `commander` and provides these features.

**Comment by grant** [comment]
Also check out https://github.com/sindresorhus/fkill-cli
https://www.npmjs.com/package/meow

**Comment by grant** [comment]
Example prompt:
```js
/**
 * List prompt example
 */

'use strict';
var inquirer = require('inquirer');
var _ = require('lodash');
var fuzzy = require('fuzzy');
var Promise = require('promise');

inquirer.registerPrompt('autocomplete', require('./index'));

var states = [
  'Alabama',
  'Alaska',
  'American Samoa',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District Of Columbia',
  'Federated States Of Micronesia',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Marshall Islands',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Northern Mariana Islands',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Palau',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virgin Islands',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
];

var foods = [
  'Apple',
  'Orange',
  'Banana',
  'Kiwi',
  'Lichi',
  'Grapefruit',
];

function searchStates(answers, input) {
  input = input || '';
  return new Promise(function(resolve) {
    var fuzzyResult = fuzzy.filter(input, states);
    resolve(fuzzyResult.map(function(el) {
      return el.original;
    }));
  });
}


function searchFood(answers, input) {
  input = input || '';
  return new Promise(function(resolve) {
    var fuzzyResult = fuzzy.filter(input, foods);
    resolve(fuzzyResult.map(function(el) {
      return el.original;
    }));
  });
}

inquirer.prompt([{
  type: 'autocomplete',
  name: 'fruit',
  // suggestOnly: true,
  message: 'What is your favorite fruit?',
  source: searchFood,
  pageSize: 4,
  validate: function(val) {
    return val
      ? true
      : 'Type something!';
  }
}, {
  type: 'autocomplete',
  name: 'state',
  message: 'Select a state to travel from',
  source: searchStates
}]).then(function(answers) {
  console.log(JSON.stringify(answers, null, 2));
});
```

**Comment by grant** [comment]
So I've look at this for a bit today. There seems to not be an ideal solution that fits for clasp.

The issues are multifold.
- I'd expect `clasp` to be executed from a bash script as well as a user.
- It seems tab autocompletion is not possible without bash rc modification (which I don't want to do).

## Command Prompt Options

**Inquirer**: Too basic. Can't take specific commands, treats everything as global.
**Vorpal**: Seems like the best choice.
**Commander**: Wraps inquirer with some state (allows subcommands). But no interactive selection
**yargs**: Too simple. Able to parse args but has no context.

Here's a good tutorial of combining commander and inquirer: https://scotch.io/tutorials/build-an-interactive-command-line-application-with-nodejs

## Commands

I think `clasp@2` should use commander and inquirer in this combination to provide an easy, simple experience for Apps Script developers.

```sh
# Commander
clasp # If there's no clasp project, displays help. If there's a clasp project, watch.
clasp login
clasp logout
clasp pull
clasp push [--watch]
clasp open
clasp deployments
clasp versions
clasp list
clasp logs [--json] [--open]

# Inquirer enhancement (leave off the arg and it'll prompt you)
clasp create  [scriptTitle] [scriptParentId] – These can be prompted by the user
clasp clone <scriptId> – clasp list the scriptId.
clasp deploy [version] [description] - clasp deploy would prompt the user
clasp redeploy ... - clasp redeploy would prompt the user
clasp version - clasp version would prompt the user
```

## Summary

I think a combination of `commander` (for base command structure) and `inquirer` (for extra selection features) should be the technology decision for powering the clasp CLI.

**Comment by grant** [comment]
Inquirer is complete for `create` and `clone`.
It's needed for `deploy`, `redeploy`, and `version`.

**Comment by grant** [comment]
Also see:
https://cloud.google.com/sdk/docs/interactive-gcloud

https://github.com/dthree/vorpal/wiki/Docs-%7C-Autocomplete
https://www.npmjs.com/package/prompt-autocompletion

**Comment by takanakahiko** [comment]
I am going to try this!
I will make PR later.

**Comment by takanakahiko** [comment]
Using inquire.js makes automatic deployment more difficult. (Example: CircleCI)
What do you think?

**Comment by takanakahiko** [comment]
Do we need to migrate other functions?

**Comment by grant** [comment]
@takanakahiko It would be nice if `clasp create` was fixed to prompt the user of which type of add-on to create if `--type` isn't specified.

The 2.0 interface is described here:
https://github.com/google/clasp#create

**Comment by grant** [comment]
I may have to revisit this and use the up and rising CLI framework `oclif`:
https://github.com/oclif/oclif
