### ISSUE TITLE
How to work with existing bound script?

### ISSUE THREAD

**Issue by yang** [google/clasp#573]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
`clasp clone EXISTING_SCRIPT_ID` works, where script ID is the ID of an existing bound script not created with `clasp clone`.

## Actual Behavior
```
> Did you provide the correct scriptId?
```

## Steps to Reproduce the Problem

1. Create a bound script in a Google Sheet by going to Tools > Script Editor, saving.
2. `clasp clone...`

## Specifications

- Node version (`node -v`): 10.15.1
- Version (`clasp -v`): 1.7.0
- OS (Mac/Linux/Windows): Mac

## Additional Info
I think this has to do perhaps with the permissions that clasp requests, which is (for Google Drive):

- View and manage Google Drive files and folders that you have opened or created with this app
- View metadata for files in your Google Drive

However, since this script project wasn't created with clasp, it's not accessible to it, perhaps. Yet I don't know how to grant access.

**Comment by grant** [comment]
You're probably logged in with an account that can't see that script.
Try to log out and log in again.

**Comment by yang** [comment]
I tried but no luck, also upgraded clasp:

```
$ clasp -v
2.0.1

$ clasp login
Logging in globally...
🔑 Authorize clasp by visiting this url:
XXX

Authorization successful.

Default credentials saved to: ~/.clasprc.json (/Users/yang/.clasprc.json).

$ clasp clone XXX
Could not find script.
Did you provide the correct scriptId?
Are you logged in to the correct account with the script?
```

**Comment by tehhowch** [comment]
Did you pass the actual script id, found in the Project Properties? Or did you get the "ID" from the URL (as one might do with other Gsuite file types)?

**Comment by yang** [comment]
@tehhowch That was indeed the issue, thank you.

**Comment by MatthewGitter** [comment]
As of 11/21/24 clasp can list bound projects along with standalone projects, and it can clone and pull bound projects as it can standalone projects. However, the proper permissions scopes must be selected during clasp login in the authentication flow in the browser on the page introducing the list with "Select what clasp – The Apps Script CLI can access":

clasp list requires "See information about your Google Drive files. [✓]".
clasp clone <script ID> (where you copy <script ID> from the GAS project's Project Settings page) as well as clasp pull and clasp push require "Create and update Google Apps Script projects. [✓]" (also ensure that the local dir does not contain a .clasp.json file already, as the clone operation needs to overwrite it but will be blocked by an existing one).
clasp push additionally requires activating Google Apps Script API at https://script.google.com/u/5/home/usersettings , which can take a few minutes to take effect for clasp to use it.
