### ISSUE TITLE
clasp create arguments are ignored

### ISSUE THREAD

**Issue by yang** [google/clasp#575]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
`clasp create` doesn't ignore its arguments.

## Actual Behavior
```
$ clasp login
Logging in globally...
🔑 Authorize clasp by visiting this url:
XXX

Authorization successful.

Default credentials saved to: ~/.clasprc.json (/Users/yang/.clasprc.json).

$ clasp create --title asdf --parentId XXX
? Clone which script? sheets
Created new Google Sheet: https://drive.google.com/open?id=1lldnEy_J8SO36QCj8qcokqzvDIUSiSCCqXeyVdU_dxU
Created new Google Sheets Add-on script: https://script.google.com/d/1hytISkhQabZ_UKcNaLxCg6akLYkiMzXpc1aigfpfHVtDbmr6ELhFYrHa/edit
Cloned 1 file.
└─ appsscript.json
```

## Steps to Reproduce the Problem

1. See above

## Specifications

- Node version (`node -v`): 10.15.1
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
This will be fixed when clasp is published next.

**Comment by grant** [comment]
Can you upgrade clasp try again @yang?

**Comment by yang** [comment]
It works now, thanks!
