### ISSUE TITLE
Create instructions for online IDE

### ISSUE THREAD

**Issue by grant** [google/clasp#579]
## Expected Behavior

Create a tutorial/script for using an online IDE for Apps Script:
https://ide.coder.com/

### Script Features
- Install Node: `curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -`
- VS Code Settings (See below schemastore)
- Install types for autocompletion (`npm i @types/google-apps-script`)
- Install clasp: `npm i -g @google/clasp`
- Prompt to login: `clasp login --no-localhost`
- Prompt to create or push `clasp create` / `clasp push --watch`

### VS Code `settings.json`:

Location: `/root/.local/share/code-server/User/settings.json`

```json
{
    "git.enableSmartCommit": true,
    "json.schemas": [
        {
            "fileMatch": [
                "appsscript.json"
            ],
            "url": "http://json.schemastore.org/appsscript"
        },
        {
            "fileMatch": [
                ".clasp.json"
            ],
            "url": "http://json.schemastore.org/clasp"
        }
    ]
}
```

**Comment by grant** [comment]
Maybe create a shell script that setups the IDE from the base Dockerfile?

**Comment by takanakahiko** [comment]
I think gitpod is appropriate for this case.
We can open the repository in Online IDE with one click using gitpod.

Create a PR to add gitpod settings.
