### ISSUE TITLE
.claspignore not working at all

### ISSUE THREAD

**Issue by Edge-Developer** [google/clasp#587]
## Expected Behavior

The text below written within `.claspignore` is supposed to ignore everything else and select sample.js for push

```
**/**
!sample.js
```

## Actual Behavior
But Alas, after running `clasp status` on the terminal

it did not ignore the rest:
<figure>
<img width="344" alt="'clasp status' on terminal" src="https://user-images.githubusercontent.com/22748496/55210437-b6579880-51e7-11e9-93d6-0e610babd892.png">
  <figcaption>"clasp status" on terminal</figcaption>
</figure>
<br><br>
Still did not ignore when i pushed
<figure>
<img width="318" alt="Screen Shot 2019-03-29 at 6 01 52 AM" src="https://user-images.githubusercontent.com/22748496/55210556-43025680-51e8-11e9-8002-7fc2e38df9fc.png">
  <figcaption>"clasp push" on terminal</figcaption>
</figure>

## Steps to Reproduce the Problem

Already given above

## Specifications
- Node version: 10.15.3
- Clasp Version: 2.1.0
- OS: Mac (Mojave)

**Comment by grant** [comment]
Thanks for the report. Probably related to #58.

**Comment by PopGoesTheWza** [comment]
This also needs to be validated after PR #620

**Comment by PopGoesTheWza** [comment]
@Edge-Developer  can you try with clasp 2.2.0 if the issue still occurs?
