### ISSUE TITLE
(Minor) deprecated `opn` packages should be replace with its successor `open`

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#603]
## Steps to Reproduce the Problem

1. check clasp's packages.json for `opn` depenecy
1. check [`opn` npm page](https://www.npmjs.com/package/opn) for deprecation warning
1. check [`open` npm page](https://www.npmjs.com/package/open) to verify same author/same api

## Specifications

- Node version (`node -v`): n.a.
- Version (`clasp -v`): @latest
- OS (Mac/Linux/Windows): n.a.

**Comment by grant** [comment]
OK. Sounds like an easy fix.
