### ISSUE TITLE
(Minor) npm package `readline` wrongly added in place of node `readline` module

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#604]
## Steps to Reproduce the Problem

1. check clasp's packages.json for `readline` depenecy
1. check [`readline` npm page](https://www.npmjs.com/package/readline) for renaming warning
1. check [`linebyline` npm page](https://www.npmjs.com/package/linebyline) to verify same author/same api

## Specifications

- Node version (`node -v`): n.a.
- Version (`clasp -v`): @latest
- OS (Mac/Linux/Windows): n.a.

**Comment by PopGoesTheWza** [comment]
After closer inspection, the npm package `readline` is never effectively `require`d and the standard node module `readline` is in fact what is being used. Thus, droping the npm package is the answer.

**Comment by grant** [comment]
Fixed with #606.
