### ISSUE TITLE
(Minor) Outdated test suite packages

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#607]
`chai`, `mocha` and `nyc` are outdated and npm issues high vulnerability risk.

Simply bumping all those 3 packages to their latest version breaks the `npm run test` command. So having them up to date might require refactoring of the test suite.

## Expected Behavior

- no vulnerability report upon `npm install`

## Steps to Reproduce the Problem

1. `npm install` -> `found 10 vulnerabilities (9 moderate, 1 high)`
1.

## Specifications

- Node version (`node -v`): 10 --lts
- Version (`clasp -v`): latest
- OS (Mac/Linux/Windows): Mac OS (latest)

**Comment by PopGoesTheWza** [comment]
I was able to pinpoint the issue to the `mocha` package as the root cause of breaking `npm run test` on upgrade

**Comment by PopGoesTheWza** [comment]
@grant 
Like #608 this issue is rather informational. PR #606 upgrades packages at version which:
- keeps NodeJs 8 compatibility
- pass Travis tests successfully
- comply with `npm audit`

**Comment by grant** [comment]
OK, sounds fine. Thanks.

**Comment by PopGoesTheWza** [comment]
@grant following PR #606 , this issue can be closed, unless one believe that `mocha` package really needs to be upgraded past the version `5.2.0`.
