### ISSUE TITLE
(Minor) outdated `read-multiple-files`

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#608]
Updating `read-multiple-files` to version 3.0.0 or more breaks node 8 support.

It is up to the project owner to decide what option to follow:

- leave as is
- find an alternative compatible with node 8
- drop node 8 support

## Steps to Reproduce the Problem

1.

## Specifications

- Node version (`node -v`): 10 --lts
- Version (`clasp -v`): latest
- OS (Mac/Linux/Windows): Mac OS (latest)

**Comment by grant** [comment]
I don't know the problem with using the outdated version.

Node 8 is only supported until the end of this year, so we could later only support Node 10+ later if needed.

**Comment by PopGoesTheWza** [comment]
This issue is more informational than anything.
In an attempt to fix the `dependencies : out-of-date` badge, in related PR I tried to upgrade every "old" packages. With `read-multiple-files`, from `1.1.1` it can be upgraded to the latest `^2.*.*` while maintaining NodeJs 8 compatibility. Upgrading to any version 3 or above would require a higher version of NodeJs.

**Comment by PopGoesTheWza** [comment]
The irony: after closer inspection, it looks like this dependency is in fact unnecessary and can be dropped.

**Comment by grant** [comment]
Fixed in #606.
