### ISSUE TITLE
Cannot have multiple definitions for the same class name in TS

### ISSUE THREAD

**Issue by allisonchanykei** [google/clasp#611]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

Consider the following folder structure:
```
/bye
> say.ts
/hi
> say.ts
```
where `say.ts` are 2 different declaration of class with the same class name (`Say`).

```typescript
import { Say } from './bye/say';

function myFunction() {
    const bye = new Say();
    const str = bye.word();
    return;
}
```

## Expected Behavior
`bye.word()` should return "bye"

## Actual Behavior
`bye.word()` is returning "hi"

## Steps to Reproduce the Problem

See project: https://github.com/allisonchanykei/google-clasp-issue
See GAS: https://script.google.com/d/14cRtYckxQeHwi051IT61ITxWe5V3kDlpGfjy3UsawPGdfRR4lTvbLkz-/edit?usp=sharing

![image](https://user-images.githubusercontent.com/22278081/57414368-d2c2f980-71c5-11e9-9f28-f446e176c5cb.png)

## Specifications

- Node version (`node -v`): 8.11.2
- Version (`clasp -v`): 2.1.0
- OS (Mac/Linux/Windows): Windows

**Comment by PopGoesTheWza** [comment]
@allisonchanykei Google Apps Script has no support for modules (neither CommonJs nor es). All your transpiled code exists in the same context (i.e. every `*.gs` share the same `this`)

To achieve code isolation, I (strongly) suggest you look at TypeScript `namespace` statement.

There is some example to get you started under [docs/typescript.md](https://github.com/google/clasp/blob/master/docs/typescript.md) too
