### ISSUE TITLE
environment vars & cli options to specify dotfiles

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#616]
In a fashion similar to `tsc --project` and `tslint --project` which allow to specify which (and where) your project configuration file to be used, it would be nice (and useful) to be able to define on the command line different clasp configuration.

## Expected Behavior

`clasp push --project dev.json`
`clasp push --project prod.json`

## Actual Behavior

(some kludgy workaround with additional folders and intricate path references)

## Steps to Reproduce the Problem

1.
1.

## Specifications

- Node version (`node -v`): 10
- Version (`clasp -v`): latest
- OS (Mac/Linux/Windows): Mac (latest)

**Comment by grant** [comment]
Why can't we:
```
clasp setting scriptId id1;
clasp push;
clasp setting scriptId id2;
clasp push;
```
?

What would `dev.json` include?

**Comment by PopGoesTheWza** [comment]
@grant I have started implementing the following design:

- overide path and name for `.clasp.json`, `.claspignore`, `.clasprc.json` & `appsscript.json` by precedence:
  1. commander options (`-P, --project`, `-I, --ignore`, `-A, --auth `-M, --manifest`)
  1. environment variables (`clasp_config_project`, `clasp_config_ignore`, `clasp_config_auth` & `clasp_config_manifest`)
  1. current implementation

Handling scriptIds directly on the command line is clumsy IMHO. And about half a dozen issues are likely to be addressed with cli option/environment vars overrides.

I am also considering an "extended" .clasp.json interface which would allow to hold it all in one file. I haven't yet fully thought it over, but it could look something like the following:

```json
{
  // "legacy" properties
  "scriptId": "scriptId",
  "rootDir": "rootDir",
  "projectId": "projectId",
  "fileExtension": "fileExtension",
  "filePushOrder": "filePushOrder",
  // "extended properties
  "env": {
    // same "legacy" properties
    "claspIgnore": "pathAndNameToClaspIgnore",
    "clasprc": "pathAndNameToClaspRc",
    "manifest": "pathAndNameToAppsScriptJson",
  }
}
```

There you could do commands like `clasp <cmd> --env <env>`

**Comment by PopGoesTheWza** [comment]
@grant 

The goal of this feature request is to enable the user in specifying which/where the following configuration files to be used by Clasp:

- `.clasp.json`
- `.claspignore`
- `.clasprc.json` (local auth)

This sould be possible through:

- environment variables:
  - `clasp_config_project`
  - `clasp_config_ignore`
  - `clasp_config_auth`
- cli options:
  - `-P, --project <file>`
  - `-I, --ignore <file>`
  - `-A, --auth <file>`

The rules to resolve a config file path would be by priority order:
1. if defined via cli option, use this value
1. if defined via environment variable, use this value
1. use default/current behaviour

**Comment by PopGoesTheWza** [comment]
@grant comments? thoughts?

**Comment by grant** [comment]
I can’t really support feature that don’t have at least 10 users or solves a key use case.

I would maybe fork clasp if you really can’t use bash commands to do this and want to add it to the CLI.

**Comment by PopGoesTheWza** [comment]
I can use command line or use my own fork even. The proposed change would potentially address #12 #483 #524 #12 #42 I think, but at that point i’ll Wait for mote traction/support.

**Comment by chechedotmx** [comment]
I want to "git" my gas project, but I need to add some hardcode id´s (google sheet) to the git repository, it would be great to have environment variables inside .clasp.json to avoid the versioning of this id´s

**Comment by grant** [comment]
A design/PR that only included the following would be fine:
- CLASP_PROJECT
- CLASP_IGNORE

no flags, ignore file would be in the project. Be sure to document the variables.

**Comment by PopGoesTheWza** [comment]
@chechedotmx would environment variables to specify `.clasp.json` & `.clasprc.json` address your need?

**Comment by PopGoesTheWza** [comment]
@grant why no flags (cli options)? You're spoiling all the fun!

**Comment by grant** [comment]
Want to start simple. Also flags may conflict with existing command flags.

**Comment by PopGoesTheWza** [comment]
@grant I already did the full PR, so limiting to only `.clasp.json` and `.clasprc.json` should not be problem. Even dishing out the cli options (which do not conflict)
I only need @chechedotmx approval to start.

**Comment by chechedotmx** [comment]
Sounds good @PopGoesTheWza
