### ISSUE TITLE
`.claspignore` does not handle `./` and `../` in paths

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#617]
If the `rootDir` in the `.clasp.json` happens to contain `./` or `../` the .claspignore patterns fails to match anything.

This is in fact an issue within the `multimatch` module

## Expected Behavior

n.a.

## Actual Behavior

n.a.

## Steps to Reproduce the Problem

1.
1.

## Specifications

- Node version (`node -v`): 10
- Version (`clasp -v`): latest
- OS (Mac/Linux/Windows): Mac

**Comment by PopGoesTheWza** [comment]
For reference: https://github.com/sindresorhus/multimatch/issues/29

**Comment by grant** [comment]
We should probably use `glob` to match files.

See:
https://github.com/google/clasp/issues/58
https://github.com/google/clasp/issues/86

**Comment by PopGoesTheWza** [comment]
No need for ‘glob’ in fact.
