### ISSUE TITLE
Documentation for `clasp run` is outdated

### ISSUE THREAD

**Issue by takanakahiko** [google/clasp#623]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

The documentation should show how to get the project id in a new script.

## Actual Behavior

In [run.md](https://github.com/google/clasp/blob/master/docs/run.md) , how to get Project ID is presented as follows

> Add a projectId to your .clasp.json. You can find your Project ID via:
> - clasp open
> - In the menu, click Resources > Cloud Platform project...
> - Copy the project ID. Example: project-id-7006438181792679938.
> - Paste this in projectId in your .clasp.json.

However we can't find Project ID in `Cloud Platform project`.

![image](https://user-images.githubusercontent.com/10114717/58087965-a57e3e80-7bfc-11e9-9587-07540c90e722.png)

In English:
> This script has a Cloud Platform project managed by Google Script.

See also : https://developers.google.com/apps-script/guides/cloud-platform-projects

## Steps to Reproduce the Problem

1.
1.

## Specifications

- Node version (`node -v`):
- Version (`clasp -v`):
- OS (Mac/Linux/Windows):

**Comment by grant** [comment]
:( This is because of a new feature the Apps Script team added to hide the project id.

Now we must paste the ID of our project.
I'm working with the team to make this easier, but for now we should update the instructions to create or use a _project_ and paste the project id here.

**Comment by takanakahiko** [comment]
@grant Thanks! 
Is it okay to change the document to explain how to paste(apply) the project-id?

**Comment by grant** [comment]
Yes, please change it.
