### ISSUE TITLE
clasp push: UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.claspignore'

### ISSUE THREAD

**Issue by grant** [google/clasp#626]
## Expected Behavior

`clasp push` works

## Actual Behavior

`clasp push` without `.claspignore` fails.
```
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.claspignore' 
```

This is probably broken due to a PR that modified `.claspignore`.

I can't publish clasp until this is fixed.

**Comment by grant** [comment]
@PopGoesTheWza @DimuDesigns Can't publish `clasp` until this is fixed.
https://github.com/google/clasp/issues/624#issuecomment-494672834

**Comment by PopGoesTheWza** [comment]
@grant if no defined .claspignore, we could apply a “built in” default?
Something like ignore node_module, and consider only AppsScript.json and *[jt]s in current folder
What do you think?

**Comment by grant** [comment]
The default sounds great.
Please create a PR that fixes this and documents the default ignore file (`node_modules/`).

**Comment by PopGoesTheWza** [comment]
Will do in an hour. I will let you add a test for when there is no .claspignore
