### ISSUE TITLE
TypeError: dotf is not a function

### ISSUE THREAD

**Issue by robfordww** [google/clasp#631]
## Expected Behavior

Being able to run clasp

## Actual Behavior

Gets an error message on any execution of the clasp command

## Steps to Reproduce the Problem

1) Installing clasp like  instructed
2) Running "clasp" or "clasp login" results in the following:

    ...AppData\Roaming\npm\node_modules\@google\clasp\src\dotfile.js:89
        RC: dotf(exports.DOT.RC.DIR, exports.DOT.RC.NAME),
            ^
    TypeError: dotf is not a function
    
## Specifications

- Node version (`node -v`):
v10.14.1
- Version (`clasp -v`):
Clasp -v failes
- OS (Mac/Linux/Windows):
Windows 10

**Comment by PopGoesTheWza** [comment]
@robfordww there is an [issue](https://github.com/grant/dotf/issues/10) with the `dotf` package

A PR to fix it has been produced, for @grant to review and re-publish.

Meanwhile, the workaround is to edit Clasp package.json so that it does not use `dotf@1.3.0`

```json
    "dotf": "~1.2.0",
```

**Comment by darul75** [comment]
confirmed, facing similar issue

**Comment by PopGoesTheWza** [comment]
@robfordww  @darul75 (and others) be sure to issue a `npm install` after patching dotf version to `~1.2.0`

On my system at least, this fixed the issue.

**Comment by darul75** [comment]
I am on a mac and it does not make any differences, I have tried to uninstall it globally and install a previous release but I still got this error.

**Comment by darul75** [comment]
` "dependencies": {
    "chalk": "^2.4.1",
    "cli-spinner": "^0.2.8",
    "commander": "^2.15.1",
    "connect": "^3.6.6",
    "del": "^3.0.0",
    "dotf": "^1.2.0",`

`/usr/local/lib/node_modules/@google/clasp/src/dotfile.js:89
    RC: dotf(exports.DOT.RC.DIR, exports.DOT.RC.NAME),
        ^

TypeError: dotf is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/src/dotfile.js:89:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/src/auth.js:57:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)`

**Comment by PopGoesTheWza** [comment]
@darul75 (and others) for a correct workaround:

1. patch clasp `package.json` with "~1.2.0" for "dotf" version
1. from the clasp root folder run the command `npm uninstall -g @google/clasp && npm run build-fresh` (your system may require you to `sudo` that command)
1. run `clasp --version` to verify clasp no longer crashes

**Comment by darul75** [comment]
ok, thanks my bad, I confused `^1.2.0` with `~1.2.0` your initial @PopGoesTheWza workaround worked.

**Comment by grant** [comment]
Looks like a PR broke the module.
- I deprecated `dotf@1.3.0`
- I published `dotf@1.4.0` with a patch by Pop.

I didn't verify that it works (other than running tests).

Sorry for breaking things.

**Comment by andrewdimmer** [comment]
@PopGoesTheWza Thank you for the work around!

**Comment by grant** [comment]
Hi all,
I believe I've successfully deprecated the broken `dotf` versions on npm, such that `clasp` should work fine for previous and new installs.

If you installed `clasp` between now and yesterday, you may have installed a version that includes the broken `dotf` package. Please re-install `clasp` to undo that.

Let me know if this is still an issue.

### Details

https://www.npmjs.com/package/dotf/v/1.2.0 – Latest/Working (published 6 months ago)
https://www.npmjs.com/package/dotf/v/1.3.0 – Broken (unpublished)
https://www.npmjs.com/package/dotf/v/1.4.0 – Broken attempt to fix (unpublished)

**Comment by dermidgen** [comment]
@grant This appears to have popped up again.  When installing on a fresh system today, I got nailed with this one.  It was trying to use https://www.npmjs.com/package/dotf/v/1.4.1

The same workaround above works for pinning to `~1.2.0`.

You can also install via your project's `package.json` and run using `npx clasp`.  

```
  "devDependencies": {
    "@google/clasp": "^2.2.0",
    "dotf": "~1.2.0"
  }
```

**Comment by PopGoesTheWza** [comment]
@dermidgen PR #739 is successful in build & test with dotf@1.4.1

Can you give more details about reproducing the issue?

**Comment by dermidgen** [comment]
@PopGoesTheWza 

Ubuntu 18.04.4 LTS
Node v12.8.0
NVM v0.32.1

- Cleaned all local & globally installed `node_modules`
- Install via `npm i -g @google/clasp`
- Run `clasp` (also ran `./src/index.js` from `~/.nvm/versions/node/v12.8.0/lib/node_modules/@google/clasp` for same result)

```
~/.nvm/versions/node/v12.8.0/lib/node_modules/@google/clasp/src/dotfile.js:112
    RC: dotf(exports.DOT.RC.DIR, exports.DOT.RC.NAME),
        ^

TypeError: dotf is not a function
    at Object.<anonymous> (~/.nvm/versions/node/v12.8.0/lib/node_modules/@google/clasp/src/dotfile.js:112:9)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (~/.nvm/versions/node/v12.8.0/lib/node_modules/@google/clasp/src/utils.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
```

**Comment by PopGoesTheWza** [comment]
@dermidgen : I just released [`dotf@1.4.2`]<https://github.com/grant/dotf/releases/tag/v1.4.2> which should address this issue

**Comment by dermidgen** [comment]
@PopGoesTheWza you nailed it. Thanks for the amazing turn-around on that! Wowza! :heart_eyes:

**Comment by PopGoesTheWza** [comment]
@dermidgen thanks for pointing out this (silly) bug early.
