### ISSUE TITLE
Make clasp logs timestamps optional

### ISSUE THREAD

**Issue by vsekhar** [google/clasp#638]
## Expected Behavior
`clasp logs` should accept a `--timestamps` parameter to enable the periodic timestamping. Leaving it off should provide "clean" logs which are useful when logs are already timestamped.

## Actual Behavior
`clasp logs` always timestamps

**Comment by grant** [comment]
PRs welcome.

Please add more details to the GitHub issue including an ideal before and after output.

**Comment by campionfellin** [comment]
I like this idea, especially for `claps logs --watch`.

I would amend your timestamps flag to be something like `--with-timestamps` or `--detailed`.

Is this the output you would be imagining?

From:

```
clasp logs
ERROR Sat Apr 07 2019 10:58:31 GMT-0700 (PDT) myFunction      my log error
INFO  Sat Apr 07 2019 10:58:31 GMT-0700 (PDT) myFunction      info message
```

to

```
clasp logs
ERROR  myFunction      my log error
INFO   myFunction      info message
```

**Comment by vsekhar** [comment]
That output works.

I think the other component is the periodic insertion of a timestamp into the log stream by clasp. That should only happen when the timestamps option is enabled.
