### ISSUE TITLE
[MINOR BUG] When contents of .clasp.json is malformed clasp reports 'No .clasp.json settings found'

### ISSUE THREAD

**Issue by DimuDesigns** [google/clasp#642]
## Expected Behavior
When the contents of `.clasp.json` is malformed and a command that references the file is invoked (ex. `clasp pull`), reported error should state that the file is malformed.

## Actual Behavior
For `.clasp.json` files with malformed content, clasp reports:

> **_No .clasp.json settings found. `create` or `clone` a project first._**

This is misleading.

## Steps to Reproduce the Problem

1. Edit `.clasp.json` so that its contents are malformed (ex. delete a comma)
2. Execute a `clasp pull` or `clasp push` command.

## Specifications

- Node version: v10.15.0
- Version: 2.1.0
- OS (Mac/Linux/Windows)

**Comment by grant** [comment]
How about we fix this quickly by saying:

>No `.clasp.json` settings found _or file is malformed_. `create` or `clone` a project first.

PRs welcome.

**Comment by PopGoesTheWza** [comment]
@grant maybe something like:

> No valid `.clasp.json` project file. You may need to `create` or `clone` a project first

**Comment by grant** [comment]
Sure
