### ISSUE TITLE
When create, use the manifest file if it already exists.

### ISSUE THREAD

**Issue by takanakahiko** [google/clasp#643]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

I'm not good at English, so I'm not confident that I can write it well.
Please listen to anything that is hard to understand.

## Expected Behavior

Feature request.
When `clasp create` , use the manifest file if it already exists.

## Actual Behavior

If the manifest file already exists, the manifest file will be overwritten by the `clasp create` command.

For example, [sao-clasp](https://www.npmjs.com/package/sao-clasp) is tool that automatically generating a manifest file and more, but the automatically generated manifest file will be overwritten at `clasp create`.

```bash
# scafolding
$ npx sao clasp

# create project
$ clas create --srcDir src
```

For example, TimeZone information of manifest is also overwritten too.
`sao-clasp` has a function to read information of developer's PC and set TimeZone automatically, But this function is not substantially available.

## Steps to Reproduce the Problem

1. `$ npx sao clasp`
1. `$ clas create --srcDir src`

## Specifications

- Node version (`node -v`): v11.9.0
- Version (`clasp -v`): v2.1.0
- OS (Mac/Linux/Windows):Mac

**Comment by PopGoesTheWza** [comment]
@takanakahiko I did the following test:

```shell
mkdir clasp643
cd clasp643
clasp create
# select standalone
# check that clasp643/appsscript.json exist and edit it
rm .clasp.json && clasp create
# select standalone
# check that clasp643/appsscript.json still exist and was NOT overwritten
```

Next I tried this

```shell
rm appsscript.json
rm .clasp.json
mkdir src
clasp create --rootDir src
# select standalone
# check that clasp643/src/appsscript.json exist and edit it
rm .clasp.json && clasp create
# select standalone
# check that clasp643/src/appsscript.json still exist and WAS overwritten
```

Thus the issue seems that the manifest file is not correctly detected when the `--rootDir` option is set

**Comment by PopGoesTheWza** [comment]
@takanakahiko @grant the cause is very likely because `rootDir` is not passed as a parameter to `manifestExists()` (in `commands/create.ts`, line 101.

I'll post a PR for you to test further.
