### ISSUE TITLE
npm package contains some unnecessary  files

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#649]
## Expected Behavior

Package should contain only files relevant to Clasp

## Actual Behavior

![image](https://user-images.githubusercontent.com/32041843/59446660-357d6580-8e02-11e9-90f5-16b20ee02602.png)

## Steps to Reproduce the Problem

1.  find npm package url
```shell
npm view @google/clasp dist.tarball
https://registry.npmjs.org/@google/clasp/-/clasp-2.1.0.tgz
````
2. Download and inspect `https://registry.npmjs.org/@google/clasp/-/clasp-2.1.0.tgz`

## Specifications

- Node version (`node -v`): [--lts]
- Version (`clasp -v`): [latest]
- OS (Mac/Linux/Windows): Mac [latest]

**Comment by grant** [comment]
Note: I've published `@google/clasp@2.2`

![Screen Shot 2019-07-03 at 12 47 31](https://user-images.githubusercontent.com/744973/60620710-c9eb4000-9d90-11e9-9dbb-85d3cc0561be.png)

---

I think this is fixed. Not sure if it's really important to keep alive as an issue, so I'll close.
