### ISSUE TITLE
Better Debug Logging

### ISSUE THREAD

**Issue by nmccready** [google/clasp#65]
Optional debug logging would go a long way in figuring out what is going on in the clasp API when things do not work as expected. A very common practice in the node community is to utilize [debug](https://github.com/visionmedia/debug). If you want to gain lazy logging please have a look at [debug-fabulous](https://github.com/nmccready/debug-fabulous) (shameless plug).

## Expected Behavior
export DEBUG="@google/clasp*"

`@google/clasp:getProjectSettings oh hi I am a debug statement`

To turn on useful optional log messages.

## Actual Behavior
Only errors are logged.

## Examples

https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/master/src/debug.js#L1

https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/master/src/init/index.js#L49

**Comment by grant** [comment]
PRs or detailed designs are welcome. Debugging `clasp` is an issue for me as well, and would like to see improvement.

**Comment by nmccready** [comment]
I'll try to get to a PR when I get back to working on google app scripts again. Thanks.

**Comment by grant** [comment]
Clasp has been split into multiple files with a testing framework that tests individual utility methods.

I don't know exactly what debug logging this issue would like to see, but I don't think contributors would need a DEBUG setting to make debugging clasp easier. Better testing is preferred over better logging.

I'll close this issue, but feel free to create a new one when there's something specific that should be added to clasp.
