### ISSUE TITLE
When can a new release of clasp be expected?

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#650]
Clasp 2.1.0 is a few months old and many PRs happened since.

## Steps to Reproduce the Problem

1.
1.

## Specifications

- Node version (`node -v`):
- Version (`clasp -v`):
- OS (Mac/Linux/Windows):

**Comment by grant** [comment]
Thanks for the issue (and PRs) @PopGoesTheWza!

I've gone ahead and published `@google/clasp@2.2` today.

Ideally we can get Eric and Steve in the @google/gsuite team to publish every few months. (Takes ~15 minutes to publish and test)

**Comment by PopGoesTheWza** [comment]
@grant Thanks for releasing 2.2 on npm. I did some quick tests and they're fine

Don't you need to commit/sync something still? The `package.json` in `master` branch still says 2.1.0

**Comment by grant** [comment]
Oh, I think I now pushed to GitHub master.
