### ISSUE TITLE
Alternative typescript export workaround

### ISSUE THREAD

**Issue by sgratzl** [google/clasp#651]
I found an alternative workaround for the Typescript module exports workaround: 

```ts
import * as _module from './module';
import * as _module2 from './module2';

declare const exports: typeof _module & typeof _module2;

exports.foo
```

the advantage is that it is easy to define a whole module as part of the imported exports.

## Expected Behavior
n.a

## Actual Behavior
n.a

## Steps to Reproduce the Problem
n.a

1.
1.

## Specifications

- Node version (`node -v`):
- Version (`clasp -v`):
- OS (Mac/Linux/Windows):

**Comment by PopGoesTheWza** [comment]
@sgratzl this is close to what is documented [here](https://github.com/google/clasp/blob/master/docs/typescript.md), right?

Until/unless Google Apps Script underlying JavaScript engine changes, there is absolutely no real support for any flavour of modules (ES, CommonJS, etc.) The fact that module syntax (i.e. `export this` then `import that`) is compiled (thanks to `ts2gas` dirty tricks) doesn't in fact provide code isolation, not even remotely.

I personally moved to another [approach](https://github.com/PopGoesTheWza/ts-gas-project-starter) to achieve proper code isolation, modularity and finer control of the typescript compilation process. Feel free to give it a look and comment.

**Comment by sgratzl** [comment]
yes it is close to the exports workaround: 

```ts
import { foo } from './module';

type _i_foo = typeof foo;  // add a type definition for imported content
declare namespace exports {
  const foo: _i_foo;  // declare typed imported content to the proper namespcae
}

exports.foo;  // address important content as it will be visible when transpiled
```

But in my opinion mine is a nicer variant since you don't have to explicitly list all functions but just merge their exports. 

Another approach would be to use something as [rollup](https://rollupjs.org/guide/en/) which tries to flatten all modules such that you end up with one big output file already in JavaScript. Tho, I haven't tried that one yet.

**Comment by PopGoesTheWza** [comment]
@sgratzl can you please test the following:

- the `import * as _module from './module';` statements can be omitted and do not affect the resulting code (i.e. generated code should be the same with and without the 'import') and execute identically.
- the `declare const exports: typeof _module` allows to correctly reference both named and default `export`s

If both are true, I can issue a PR to amend the documentation if you wish.

I'll be tempted to add a warning like:

> Module in Google Apps Script is a lie

;)

**Comment by PopGoesTheWza** [comment]
@sgratzl about the `rollup` approach (which could be substitued with webpack/gulp/anyOtherBuildChainOfChoice) I feel it goes beyond the scope of `clasp`itself (though @grant and other maintainers are the one to decide)

The approach I choose in the sample project I reference earlier achieve a better (if not true) code isolation and modularity without requiring addition of more  components in the build chain.

**Comment by sgratzl** [comment]
re rollup-plugin: 

sure I'm not saying that `clasp` should implement or enforce something like that. My point is to give developers more tools to develop better projects. Like I'm currently playing around with https://github.com/sgratzl/gappscript-test. for using `rollup` to bundle and modify my code such that it works in the Google App Script environment. 

The basic idea is simple
 * server scripts: create an IIFE (self executing function) and append a simple wrapper that defines all exports as functions that delegate to the real implementation
 * html files: also create an IIFE bundle but inline that in the template HTML file

For example, I included some poliyfills from https://github.com/zloirock/core-js and it worked

**Comment by sgratzl** [comment]
> @sgratzl can you please test the following:
> 
>     * the `import * as _module from './module';` statements can be omitted and do not affect the resulting code (i.e. generated code should be the same with and without the 'import') and execute identically.

I just realized that it can be rewritten to

```
declare const exports: typeof import('./module');
```

Thus, directly deleted by the compiler

> 
>     * the `declare const exports: typeof _module` allows to correctly reference both named and default `export`s

Well, since all the "exported" functions are stored in the **same** exports object, it can result in conflicts, when using the same name in multiple "modules". That is especially true for the default export (`exports.default`) which has the same name in all modules. Thus, it is not safe to use `default` exports since it is not predictable which one it will be in the end. 

The suggested alternative syntax doesn't fix these problems it is just a nicer way to write the already suggested TypeScript exports workaround.

**Comment by PopGoesTheWza** [comment]
@sgratzl Yes... **`module` in GAS is a lie!**

Look at the code produced by:

```ts
export default const pi = 3.141592;
```

a.k.a. *just drop it in the `global`*

```js
// Compiled using ts2gas 3.4.4 (TypeScript 3.5.2)
var exports = exports || {};
var module = module || { exports: exports };
var pi = 3.141592;
````

In your example, you use rollup to **pack** (possibly with tree-shaking in the process) several sources into a single transpiled file (I didn't looked in depth though.) As long as your build chain properly encapsulate/bundle your `module` nuts and bolts (including their own dependencies, it should be fine.

Personnally, this approach introduces too many third-party components I can't fully control and add the burden/complexity of picking/configuring/maintaining a packing line in my build chain.

Of course, those considerations do not apply to the frontend context.

**Comment by grant** [comment]
Feel free to sent a PR to the `docs/` folder about this workaround.
I don't know what we should do to close and fix this issue.

If you want to create a doc around a rollup/webpack solution, that would be great, since I'm sure many developers want to know about this too.

**Comment by PopGoesTheWza** [comment]
@grant I can issue a PR with above mentioned workaround... if you agree on me restating that *module in gas is a lie* and something to be avoided, period.

Solution based on any third-party build chain à la `pack`/`shake` can be achieved using half a dozen different components (webpack, rollup, grunt, browserify, gulp, jake, etc.) and are not worth detailing here, imho.

The only viable solution for code isolation and reuse in gas (without third party), i have documented with a public repos.

**Comment by grant** [comment]
I don't think we state that modules are supported in gas.

I was thinking we could just add something here:
https://github.com/google/clasp/blob/master/docs/typescript.md#the-namespace-statement-workaround
