### ISSUE TITLE
clasp login --creds fails

### ISSUE THREAD

**Issue by brettcarroll** [google/clasp#656]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
Expecting local credentials to be saved within the project folder when using flag.  Saving credentials within the project folder (very useful for switching different profiles) use to be accomplished using the --ownkey flag.  Now it seems that the --creds flag is used.

## Actual Behavior
When running the login with the --creds flag a "no such file" error is produced (see below) and no .clasprc.json file is saved in the directory.

Using the creds flag is mentioned in https://github.com/google/clasp/issues/42 as work around 1 but fails.  Work around 2 of coping the cred file works but is difficult when using many different profiles and not as smooth as the creds file that was saved with --ownkey.

## Steps to Reproduce the Problem

```
clasp login --creds creds.json
	Logging in locally...

	Authorizing with the following scopes:
	https://www.googleapis.com/auth/script.webapp.deploy

	NOTE: The full list of scopes your project may need can be found at script.google.com under:
	File > Project Properties > Scopes

	ENOENT: no such file or directory, open 'creds.json'
```

## Specifications

- Node version (`node -v`):10.16.0
- Version (`clasp -v`):2.1.0
- OS (Mac/Linux/Windows): Windows 10 64

**Comment by mikearche** [comment]
I am unable to reproduce the issue. Be sure that the file you are targeting is in the correct location, or that you have targeted the file correctly.

I got the same output if I targeted a file that did not exist. Perhaps the error outputted should exit before attempting to login if the targeted file does not exist.

**Comment by sqrrrl** [comment]
Not reproducible and likely user error as --creds specifies an *input* file and the error indicates the input doesn't exist.

**Comment by kospl** [comment]
@sqrrrl documentation says it's *output* file, so maybe it worth to fix:

https://github.com/google/clasp/blob/master/docs/config-files.md

Command | Project file | ignore file | Auth file | Manifest file
--- | --- | --- | --- | ---
login | | | Write (`--creds` option) |


while https://github.com/google/clasp/issues/42 is still Open, I would like to add that this is a nightmare to use clasp with multi projects / multi accounts.

And, even if it's *possible* to do, there is literally no steps or guide on how to do it properly - so just sending to "documentation" is not helpful at all.
