### ISSUE TITLE
The "manifestHasChanges" function shouldn't check the line endings

### ISSUE THREAD

**Issue by DominikPalo** [google/clasp#666]
## Expected Behavior
When manifest files differ only in line endings,  "Manifest file has been updated" warning is displayed.

## Actual Behavior
After I push my project from a macOS machine and then the same project from a Windows machine, warning "Manifest file has been updated. Do you want to push and overwrite?" is displayed, although the content of both manifest files is the same. The only difference is that Windows GIT sets line endings of the `appscript.json` to `CRLF` style (during the pull phase), but on macOS, it sets line ending to `LF`. Of course, updating of line endings to `LF` manually in my IDE before every `clasp push` helps, but it's a bit annoying.

I've found that the[ `manifestHasChanges` function](https://github.com/google/clasp/blob/f45f550bbed8c8af4fc22987a24e69332ee97aec/src/commands/push.ts#L77) compares files simply by `localManifest !== remoteManifest.source`, so my proposal is to use a bit more sophisticated way for comparing - like deep compare of `JSON.parse(localManifest )` and `JSON.parse(remoteManifest.source)`.

## Steps to Reproduce the Problem

1. push from macOS
2. push the same project (manifest) from Windows
3.  'Manifest file has been updated. Do you want to push and overwrite?' is displayed

## Specifications

- Node version (`node -v`): v10.16.0
- Version (`clasp -v`): 2.1.0
- OS (Mac/Linux/Windows): macOS/Windows

**Comment by takanakahiko** [comment]
I implemented to compare them as string, according to comment https://github.com/google/clasp/pull/431#discussion_r237969173.
However, it is difficult to make comparisons between strings considering line feed codes.
So I agree with this proposal.

**Comment by PopGoesTheWza** [comment]
@DominikPalo @takanakahiko No time for a PR but I'd consider adding the following [package](https://www.npmjs.com/package/normalize-newline)

and do something like this

```ts
const normalizeNewline = require('normalize-newline');

...

  return normalizeNewline(localManifest( !== normalizeNewline(remoteManifest.source);
```

**Comment by PopGoesTheWza** [comment]
@DominikPalo @takanakahiko (and anyone else interested/willing)

Could you test PR #667 and report if it fixes the issue?
