### ISSUE TITLE
Tests not working on Windows

### ISSUE THREAD

**Issue by mikearche** [google/clasp#668]
## Expected Behavior
SpawnSync should output the appropriate stdout when running tests. 

I'm currently running into an issue where Windows Virtual Terminal Sequences are being outputted. On multiple tests I get: `expected '\u001b[2K\u001b[1G' to include 'string from test here'`.

I've been running the tests on git bash for windows. When I ran this on command prompt I get the same issue as well.

I'm a little stumped on this one, and spent a few days trying to fix.

May be related to #231

## Actual Behavior
The tests should output the appropriate stdout on Windows.

## Steps to Reproduce the Problem

1. Run the tests on Windows 10

## Specifications

- Node version (`node -v`): 12.4.0
- Version (`clasp -v`): 2.2.1
- OS (Mac/Linux/Windows): Windows 10 Version 1809

**Comment by mikearche** [comment]
@wilt00 Do you possibly have any information that may lead me into the right direction?

**Comment by PopGoesTheWza** [comment]
Recently merged PR #662 changes how tests are run. It might be good to check if your issue is affected by this change.

**Comment by wilt00** [comment]
@mikearche Unfortunately I stopped running Windows a few months ago, and don't have access to a Windows box for testing any longer. Sorry!

**Comment by mikearche** [comment]
#662 should at least make this easier to debug... But unfortunately, I'm still getting the errors. 

I'll keep looking into it in the mean time.

**Comment by mikearche** [comment]
So I believe that I've fixed one of the issues.

- **the del library only works for posix pathnames**
The logout test was the first to fail on windows, and that was actually an accurate test! Logging out currently does not work on windows.
Because of this: https://github.com/sindresorhus/del/issues/93

I can go ahead and create a PR, but there are still a couple of failing tests on windows. For some reason I believe the google api calls are outputting a status of 1, but they're getting the correct stdout... This is specifically for the logs setup tests, and the clasp version tests.
