### ISSUE TITLE
clasp push/status fails on large files despite claspignore

### ISSUE THREAD

**Issue by mheffner** [google/clasp#677]
## Expected Behavior

clasp push and status should ignore files/directories listed in `.claspignore` when performing a max file size test

## Actual Behavior

```
$ clasp push
Push failed. Errors:
Exit 1
```

```
$ clasp status
Error: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (4253024256) is greater than possible Buffer: 2147483647 bytes
    at .../.nvm/versions/node/v10.15.3/lib/node_modules/@google/clasp/src/files.js:121:53
    at .../.nvm/versions/node/v10.15.3/lib/node_modules/@google/clasp/node_modules/read-multiple-files/index.js:35:7
    at end (.../.nvm/versions/node/v10.15.3/lib/node_modules/@google/clasp/node_modules/run-parallel/index.js:18:15)
    at done (.../.nvm/versions/node/v10.15.3/lib/node_modules/@google/clasp/node_modules/run-parallel/index.js:22:10)
    at each (.../.nvm/versions/node/v10.15.3/lib/node_modules/@google/clasp/node_modules/run-parallel/index.js:28:7)
    at .../.nvm/versions/node/v10.15.3/lib/node_modules/@google/clasp/node_modules/run-parallel/index.js:43:37
    at .../.nvm/versions/node/v10.15.3/lib/node_modules/@google/clasp/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:37:12)
```

## Steps to Reproduce the Problem

Have a large file in a subdir of the project:
```
$ ls -alh scripts/big_file_4096.bin 
-rw-rw-r-- 1 mheffner mheffner 4.0G Jul 31 10:21 scripts/big_file_4096.bin
```
Directory is ignored:
```
$ grep scripts .claspignore 
scripts/*
$ clasp status
Not ignored files:
└─ appsscript.json
└─ src/main.ts

Ignored files:
└─ tmp/*
└─ node_modules/**
└─ node_modules/**/.*/**
└─ node_modules/**/.*
└─ scripts/*
└─ .clasp.json
└─ .claspignore
````

However, clasp push/status fails with messages above. Removing the large file from any sub directory fixes the problem. Other smaller files under `scripts/` are correctly ignored, but the file size check seems to not be skipped even though the file is ignored.

## Specifications

- Node version (`node -v`): v10.15.3
- Version (`clasp -v`): 2.1.0
- OS (Mac/Linux/Windows): Linux, Fedora 30

**Comment by PopGoesTheWza** [comment]
@mheffner Can you please try to reproduce this issue with the latest `2.2.1` release?

In your log, the package `read-multiple-files` is mentioned. This package has been replace with another alternative since.

**Comment by mheffner** [comment]
@PopGoesTheWza Yep, looks like latest release fixes it. Thanks!
