### ISSUE TITLE
Push failed when using variable of type "let" in script.

### ISSUE THREAD

**Issue by Oshio09** [google/clasp#683]
Here is a piece of code for a google sheets script:

```
function test() {
    let i = 0;
    i++;
}
```
when using `clasp push`, the following error is reported:
```
  errors:
   [ { message: 'Request contains an invalid argument.',
       domain: 'global',
       reason: 'badRequest' } ] }
```

The push is successful when the `let`is swapped by `var`:
```
function test() {
    var i = 0;
    i++;
}
```
I was able to reproduce the error in healthy projects just by changing `var` for `let`.
I believe this could be a bug, can someone reproduce the behavior?

System Info:
Ubuntu 18.04
clasp version: 2.2.1

**Comment by grant** [comment]
Apps Script doesn't support `let`. So this is an error from the API.

If you want to use `let`, you must use TypeScript and have your file end with `.ts`.

**Comment by Oshio09** [comment]
Thanks!
