### ISSUE TITLE
Install clasp without sudo instructions

### ISSUE THREAD

**Issue by grant** [google/clasp#687]
## Expected Behavior

You should be able to install clasp if you don't have sudo permissions.
Document how to do this.

i.e. Using clasp on codesandbox.io/s/node

## Actual Behavior

We don't have instructions for this.

## Steps to Reproduce the Problem

```
npm i @google/clasp
alias clasp=./node_modules/\@google/clasp/src/index.js
```

**Comment by PopGoesTheWza** [comment]
@grant for all it's worth:
- I never needed to `sudo` on Mac OS
- have to tried using clasp via `npx` (which might workaround the need to `sudo`)

**Comment by grant** [comment]
Hmm, must be my laptop or certain Node setups.

**Comment by PopGoesTheWza** [comment]
Give `npx` a try. It should allow you to use clasp even if not installed locally or globally. Do you need to `sudo`for any global package or only clasp?

**Comment by PopGoesTheWza** [comment]
@grant Out of curiosity I did the following test:
- install a fresh NodeJs 10.16.3
- check with npm list -g --depth=0 that there is no global package beside `npm`
- open one existing "clasp" project with only `@google/clasp` package listed under dependencies
- run npm/yarn install to have `@google/clasp` installed (no need to `sudo`)
- run clasp cli commands (I run `clasp push` with no error)

So at least on my system, `@google/clasp` does not require to be installed as a global package, and there is no need to `sudo` (even for a global install)

Why/where do you think `sudo` is necessary?

**Comment by PopGoesTheWza** [comment]
@grant for reference: https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by PopGoesTheWza** [comment]
@grant here are my tests using `npx`

**Running a locally installed `@google/clasp` package**

1. check there's no global `clasp`
```shell
~/prive/test-clasp$ clasp
-bash: clasp: command not found
```

2. install the package locally
```shell
~/prive/test-clasp$ npm install @google/clasp
npm notice created a lockfile as package-lock.json. You should commit this file.
[...]
+ @google/clasp@2.2.1
added 235 packages from 188 contributors and audited 535 packages in 15.478s
found 0 vulnerabilities

```

3. verify that clasp cannot be invoked directly
```shell
~/prive/test-clasp$ clasp
-bash: clasp: command not found
~/prive/test-clasp$ ./node_modules/.bin/clasp
Usage: clasp <command> [options]

clasp - The Apps Script CLI
[...]
```

4. use `npx` to run local clasp
```shell
~/prive/test-clasp$ npx clasp
Usage: clasp <command> [options]

clasp - The Apps Script CLI
[...]
```

**Running `@google/clasp` without package installed**

```shell
~/prive/test-clasp$ npm uninstall @google/clasp
[...]
removed 1 package and audited 1305 packages in 1.609s
found 0 vulnerabilities

~/prive/test-clasp$ ./node_modules/.bin/clasp
-bash: ./node_modules/.bin/clasp: No such file or directory
~/prive/test-clasp$ npx @google/clasp
npx: installed 235 in 9.454s
Usage: clasp <command> [options]

clasp - The Apps Script CLI
[...]
```
