### ISSUE TITLE
clasp push ignores some files in rootDir with v2.2.0

### ISSUE THREAD

**Issue by misterludden** [google/clasp#698]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
clasp push with "rootDir" set in .clasp.json pushes all files under that rootDir 

## Actual Behavior
only 2 files are pushed including appsscript.json to the project. This seems specific to some already existing projects, I did not have this problem on new projects created with clasp 2.2.0. I recently had installed 2.2.0 to see if this was working since I had same issue about a month ago, but it still persists.

## Steps to Reproduce the Problem

1. run clasp push to existing project
2. see only 2 files pushed
3. run npm uninstall -g @google/clasp
4. run npm i -g @google/clasp@2.1.0
5. run clasp push again
6. all files pushed

## Specifications

- Node version (`node -v`): 10.16.0
- Version (`clasp -v`): 2.2.0
- OS (Mac/Linux/Windows): Linux Ubuntu 18.04.3 LTS

**Comment by PopGoesTheWza** [comment]
- Does your .clasp.json has any files or include attributes?
- Beside appsscript.json what is the other file correctly pushed?
- Example of flies not being pushed?

**Comment by misterludden** [comment]
![clasp push only](https://user-images.githubusercontent.com/12755782/64028237-1d5edd80-caf7-11e9-96a2-c5fe3dbd0cc4.png)
![clasp reinstall](https://user-images.githubusercontent.com/12755782/64028238-1d5edd80-caf7-11e9-8315-ece43c561922.png)

here are some examples of my steps to repro

**Comment by PopGoesTheWza** [comment]
likely related to #669 and #692 

With @google/clasp 2.2.0 a (breaking) change was introduced when no `.claspignore` file is defined. In previous version, subdirectories were considered for files to push. In 2.2.0, only files directly in rootDir are considered (I.e. not subfolder)

There is a PR #695 ready which you can try.

One quick workaround is to add this `.claspignore` file next to your `.clasp.json`

```text
# ignore all files...
**/**

# except the extensions...
!appsscript.json
!**/*.gs
!**/*.js
!**/*.ts
!**/*.html

# ignore even valid files if in...
.git/**
node_modules/**
```

**Comment by misterludden** [comment]
Great @PopGoesTheWza - I will give a try to add the .claspignore. And....it works. Thanks a million.

I used to do it but all my ignores are outside the rootDir and I didn't use TS on my old proejcts so I stopped adding a .claspignore file.  Thanks for the quick reply, and btw your GAS TS project starter is beyond helpful.

**Comment by PopGoesTheWza** [comment]
You’re welcome.

Feel free to star the Starter and open issues there if need be.
