### ISSUE TITLE
Add better default `clasp` message.

### ISSUE THREAD

**Issue by grant** [google/clasp#7]
Currently, the command `clasp` with no arguments does not print anything.
We should print the output of `clasp -h` as the default command (`clasp`).

The last time I checked, the `isDefault` argument didn't work for [`npmjs.com/commander`](https://www.npmjs.com/package/commander). See if we can make it work now.

**Comment by cwatson88** [comment]
Hi Grant, 

Can I look into this I think I have a fix and would like to put a PR in?

**Comment by grant** [comment]
@cwatson88 I would happily accept a PR for this! Thanks.
