### ISSUE TITLE
Clasp does not need to be installed globally

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#700]
currently only global install of clasp is documented. This implies that upgrading clasp can break existing projects.

## Expected Behavior

One can install clasp as a local dependency and use nom scripts (or npx’ on the command line) to use the local version of clasp

npm install @google/clasp
npx clasp —version

## Steps to Reproduce the Problem

1.
1.

## Specifications

- Node version (`node -v`):
- Version (`clasp -v`):
- OS (Mac/Linux/Windows):

**Comment by grant** [comment]
We prefer global though. Be sure to still have the main instructions install globally.

**Comment by imthenachoman** [comment]
Out of curiosity, why would you not want to install it globally? Does it break anything else? I install the `@types/google-apps-script` locally cause I don't want it mucking up all my non GAS stuff but I haven't had issues with clasp being global...yet.

**Comment by PopGoesTheWza** [comment]
@PopGoesTheWza my personal taste is to limit global packages to the bare minimun (currently I have `lerna`, `npm` and `pm2`, with `lerna` to go local when I'll have time)

But perhaps the most significant use case is for 'sealing' a project which is known to work with one version of clasp and not take the risk of having issues with future versions.

**Comment by imthenachoman** [comment]
That makes a lot of sense.
