### ISSUE TITLE
`clasp login --status` is still not available?

### ISSUE THREAD

**Issue by nasat75** [google/clasp#704]
hey guys
I found new command option `status` regarding of `clasp login` on README.
but latelest npm version downloaded doesn't exist such a option. 
so I digged closed PR , but da one had merged. 
hmmm, let me know how 2 use dis option or da option launch schedule,🙏

**Comment by grant** [comment]
@nasat75 Can you try installing again? I just published `2.3.0`.

**Comment by nasat75** [comment]
@grant Thank u so much !! it's successful downloaded !!
