### ISSUE TITLE
unable to install clasp on a Windows 10 machine

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#705]
## Expected Behavior

Successful package install of clasp from NPM

## Actual Behavior

After running `npm i @google/clasp -g` I see this:

    C:\Users\nacho>npm i @google/clasp -g
    C:\Users\nacho\AppData\Roaming\npm\clasp -> C:\Users\nacho\AppData\Roaming\npm\node_modules\@google\clasp\src\index.js
    npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

    + @google/clasp@2.3.0
    added 187 packages from 118 contributors and updated 1 package in 56.542s

Then I ran `npm i -g inquirer@^6.0.0`:

    C:\Users\nacho>npm i -g inquirer@^6.0.0
    + inquirer@6.0.0
    added 33 packages from 28 contributors in 8.851s

But when I try to run `clasp` I get an error:

    C:\Users\nacho>clasp
    'clasp' is not recognized as an internal or external command,
    operable program or batch file.

If I run `npm list -g` I see:

    C:\Users\nacho>npm list -g
    C:\Users\nacho\AppData\Roaming\npm
    +-- @google/clasp@2.3.0
    | +-- chalk@2.4.2
    | | +-- ansi-styles@3.2.1
    | | | `-- color-convert@1.9.3
    | | |   `-- color-name@1.1.3
    | | +-- escape-string-regexp@1.0.5
    | | `-- supports-color@5.5.0
    | |   `-- has-flag@3.0.0
    | +-- cli-spinner@0.2.10
    | +-- commander@3.0.1
    ...
      `-- write-file-atomic@2.4.3
        +-- graceful-fs@4.2.2 deduped
        +-- imurmurhash@0.1.4 deduped
        `-- signal-exit@3.0.2 deduped

    npm ERR! peer dep missing: inquirer@^5.0.0 || ^6.0.0, required by inquirer-autocomplete-prompt@1.0.1

I have tried these and then re-installing but that did not fix it:

    npm cache clear --force
    npm cache verify

## Note

This is on my corporate computer and I do not have admin access to it. So I am doing this from a non-admin command prompt. It worked this way when I tried it on my personal computer (without admin) so I feel like it should work here without admin too...

## Steps to Reproduce the Problem

1. `npm i @google/clasp -g`

## Specifications

- Node version (`node -v`): v10.13.0
- NPM version: 6.11.3
- Version (`clasp -v`): n/a
- OS (Mac/Linux/Windows): Windows 10

**Comment by PopGoesTheWza** [comment]
Try the workaround:

npx clasp status

Next check you environment variables (path, node home, etc)

set > env.txt

Try to locate the main components:

where node
where npm
where clasp

Then share the results

**Comment by imthenachoman** [comment]
From `npx clasp status`:
    
    C:\Users\nacho>npx clasp status
    { Error: Command failed: clasp -v
    'clasp' is not recognized as an internal or external command,
    operable program or batch file.

        at ChildProcess.exithandler (child_process.js:289:12)
        at ChildProcess.emit (events.js:182:13)
        at maybeClose (internal/child_process.js:962:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5) killed: false, code: 1, signal: null, cmd: 'clasp -v' }

    No valid .clasp.json project file. You may need to `create` or `clone` a project first.

    C:\Users\nacho>
    
From `set`:

    ALLUSERSPROFILE=C:\ProgramData
    APPDATA=C:\Users\nacho\AppData\Roaming
    CommonProgramFiles=C:\Program Files\Common Files
    CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
    CommonProgramW6432=C:\Program Files\Common Files
    COMPUTERNAME=[redacted]
    ComSpec=C:\windows\system32\cmd.exe
    FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
    FPS_BROWSER_USER_PROFILE_STRING=Default
    HOMEDRIVE=C:
    HOMEPATH=\Users\nacho
    LOCALAPPDATA=C:\Users\nacho\AppData\Local
    NUMBER_OF_PROCESSORS=8
    OneDrive=C:\Users\nacho\OneDrive
    OS=Windows_NT
    Path=C:\windows\system32;C:\windows;C:\windows\System32\WindowsPowerShell\v1.0\;C:\program files\Java\jre8\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Users\nacho\AppData\Local\Microsoft\WindowsApps
    PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
    PROCESSOR_ARCHITECTURE=AMD64
    PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
    PROCESSOR_LEVEL=6
    PROCESSOR_REVISION=8e0a
    ProgramData=C:\ProgramData
    ProgramFiles=C:\Program Files
    ProgramFiles(x86)=C:\Program Files (x86)
    ProgramW6432=C:\Program Files
    PROMPT=$P$G
    PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules
    PUBLIC=C:\Users\Public
    SESSIONNAME=Console
    SystemDrive=C:
    SystemRoot=C:\windows
    TEMP=C:\Users\nacho\AppData\Local\Temp
    TMP=C:\Users\nacho\AppData\Local\Temp
    USERDNSDOMAIN=[redacted]
    USERDOMAIN=[redacted]
    USERDOMAIN_ROAMINGPROFILE=[redacted]
    USERNAME=nacho
    USERPROFILE=C:\Users\nacho
    windir=C:\windows

From `where node npm clasp`:

    C:\Users\nigaman\Desktop>where node npm clasp
    C:\Program Files\nodejs\node.exe
    C:\Program Files\nodejs\npm
    C:\Program Files\nodejs\npm.cmd
    INFO: Could not find "clasp".

Do I need to add something to the environmental variable? Shouldn't it have been set automatically? I don't recall doing this when I installed `clasp` on my home computer...

**Comment by PopGoesTheWza** [comment]
Please check this SO post <https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows>

My guess is that it is similar with the issue you are experiencing

**Comment by PopGoesTheWza** [comment]
@imthenachoman try this:

```sh
SET NODE_PATH=% APPDATA%\npm
clasp status
```

**Comment by imthenachoman** [comment]
Thank you! That fixed it. I wonder why the environmental variable wasn't already set. I don't recall setting it when I installed it at home. I'll investigate that on my end.

**Comment by analorios93** [comment]
I got the same error trying to install clasp 
npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none was installed.
However your solution didn't work with me:
SET NODE_PATH=% APPDATA%\npm
clasp status 

What could I do?

**Comment by PopGoesTheWza** [comment]
@analorios93 what is the output of the commands:

- where node
- bpm list go clasp

**Comment by analorios93** [comment]
where node: 
c:\program files\nodejs\node.exe

where C:\Users\Ruben>where npm: 
c:\program files\nodejs\npm
c:\program files\nodejs\npm.cmd

C:\Users\Ruben>where clasp
c:\program files\nodejs\clasp
c:\program files\nodejs\clasp.cmd

And the bpm list go clasp says this: 
bpm" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Which means can't find the comand bpm. Do I need to install something so it recognize that comand?

**Comment by PopGoesTheWza** [comment]
Sorry, I meant “npm”, not “bpm”

**Comment by analorios93** [comment]
npm list go clasp says this:

C:\Users\Ruben
`-- (empty)

**Comment by gloriamacia** [comment]
I see clasp installed in C:\Users\maciamug\AppData\Roaming\npm but the workaround above does not work for me! :-(

**Comment by willjgomes** [comment]
In case this helps anyone. For me just setting NODE_PATH didn't work either. Once I reinstalled clasp after setting the missing NODE_PATH env variable, it finally worked.
