### ISSUE TITLE
'Syntax error: Missing ; before statement'

### ISSUE THREAD

**Issue by a2chan** [google/clasp#722]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

'Syntax error: Missing ; before statement' error on including most node libraries.

```
errors: [
    {
      message: 'Syntax error: Missing ; before statement. line: 9175 file: code-3.12.0',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
```

Code at line 9175:
```
var NodeType;
(function (NodeType) {
    NodeType[NodeType["ELEMENT_NODE"] = 1] = "ELEMENT_NODE";
    NodeType[NodeType["TEXT_NODE"] = 3] = "TEXT_NODE";
})(NodeType = exports.NodeType || (exports.NodeType = {}));
/**
 * Node Class as base class for TextNode and HTMLElement.
 */
class Node {
    constructor() {
        this.childNodes = [];
    }
}
```

## Specifications

- Node version: 12.14.0:
- Version: 2.3.0
- OS: Linux:

**Comment by PopGoesTheWza** [comment]
@a2chan I am unsure what you are doing but...

> error on including most node libraries.

You should not be able to include **any** nodejs/commonjs/es6 libraries.

The "libraries" available within Google Apps Script are described here: <https://developers.google.com/apps-script/guides/libraries>

For your own sake, I advise you avoid/forget/ban anything related to nodejs/commonjs/es6 modules, starting with the `export`/`import`/`require()` statements.

This part of the doc may give you some background why: <https://github.com/google/clasp/blob/master/docs/typescript.md#modules-exports-and-imports>
