### ISSUE TITLE
getProtections() returns empty array in clasp

### ISSUE THREAD

**Issue by z1abl** [google/clasp#732]
```
function test() {
 return sheet.getProtections(SpreadsheetApp.ProtectionType.RANGE);
}

```
In clasp this function returns empty array: [] but in cloud editor it returns [Protection,Protection].

- Node version (`node -v`): v12.11.1
- Version (`clasp -v`):2.3.0
- OS (Mac)

**Comment by PopGoesTheWza** [comment]
@z1abl are you referencing an issue with Typescript declaration `@types/google-apps-script`? If so it should opened on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by z1abl** [comment]
@PopGoesTheWza , thanks.
