### ISSUE TITLE
inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#736]
## Expected Behavior

Errorless install of `clasp`

## Actual Behavior

Installing `clasp` results in this error:

    sudo npm i @google/clasp -g
    /usr/bin/clasp -> /usr/lib/node_modules/@google/clasp/src/index.js
    npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
    
    + @google/clasp@2.3.0
    added 189 packages from 116 contributors in 11.015s

## Steps to Reproduce the Problem

1. sudo npm i @google/clasp -g

## Specifications

- Node version (`node -v`): v13.8.0
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Linux (Ubuntu 19.10)

**Comment by takanakahiko** [comment]
fixed in #733
@imthenachoman  Wait for the next release.

**Comment by imthenachoman** [comment]
@takanakahiko Got it. Thanks! Sorry if this was mentioned somewhere. I did a search but didn't find any existing issues/comments.

**Comment by fletort** [comment]
So claps 2.3.0 can not be used ?

**Comment by PopGoesTheWza** [comment]
This peer dependency warn can probably be ignored and `@google/clasp` should work.

Alternatively, you can try the unofficial 2.4.0 build

```shell
npm uninstall -g @google/clasp && npm install -g forked-clasp
clasp --version
# should be 2.4.0 or more
```

Last, only `sudo` an npm install if it fails without sudo...

**Comment by CrystalCo** [comment]
Thank you.  Ignoring the dependency warning turned out to be alright.  Had no issues using CLASP after installing it and didn't need to install the dependency.

**Comment by CodingAlbert** [comment]
I received same error on macOS Catalina. Ignoring the dependency warning also turned out to be alright. I will be testing it further.

**Comment by tombohub** [comment]
How can we remove this error for now?

**Comment by waterlava** [comment]
Same issue here on Windows 10 (2004),
node version: v14.15.1
version: 2.3.0
2020-12-04

**Comment by PopGoesTheWza** [comment]
This is a warning that can be safely ignored.

Also you can try this forked npm package 
https://www.npmjs.com/package/forked-clasp
or from the github repository
https://github.com/PopGoesTheWza/clasp/tree/forked

**Comment by PopGoesTheWza** [comment]
Try replacing `@google/clasp` 2.3.0 with `forked-clasp` which is more advanced.

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
```

**Comment by PopGoesTheWza** [comment]
Fixed in https://github.com/google/clasp/releases/tag/v2.3.1

**Comment by tombohub** [comment]
@PopGoesTheWza thank you for you hard work
