### ISSUE TITLE
[RFC] better V8 support

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#741]
Purpose of this issue is to discuss and exchange on how to improve V8 support/integration:

**Comment by PopGoesTheWza** [comment]
I'll start with...

## Possible general features:

  - CLI option to specify engine and update `appsscript.json` when using some commands like `create`, `pull`, `push`

## Possible Typescript related features:

  - detect Rhino/V8 from local `appsscript.json` and provide the appropriate `es3`/`es2019` default `target` to `ts2gas`
  - (optional) detect `target` from local `tsconfig.json` and warn if it does not match engine from local `appsscript.json`

**Comment by PopGoesTheWza** [comment]
@grant how/when can we expect a release?

**Comment by grant** [comment]
> @grant how/when can we expect a release?

Hi @PopGoesTheWza, sorry I don't know the answer to that question as I don't release this project anymore. I've CC'd @erickoledadevrel who can answer that question. (Although, this week is busy for Googlers)

**Comment by erickoledadevrel** [comment]
Assigning to @sqrrrl to answer.

**Comment by connorpb** [comment]
Any word on when this update might be released? Would love to start using V8

**Comment by PopGoesTheWza** [comment]
@erickoledadevrel @sqrrrl can we have a status about this project?

Beside Grant Timmerman (who is no longer working on `@google/clasp` but still review some issues) there doesn't seem to be much (if any) involvement from Google.

**Comment by erickoledadevrel** [comment]
I too no longer work on the G Suite DevRel team.

**Comment by PopGoesTheWza** [comment]
> I too no longer work on the G Suite DevRel team.

So... what happens next? Who's in charge now?

Shall we consider this project closed/dead?

Should the community fork it in order to get some work done, big fixed and updates released?

**Comment by erickoledadevrel** [comment]
I think that's a decision for @sqrrrl now.

**Comment by PopGoesTheWza** [comment]
@sqrrrl hasn't showed up for nearly three months...

Ok. We'll wait some more.

**Comment by PopGoesTheWza** [comment]
Fixed in https://github.com/google/clasp/releases/tag/v2.3.1
