### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by grant** [google/clasp#75]
## Expected Behavior

Developers write readable code that conforms to a style.

## Actual Behavior

Developers write code that is poorly formatted.

## Solution

- Give an example of how we can use an example like [prettier.io](http://prettier.io) to format Apps Script code.
- Integrate it with `clasp`? (Do we need .rc files to specify style?) **No**

**Comment by diminishedprime** [comment]
Adding my two cents to the discussion. 

I'm using prettier personally with some of my AppsScripts projects and it works really great, especially for some things that appsscript considers errors such as semicolons. I make a npm package, and have the clasp-specific stuff all under a `src` directory. Prettier is configured through my `package.json` file. 

I think it'd be frustrating, though, if using clasp meant I had to adopt a specific style. I could see myself disagreeing with the defaults that are picked--i.e. single vs double quotes, line-length, spaces around brackets. 

If the behavior was able to be overridden, or if it only did the steps necessary for a sucessful push (adding semicolons, changing arrow functions to normal function definitions, changing const/let to var) I would really like this feature.

**Comment by grant** [comment]
I agree. I don't think `clasp` should pick a style at all, there's lots of tools to do that. Apps Script is different than Go. 

I removed: _"Should we enforce a certain style like Go?"_

But I think we should tell people how to use some of the existing tools.

**Comment by grant** [comment]
Formatting should be done in `clasp`.
