### ISSUE TITLE
Feature request: `clasp push -w` - add option to push only changed files

### ISSUE THREAD

**Issue by kospl** [google/clasp#760]
Currently `clasp push -w` pushes ALL project files when *any* of files is changed. This behavior is not exactly how it feels it need to work, because for any minor edit, a lot of files are being updated. 

So this is feature request for one of:
1. change behavior of `clasp push -w` to push only changed files
2. additional flag to push only changed files 

It will let speed up local development a lot, thanks!

**Comment by grant** [comment]
Unfortunately the API only allows for a "replace all files" option, so we can't really implement this right now without a new API feature.

See https://github.com/google/clasp/issues/762#issuecomment-629892811

**Comment by kospl** [comment]
Created API feature request: https://issuetracker.google.com/issues/158177675
Feel free to "star" it.

**Comment by darrenlmdse** [comment]
the original ticket is closed due to inactivity, I opened another one here: https://issuetracker.google.com/issues/231616121
feel free to star it as well and I will try to keep it alive

**Comment by Nu11u5** [comment]
@darrenlmdse

How large are your GAS projects where uploading the whole project takes a significant amount of time?

I would also add that GAS is not intended to be used collaboratively.  Even when using the web editor changes made by other users (even in different files) may not be visible until a reload, and accidental overwrites can happen.  Sharing exists simply to provide access, with no features meant to support simultaneous collaboration on projects.

Collaboration should be done using Git or other SCM, with the GAS platform treated as a deployment target, not a repository.
