### ISSUE TITLE
Ignored file removed when do clasp push

### ISSUE THREAD

**Issue by Alinaki** [google/clasp#762]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior

If I create some file directly in the script editor and ignore that file in .claspignore I expect that file not to be removed while pushing

## Actual Behavior

Newly created file deleted from remote project

## Steps to Reproduce the Problem

1. Create a file e. g. config.js in script editor
1. Add this file to .claspignore
1. Do push

## Specifications

- Node version (`node -v`): v12.12.0
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
Yeah, unfortunately the API only allows for a "replace source code" option when pushing. We are replacing all the source code at once. Not sure what to do besides clarify that in the docs.

**Comment by PopGoesTheWza** [comment]
I'll create a doc PR sometime this week
