### ISSUE TITLE
tsconfig.json with the "target": "2019" is flagged by VSCode and appear to have no function

### ISSUE THREAD

**Issue by axtens** [google/clasp#766]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
Was expecting to set "target" to "2019" and have `clasp push` send V8  code to Google Sheets project.

## Actual Behavior
"2019" has a wavy line under it in VSCode suggesting that it is unknown.  `clasp push` continues to push ES3 code into Google Sheets project.

## Steps to Reproduce the Problem

1. Edit `tsconfig.json` with "target" of "2019". Note wavy line under "2019"
1. Run `clasp push`
1. Compare code in VSCode with that in Google Sheets project

_NOTE_
"target" of "ES2019" is acceptable to VSCode. However, ES3 code is still emitted.

## Specifications

- Node version (`node -v`): v14.0.0
- Version (`clasp -v`): 2.2.1
- OS (Mac/Linux/Windows): Windows 10

**Comment by yumetodo** [comment]
See https://github.com/google/clasp/issues/735#issuecomment-590309579 and try again! You need to edit `appsscript.json` .
