### ISSUE TITLE
Can't install CLASP in windows environment.

### ISSUE THREAD

**Issue by Swopno1** [google/clasp#767]
> I'm trying to download and install CLASP in my system. When I try to download CLASP using "npm install -g @google/clasp", it return with an error message. What can I do? 
Here is the details of my system specification.

Visual Studio: 1.44.2 (user setup)
Electron: 7.1.11
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

## Actual Behavior

npm ERR! Unexpected end of JSON input while parsing near '...r":"^2.2.0","husky":"'

## Specifications

- Node version (`node -v`): 12.8.1
- Version (`clasp -v`):
- OS (Mac/Linux/Windows): Windows 10

**Comment by HelioGomesMagalhaes** [comment]
Hi, maybe it's a W10 powershell issue not allowing to execute scripts because of default safety reasons. Google for "powershell change restriction mode". There are some options, including, "unrestricted" mode.

**Comment by PopGoesTheWza** [comment]
@Swopno1 can you provide the npm log file with the error?

**Comment by contributorpw** [comment]
@Swopno1 

before anything what happens if you first call

```powershell
PS C:\> npm cache clean --force
```
?

**Comment by Swopno1** [comment]
@contributorpw 


Get-Process : A positional parameter cannot be found that accepts argument 'npm'.
At line:1 char:1
+ PS C:\> npm cache clean --force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetProcessCommand

**Comment by Swopno1** [comment]
[2020-05-29T14_44_44_013Z-debug.log](https://github.com/google/clasp/files/4702454/2020-05-29T14_44_44_013Z-debug.log)

@PopGoesTheWza 

Please, find the log file.

**Comment by PopGoesTheWza** [comment]
Does the command « where npm » correctly resolve path to your npm executable?

**Comment by PopGoesTheWza** [comment]
What does « npm —version » outputs?

**Comment by PopGoesTheWza** [comment]
Can you test with the #791 unofficial release?

```shell
npm uninstall -g @google/clasp && npm install -g forked-clasp
clasp --version
# should be 2.4.0 or more
```

**Comment by Swopno1** [comment]
I just re-install my Windows and its working now. Thanks for your assitance.
