### ISSUE TITLE
clasp push fails with 'for...of', 'Array.prototype.map', 'Array.prototype.forEach' and arrow functions.

### ISSUE THREAD

**Issue by LoveSponge** [google/clasp#768]
## Expected Behavior
should be able to push any file including a 'for...of' loop

## Actual Behavior
Pushing file as described in reproduction steps prints following output:
```
> clasp push

- Pushing files...Push failed. Errors:
GaxiosError: Syntax error: Syntax error. line: 3 file: test
    at Gaxios._request (C:\<redacted>\gmail_add-on\node_modules\gaxios\build\src\gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OAuth2Client.requestAsync (C:\<redacted>\gmail_add-on\node_modules\google-auth-library\build\src\auth\oauth2client.js:350:18) {
  response: {
    config: {
      url: '',
      method: 'PUT',
      paramsSerializer: [Function],
      data: [Object],
      headers: [Object],
      params: [Object: null prototype] {},
      validateStatus: [Function],
      retry: true,
      body: **ALL STRINGIFIED CODE**,
      responseType: 'json',
      retryConfig: [Object]
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Mon, 04 May 2020 15:11:42 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: ''
    }
  },
  config: {
    url: '',
    method: 'PUT',
    paramsSerializer: [Function],
    data: {
      scriptId: '1MNlr6RHlgvyAXt1RX-dgMLKj7pExPpG330jTfwV4cqRo7_vSnpSmIcqf',
      files: [Array]
    },
    headers: {
      'x-goog-api-client': 'gdcl/3.2.2 gl-node/12.16.2 auth/5.10.1',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/3.2.2 (gzip)',
      Authorization: 'BEARER TOKEN',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    retry: true,
    body: **ALL CODE JSON STRINGIFIED**,
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: 400,
  errors: [
    {
      message: 'Syntax error: Syntax error. line: 3 file: test',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
└─ GetContextualAddOn.gs
└─ appsscript.json
└─ cards.gs
└─ helpers.gs
└─ test.gs
Pushed 5 files.
```

## Steps to Reproduce the Problem

1. create a file with the following content:
```js
// test.js (in project root)
const array = [1,2,3]
for(const i of array) {
    console.log(i)
}
```
2. run `clasp push` (after having logged in to clasp of course)

## Specifications

- Node version (`node -v`): 12.16.2
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Windows

# UPDATES

- Added error log information to actual result.
- Added code example to reproduction steps.

---
So i tried to use forEach loops instead, exactly the same thing happens.

---
Fails on map too...

---
Okay so it looks like it works for the following syntax:
```js
for(var i = 0; i < x.length; i++) { ... }
```
Note the `var` assignment, it fails if you use `let` or `const`, despite being able to write both outside the context of writing a for loop.
It does however still fail if you write:
```js
for(var x of y) { ... }
```

hope this is helpful
---

**Comment by grant** [comment]
`for...of` is not part of JavaScript 1.6 I believe.
The API fails when trying to upload files with invalid JS.

Maybe use V8 or normal for loops?
https://developers.google.com/apps-script/guides/v8-runtime

**Comment by LoveSponge** [comment]
Hi @grant

Thanks for your reply, I'll check the link first thing in the morning;

How might I get clasp to recognise that I'm writing code intended for V8? As far as I know, I have enabled V8 on the Web version of appsScript, it's only when running clasp from the command line on my machine that I see this error?

Should I have some special setting to tell clasp that the code is destined for V8?

Would the above work and allow me to use the latest syntax? (a quick skim through the link you posted suggests the answer is yes, but just to be sure.)

Thanks again for your time

**Comment by grant** [comment]
Check the link.
It's all server-side errors, clasp doesn't affect it other than uploading your `appsscript.json` which specifies the V8 engine.

I think the `.ts` feature of clasp might enable `for of` loops too, so you could try renaming your files to `.ts`.
Hope that helps.
–Grant

**Comment by PopGoesTheWza** [comment]
@LoveSponge `@google/clasp` should have no problem pushing 'modern JavaScript'/'V8'/'ES2019' code as long as the `appsscript.json` manifest enables the use of the 'V8' engine.

If it does not work with the (somewhat old) NPM published package, you should try using a clone from this repository `master` branch.
