### ISSUE TITLE
not downloading `libraries` mentioned in  appsscript.json

### ISSUE THREAD

**Issue by Gauravshah** [google/clasp#779]
## Expected Behavior
clasp clone should also clone all libraries within appscript.json, this will help auto-complete for those custom libraries as well

## Actual Behavior
clasp downloads the current script folder but not the libraries mentioned

## Steps to Reproduce the Problem

1. create a new script project
2. add any library like picasa
3. use it in the code
4. clone via clasp
5. autocomplete won't work

## Specifications

- Node version (`node -v`): v14.3.0
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Mac

**Comment by PopGoesTheWza** [comment]
@Gauravshah I just did a test using #778 and the `appsscript.json` of the cloned script project do in fact have the correct `libraries` listed.

**Comment by Gauravshah** [comment]
thanks @PopGoesTheWza

**Comment by Gauravshah** [comment]
@PopGoesTheWza I tried the branch but I get following:

```
 clasp clone 1.......e
Warning: files in subfolder are not accounted for unless you set a '.claspignore' file.
Cloned 4 files.
└─ Controller.js
└─ Code.js
└─ analyser.js
└─ appsscript.json
Not ignored files:
└─ Code.js
└─ Controller.js
└─ analyser.js
└─ appsscript.json

Ignored files:
```

It did not clone the appscript.json's libraries

**Comment by PopGoesTheWza** [comment]
That is the expected result. 
The appsscript.json holds references to external libraries which are distinct projects. Source files of libraries are not retrieved.

**Comment by Gauravshah** [comment]
@PopGoesTheWza may be I didn't explain it well. The issue with this approach is that external library codes are not downloaded hence auto-complete for library classes don't work.
For ex If I have `S3` lib in `appscript.json` and I try to use `S3.` I do not see any results

**Comment by PopGoesTheWza** [comment]
I see what you mean. I benefit from auto complete by having a .d.ts for my libraries since I am coding with typescript.

**Comment by Gauravshah** [comment]
have to manually generate each of those. also not all libraries are modules, so no export. Unsure how gas is doing it in the first place

**Comment by PopGoesTheWza** [comment]
First avoid any `export`/`import` with GAS. Those are a lie and only add confusion, IMHO.

You may want to give a look at this [template of mine](https://github.com/PopGoesTheWza/ts-gas-project-starter) (which could benefit with some update) for multiple GAS projects and shared libraries.

Back to your original issue, one thing to try is organising your project like

- add a subfolder to hold cloned libraries
- setup `clasp.json` to ignore above subfolder and its content

There is likely one more thing to address: a library with public variable/function/class `A` is referenced in your appsscript.json by a `userSymbol` (i.e. `MyLibWithA`) which acts as a namespace to address the content of the library:

```js
var a = MyLibWithA.A();
```

So we have to find an elegant way to express this in order for the IDE to 'understand' where/what/how `A` is addressed.

**Comment by Gauravshah** [comment]
Yup started cloning all libraries into `lib/<appscript_userSymbol>` but still stuck with IDE having to understand that public functions referenced as `userSymbol.A()` 
Tried looking but didn't find anything that would help us reference this for IDE

**Comment by PopGoesTheWza** [comment]
I had started working on a project to generate .d.ts for libraries but had to stop due to limited free time...

**Comment by Gauravshah** [comment]
I am new to typescript world. Will take stab at trying to understand `.d.ts` there are following generators:
https://github.com/mhelvens/js2tsd
https://github.com/Microsoft/dts-gen
https://github.com/ConquestArrow/dtsmake

**Comment by PopGoesTheWza** [comment]
@Gauravshah Typescript compiler `tsc` can generate `.d.ts` declaration files from both `.js` and `.ts` files but those cannot be used as third party libraries without some transformation.
AFAIK, there is no automated generator available for this transformation.

**Comment by Gauravshah** [comment]
thanks @PopGoesTheWza
