### ISSUE TITLE
Serve locally for testing

### ISSUE THREAD

**Issue by sindhus** [google/clasp#78]
## Expected Behavior

I expect there to be an option to serve the script locally for easier testing. 

## Actual Behavior

There is no clasp command-line option to serve the Google Apps Script locally. 

## Specifications

  - Node version (`node -v`): v9.8.0
  - Version (`npm list | grep clasp`):

```
➜  ~ npm list | grep clasp
➜  ~ which clasp
/usr/local/bin/clasp
```
  - OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment]
Are you looking to run functions locally?
That's almost impossible since Apps Script binds to Google Services like Gmail, Slides, etc.

**Comment by sqrrrl** [comment]
Probably best tackled outside clasp. Really this is asking for a local apps script runtime. It's (mostly) feasible but a very large project to create an emulator that can be run locally.

I do find https://www.npmjs.com/package/gas-local to be useful in tests. Still have to mock out whatever services you use, but at least gives you loading and module (err, lack of) behavior similar to apps script.

**Comment by grant** [comment]
Going to close this in favor of #11.
