### ISSUE TITLE
Add link to "see below" for setting up Project ID/Credentials

### ISSUE THREAD

**Issue by leeyspaul** [google/clasp#792]
DOC: It would be useful to add a hyperlink to the "see below" section for setting up Project ID/Credentials for the added commands.

Section here: https://github.com/google/clasp#advanced-commands-1

Link to section: https://github.com/google/clasp#projectid-optional

Could be labeled as a good first issue if people agree that it'd be useful!

> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
N/A

## Actual Behavior
N/A

## Steps to Reproduce the Problem

1.
1.

## Specifications
N/A

- Node version (`node -v`):
- Version (`clasp -v`):
- OS (Mac/Linux/Windows):

**Comment by PopGoesTheWza** [comment]
Is this strictly a documentation issue? Can anyone volunteer for a PR?

**Comment by MadeleyKarina** [comment]
Hello, can I be assigned this??
