### ISSUE TITLE
`test/commands` are not tested on CI

### ISSUE THREAD

**Issue by tricknotes** [google/clasp#793]
Since 3a1948c269dd5817a72b15ef23fb8ff6691ac11a, tests under `tests/commands` are not tested via `$ npm run test`.
The following diff enables tests, but it seems there are some failing tests...

``` diff
diff --git a/package.json b/package.json
index a361c3b..e81134d 100644
--- a/package.json
+++ b/package.json
@@ -10,7 +10,7 @@
     "prepare": "npm run compile",
     "publish": "npm publish --access public",
     "lint": "npm run check",
-    "test": "nyc mocha --cache false --timeout 100000 build/test",
+    "test": "nyc mocha --cache false --timeout 100000 build/test/*.js build/test/**/*.js",
     "coverage": "nyc --cache false report --reporter=text-lcov | coveralls",
     "prettier": "prettier src test --write",
     "check": "gts check src/*.ts src/**/*.ts test/*.ts test/**/*.ts",
```

**Comment by PopGoesTheWza** [comment]
Good pick. Do you rather feel like opening another PR or include it in #789 ?

If when reenabling ignored tests, it reveals that some were broken, a separate PR is probably best.

My guess if that the entire test suite should be revisited, probably refactored, but it is not my strongest point.

**Comment by tricknotes** [comment]
Thanks for your comment, @PopGoesTheWza 
I'll make another PR.
