### ISSUE TITLE
export const x = "y" converts to exports.x = "y" and fails to be imported at runtime.

### ISSUE THREAD

**Issue by julian-payne** [google/clasp#796]
```export const x``` does not work.
For example:

## Expected Behavior & Steps to Reproduce the Problem

in file 'constants.ts'
```javascript
export const SheetId = "sheetId1234";
```

in file code.ts
```javascript
function main() {
  let ss = SpreadsheetApp.openById(SheetId);
  Logger.log(ss.getName());
}
```
Running main should log the Spreadsheet's name.

## Actual Behavior

I get the error `ReferenceError: SheetId is not defined`

## Specifications

- Node version: 14.5
- Version: 2.3.0
- OS Mac: Mojave

I believe this to be a bug. Known issue?

**Comment by leeyspaul** [comment]
Not sure if this is related to `clasp` or the way `ts2gas` transpilation works. Can't say, as I don't know much about how that transpilation works.

I pushed up the code with the same files except I explicitly aded `exports` when calling `SheetId` which seemed to solve the issue.

Below is what rendered on my side when I pushed it up to a script project. 

In `constants.gs`
```
// Compiled using ts2gas 3.6.3 (TypeScript 3.9.7)
var exports = exports || {};
var module = module || { exports: exports };
exports.SheetId = void 0;
exports.SheetId = "id123";
```

In `code.gs`
```
// Compiled using ts2gas 3.6.3 (TypeScript 3.9.7)
var exports = exports || {};
var module = module || { exports: exports };

function main() {
    console.log(exports);
    console.log(exports.SheetId);
  
    var ss = SpreadsheetApp.openById(exports.SheetId);
    Logger.log(ss.getName());
    console.log(ss.getName());
}
```

In my logs: 

```
DEBUG      2020-07-23T04:18:24.035Z N/A {"message":"{ SheetId: 'id123' }","serviceContext":{"service":"..."}}
DEBUG      2020-07-23T04:18:24.038Z N/A {"message":"id123","serviceContext":{"service":"..."}}
```

Alternatively running it without the export seems to work.

**Comment by syzhakov** [comment]
It is not currently supported, but there are some workarounds in their docs:
https://github.com/google/clasp/blob/master/docs/typescript.md

**Comment by julian-payne** [comment]
> It is not currently supported, but there are some workarounds in their docs:
> https://github.com/google/clasp/blob/master/docs/typescript.md

Well, in the doc's example, it does not what it claims to behave as:
```typescript
// Export (The export keyword is ignored)
export const pi = 3.141592;
```
But as we all know, `export` is not ignored.

Although @leeyspaul 's solution does work, you cannot have this on the local copy, so I decided to go with wrapping in a function:
```typescript
export function getSheetId(): string {
    return "sheetId1234";
}
```
The link to the thread does seem to be related. Thanks for pointing me to the thread.

Thank you all for the suggestion :D

**Comment by syzhakov** [comment]
There is another trick that I've figured - you can declare the vars without `export` and in the end of the file add
`export {varX, varY}`

The thing is that appsscript expect it to be without export, but typescript needs this export to tell the compiler that those vars are intended (and allowed) to be imported somewhere else.
in appsscript, vars are anyways accessible in other files as they are globally defined, so this way you both define it globally for appsscript (but ts will encapsulate them from the usage in other files), and also export them (which will be used to regularly export vars in TS, but will be kind of ignored in appsscript).
Thats for sure better than wrapping every global var in a function :)

Wish it helps!

**Comment by julian-payne** [comment]
> There is another trick that I've figured - you can declare the vars without `export` and in the end of the file add
> `export {varX, varY}`
> 
> The thing is that appsscript expect it to be without export, but typescript needs this export to tell the compiler that those vars are intended (and allowed) to be imported somewhere else.
> in appsscript, vars are anyways accessible in other files as they are globally defined, so this way you both define it globally for appsscript (but ts will encapsulate them from the usage in other files), and also export them (which will be used to regularly export vars in TS, but will be kind of ignored in appsscript).
> Thats for sure better than wrapping every global var in a function :)
> 
> Wish it helps!
> 
> ```
> const a = 'BLA_BLA';
> 
> ...
> 
> export {
>    a
> }
> ```

NOICE. Thanks for sharing :)
I'm going to make the changes in my code.
