### ISSUE TITLE
intermittent clasp push issues

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#803]
## Actual Behavior

I am getting intermittent errors with `clasp push`. Sometimes it will push fine, and sometimes I will get this error:

    Could not find script.
    Did you provide the correct scriptId?
    Are you logged in to the correct account with the script?

Like, I will run the command, it will push, then immediately run the command again and it will give that error. Then I'll keep getting that error and eventually it'll push again. I can't figure out what or why.

Is there a way to turn on verbose logging to see what might be wrong?

## Steps to Reproduce the Problem

1. type `clasp push`

## Specifications

- Node version (`node -v`): v12.13.1
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Windows 10

**Comment by imthenachoman** [comment]
Any luck/help on this? I'm getting these errors quite often. I will run it 50 times and get the error and then run it again and won't. I can't figure out what could be causing the error. Is there a way to debug?

**Comment by PopGoesTheWza** [comment]
@imthenachoman is it still occurring? Does switching to `forked-clasp` helps?

**Comment by imthenachoman** [comment]
Will check. Sorry, hectic day.

**Comment by PopGoesTheWza** [comment]
Should be fixed in https://github.com/google/clasp/releases/tag/v2.3.1

**Comment by imthenachoman** [comment]
So should we be using `forked-clasp` or `clasp` v2.3.1?

**Comment by PopGoesTheWza** [comment]
@imthenachoman since @google/clasp now has official maintainers and there are new releases, go with @google/clasp 2.3.1 (or 2.4.0 when it is released)
