### ISSUE TITLE
getAllProjectFiles() ignore every file

### ISSUE THREAD

**Issue by connorhu** [google/clasp#809]
There is a missing getApiFileType function call.
https://github.com/google/clasp/blob/377ead1312dc3e2c89729f2bb4b08a985dd877a5/src/files.ts#L85

**Comment by PopGoesTheWza** [comment]
@connorhu can you please be more specific? I am unsure about both the issue and the fix here.

**Comment by sqrrrl** [comment]
Closing due to lack of additional of information + lack of reproducibility.
