### ISSUE TITLE
What execution policy should be set for clasp to work on Windows 10?

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#810]
## Expected Behavior

Clasp should run.

## Actual Behavior

I am getting the following error when trying to run Clasp on a Windows 10 machine. I am trying to find the most secure execution policy I can set to get Clasp to work. Maybe there is a way to just allow Clasp?

    PS C:\Users\nacho> clasp --version
    clasp : File C:\Users\nacho\AppData\Roaming\npm\clasp.ps1 cannot be loaded. The file
    C:\Users\nacho\AppData\Roaming\npm\clasp.ps1 is not digitally signed. You cannot run this
    script on the current system. For more information about running scripts and setting execution
    policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    At line:1 char:1
    + clasp --version
    + ~~~~~
        + CategoryInfo          : SecurityError: (:) [], PSSecurityException
        + FullyQualifiedErrorId : UnauthorizedAccess

    PS C:\Users\nacho> Get-ExecutionPolicy -list
    
            Scope ExecutionPolicy
            ----- ---------------
    MachinePolicy       Undefined
       UserPolicy       Undefined
          Process       Undefined
      CurrentUser       Undefined
     LocalMachine       AllSigned

## Steps to Reproduce the Problem

1. Run `clasp`

## Specifications

- Node version (`node -v`): v14.11.0
- Version (`clasp -v`): Can't check; just installed
- OS (Mac/Linux/Windows): Windows 10

**Comment by PopGoesTheWza** [comment]
This is more of a "nodejs over Windows" than a clasp issue IMHO.
