### ISSUE TITLE
Support for developing using ES Modules

### ISSUE THREAD

**Issue by atti187** [google/clasp#819]
## Expected Behavior
Documentation describing a setup where one can use ES Modules (import/export-statements)

## Actual Behavior
Currently not in scope

## Steps to Reproduce the Problem

N/A

## Specifications

PR is coming...

**Comment by PopGoesTheWza** [comment]
I could merge PR with more feedback from users.

**Comment by contributorpw** [comment]
Why not? It's clean and it's in a separate documentation file.

If I can get my `+1`
