### ISSUE TITLE
typescript types for services

### ISSUE THREAD

**Issue by tmc** [google/clasp#821]
It doesn't appear that `@types/google-apps-script` has types for `DocumentApp`, `SpreadsheetApp`, etc.

Are these available/published anywhere?

**Comment by contributorpw** [comment]
You need to use this as a part of your npm project. There is no a clasp dependencies.

https://www.npmjs.com/package/@types/google-apps-script

Also you can define global entry pointers for your eslint settings https://github.com/selectnull/eslint-plugin-googleappsscript (if you're using)

As for the `class` itself it works in an environment other than Google Apps Script and it doesn't have access to this environment.

<sup>_Hope I understood you correctly._</sup>

**Comment by PopGoesTheWza** [comment]
`@types/google-apps-script` issues should be discussed under https://github.com/DefinitelyTyped/DefinitelyTyped

You may give a look at this template https://github.com/PopGoesTheWza/ts-gas-project-starter for setup.
