### ISSUE TITLE
@types/google-apps-script installed but not recognized on VSCode

### ISSUE THREAD

**Issue by everspader** [google/clasp#825]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
When I install the Typescript autocompletion via `npm` package, it is not properly recognized on VSCode, no matter in which level (current or parent directory) I install it.

## Actual Behavior
Typescript autocompletion not being recognized by VSCode
```
/app-script/node_modules/...
/app-script/clasp.json
/app-script/package-lock.json
/app-script/package.json
/app-script/src/appscript.json
/app-script/src/Code.js
```

## Steps to Reproduce the Problem

1. `npm i @types/google-apps-script`
1. 

## Specifications

- Node version (`node -v`): 15.5.1
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Ubuntu 20.04

**Comment by contributorpw** [comment]
The `clasp` has nothing to do with `@types`.

Before anything check you have an installed TS Server in your current environment

```sh
$> npx tsc

npx: installed 1 in 4.236s
Version 1.5.3
# ... blah-blah
```

Install it if it's no there. There are many ways. I'm using independent local installations like

```sh
$> npm i -D typescript
```

Another issue can fired with VS Code extensions. Try all of your stuff in

```sh
$> code --daisable-extensions
```

Beware your environment should be clear for you.

**Comment by Nu11u5** [comment]
Did you prepend your .js files with `// @ts-check`?  Otherwise VSCode will not perform typescript autocompletion on .js files.

**Comment by PopGoesTheWza** [comment]
@everspader indeed, types packages are not related to ˋgoogle/claspˋ

Have a try with this project template which has GAS types enabled in vscode.

https://github.com/PopGoesTheWza/ts-gas-project-starter
