### ISSUE TITLE
[Feature Request] Mode for fewer permission

### ISSUE THREAD

**Issue by takanakahiko** [google/clasp#829]
Currently, Clasp needs permissions to read Google Drive.
This is an excessive permission and should not be used in use cases with high security requirements, such as companies.

See also [defaultScopes of src/auth.ts](https://github.com/google/clasp/blob/4464f73465dd9697ae22fab81c42370ca98232c6/src/auth.ts#L76)

Therefore, we need a mode with reduced permissions for clasp.
Specifically, we think it would be useful to have a mode in which the following permissions are removed.

- 'https://www.googleapis.com/auth/drive.metadata.readonly', // Drive metadata
- 'https://www.googleapis.com/auth/drive.file', // Create Drive files
- 'https://www.googleapis.com/auth/service.management', // Cloud Project Service Management API
- 'https://www.googleapis.com/auth/logging.read', // StackDriver logs
- 'https://www.googleapis.com/auth/userinfo.email', // User email address

**Comment by PopGoesTheWza** [comment]
@takanakahiko any idea on how it should be implemented? Doesn't the `clasp login --creds <file>` (I never used it) somehow already address this feature request?

**Comment by takanakahiko** [comment]
I closed this issue as it can be achieved with `clasp login --creds <file>`
