### ISSUE TITLE
[help needed] Accessing customSettings from the code

### ISSUE THREAD

**Issue by Mosquid** [google/clasp#830]
How do I pass a custom config (or .env) file to my clasp project? I found a couple of issues that seem relevant, but neither of them references how to access properties from my custom config in the code. If it's covered in your docs please point out where I can find it. Thank you

**Comment by PopGoesTheWza** [comment]
This feature is currently available by replacing @google/clasp with forked-clasp

**Comment by PopGoesTheWza** [comment]
On second thought, I am unsure what you are trying to achieve.

**Comment by Mosquid** [comment]
Thank you, @PopGoesTheWza. Sorry for not being clear. I have multiple environments that use different API keys and endpoints. I want to be able to pass a param when deploying a project (or running locally) that will switch the environments, depending on the param value

**Comment by PopGoesTheWza** [comment]
Then give forked-clasp a try. You can specify where/which config files by environment variables or clasp options.
