### ISSUE TITLE
clasp clone ignores rootDir option if there is already a .clasp.json in a parent directory

### ISSUE THREAD

**Issue by VAggrippino** [google/clasp#832]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
`clasp clone aaaBBBzzz --rootDir .` clones a project and writes the `.clasp.json` in the specified directory.

## Actual Behavior
`clasp clone aaaBBBzzz --rootDir .` clones a project in the current directory, but updates the `.clasp.json` file in a higher level directory rather than writing one in the specified directory.

## Steps to Reproduce the Problem

1.`clasp clone <project-id> --rootDir .` in a subdirectory of another clasp project.

## Specifications

- Node version (`node -v`): 10.19.0
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Linux

**Comment by sqrrrl** [comment]
Fixed in 2.4.1
