### ISSUE TITLE
refresh tokens not apparently working after upgrade to 2.3.1

### ISSUE THREAD

**Issue by kcculhwch** [google/clasp#839]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
after updating to 2.3.1 `clasp run` should continue to work without requiring hourly `clasp login --creds creds.json`

## Actual Behavior
after updating to 2.3.1 `clasp run` will not successfully run one hour after running

## Steps to Reproduce the Problem

1. Create successful project with clasp 2.3.0
2. Verify it runs with `clasp run`
3. update to clasp 2.3.1
4. it works for a short while, but after an hour so of not running it it errors out with `Error retrieving access token: Error: unauthorized_client`
5. re login with `clasp login --creds creds.json` and it seems to work 
6. Wait another hour, and retry `claps run` the error returns.
7. immediately downgrade to 2.3.0 and it `claps run` works successfully

## Specifications

- Node version (`node -v`):
v14.17.0
- Version (`clasp -v`):
2.3.0
2.3.1
- OS (Mac/Linux/Windows):
Mac + Docker

**Comment by sqrrrl** [comment]
Published 2.3.2 which is effectively a rollback to 2.3.0. There were some breaking changes related to config files that need to be sorted out.

**Comment by PopGoesTheWza** [comment]
> There were some breaking changes related to config files that need to be sorted out.

Do you need help?
