### ISSUE TITLE
replace old `watch` dependency with `chokidar`

### ISSUE THREAD

**Issue by PopGoesTheWza** [google/clasp#841]
## Expected Behavior

n.a.

## Actual Behavior

The `watch` package has not been updated in years and latest version have vulnerabilities:

```shell
~/ref/clasp master* 17s
❯ npm audit
# npm audit report

merge  <2.1.1
Severity: high
Prototype Pollution - https://npmjs.com/advisories/1666
fix available via `npm audit fix --force`
Will install watch@0.13.0, which is a breaking change
node_modules/merge
  exec-sh  <=0.3.1
  Depends on vulnerable versions of merge
  node_modules/exec-sh
    watch  >=0.14.0
    Depends on vulnerable versions of exec-sh
    node_modules/watch

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

## Steps to Reproduce the Problem

1. in `package.json` set `watch` version to "^1.0.2"
1. run `npm install`

## Specifications

- Node version (`node -v`): v16.0.0
- Version (`clasp -v`): 2.3.1
- OS (Mac/Linux/Windows): Mac

**Comment by PopGoesTheWza** [comment]
@sqrrrl I'll try to issue a PR asap

**Comment by sqrrrl** [comment]
Hold off, working on it right now :)
