### ISSUE TITLE
Warnings output after npm install

### ISSUE THREAD

**Issue by kospl** [google/clasp#847]
## Expected Behavior
`npm install -g @google/clasp` installs without any WARN messages

## Actual Behavior
after running `npm install` there is warning output:

> npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

## Steps to Reproduce the Problem

1. `npm uninstall -g @google/clasp`
1. `npm install -g @google/clasp`
2.  see warning 
> npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
>
>\+ @google/clasp@2.3.2

## Specifications

- Node version (`node -v`): v14.17.0
- Version (`clasp -v`): 2.3.2
- OS (Mac/Linux/Windows): Win10

**Comment by sqrrrl** [comment]
Already fixed in main branch for next release (2.4?)
