### ISSUE TITLE
how to use "library" as in the script editor?

### ISSUE THREAD

**Issue by peterweb2005** [google/clasp#848]
libraries guide
https://developers.google.com/apps-script/guides/libraries

but it need to operate the script editor, eg: left library menu, click "+" to add

--

so could this process integrate in clasp?

**Comment by PopGoesTheWza** [comment]
Short answer is: No, and it is probably out of scope.

As far as I remember, there is no support in the API to interact with libraries.

**Comment by sqrrrl** [comment]
Libraries can be added via the manifest if you know the library ID/version, and clasp will push that correctly.

See https://developers.google.com/apps-script/manifest/dependencies

One thing I'd like to see in both the IDE and clasp is better discovery of libraries. There's no official registry of libraries akin to NPM, PyPi. If that were in place, then yeah, could see adding commands to clasp to make consuming libraries easier.

**Comment by PopGoesTheWza** [comment]
Also note that Typescript support for libraries is unlikely (no need to detail here why)

**Comment by peterweb2005** [comment]
thanks,
2 questions

## import

for example, i have a class in library
```
export class Testing {
test() {}
```

how should it be imported

## ide

when in development, 
how to make "vscode" able to reference to that library?
so that no compile warning?
