### ISSUE TITLE
forked-clasp giving error

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#849]
## Expected Behavior

Successful run of the `clasp` command.

## Actual Behavior

No matter what command I do, I get this error:

```
C:\Windows\system32\cmd.exe  - "node"   "C:\Users\nacho\AppData\Roaming\npm\\node_modules\forked-clasp\build\src\index.js" [8460]: c:\ws\src\api\callback.cc:129: Assertion `(env_->execution_async_id()) == (0)' failed.
 1: 00007FF65D50B05F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+111311
 2: 00007FF65D49CEA6 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+65014
 3: 00007FF65D49D221 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+65905
 4: 00007FF65D53A5BD node::CallbackScope::~CallbackScope+1021
 5: 00007FF65D53A22E node::CallbackScope::~CallbackScope+110
 6: 00007FF65D42EDAC v8::CFunction::ReturnInfo+17164
 7: 00007FF65D42D5C6 v8::CFunction::ReturnInfo+11046
 8: 00007FF65D42D285 v8::CFunction::ReturnInfo+10213
 9: 00007FF65D539C3E node::SpinEventLoop+334
10: 00007FF65D455973 v8::internal::AsmJsScanner::GetIdentifierString+53635
11: 00007FF65D4D09D7 node::Start+215
12: 00007FF65D2F84FC RC4_options+347132
13: 00007FF65E3C067C v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+151692
14: 00007FFEFDFF7034 BaseThreadInitThunk+20
15: 00007FFEFFEA2651 RtlUserThreadStart+33
```

This is a fresh install of Node and NPM. 

Normal `clasp` works but has the timeout error -- hence why I was trying `forked-clasp`.

## Steps to Reproduce the Problem

1. `npm uninstall -g @google/clasp`
1.`npm install -g forked-clasp`

## Specifications

|What|Version|
|-|-|
|Node|v16.3.0|
|NPM|7.17.0|
|Clasp|2.11.2|
|OS|Windows 10|

**Comment by PopGoesTheWza** [comment]
@imthenachoman since @google/clasp now has official maintainers and there are new releases, go with @google/clasp 2.3.1 (or 2.4.0 when it is released)

**Comment by imthenachoman** [comment]
`@google/clasp 2.3.1` has the time error/issue where it just waits after pushing. :/

**Comment by sqrrrl** [comment]
Closing as forked-clasp is a different project.

If there's an issue with push, please file a bug :)
