### ISSUE TITLE
Issue with using clasp after v2.4.0 release

### ISSUE THREAD

**Issue by sanjeevdialpad** [google/clasp#856]
Issue with using clasp after the new release (v2.4.0)
```
fs.js:498
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'package.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at file:///usr/local/lib/node_modules/@google/clasp/node_modules/ts2gas/src/index.js:35:35
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'package.json'
}
```

Seems to be dependency issue with ts2gas.
Downgrading to v2.3.2 helped solve the issue.

## Expected Behavior
clasp login/ any command would not work

## Actual Behavior
clasp login etc to work.

## Steps to Reproduce the Problem
Just install clasp and try to use it
1. npm i @google/clasp -g
2. clasp --help

## Specifications

- Node version (`node -v`): v14.17.0
- Version (`clasp -v`):  v2.4.0
- OS (Mac/Linux/Windows): Mac

**Comment by emiliorizzo** [comment]
Same error on linux

**Comment by MrBernhard** [comment]
Same error on Windows

**Comment by dlackey** [comment]
Created an empty package.json file as a workaround.
`echo "{}" > package.json`

**Comment by PopGoesTheWza** [comment]
The issue seems to be in latest `ts2gas`

**Comment by jackstruck** [comment]
Seeing the same problem but with a slightly different error message while accessing clasp through the [google cloud editor](https://cloud.google.com/blog/products/application-development/introducing-cloud-shell-editor).

`/usr/local/nvm/versions/node/v12.14.1/lib/node_modules/@google/clasp/build/src/index.js:2
import why from 'wtfnode'; // should be your first require
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11`
@sanjeevdialpad 's workaround was successful

**Comment by mjohnsonengr** [comment]
> Seeing the same problem but with a slightly different error message while accessing clasp through the [google cloud editor](https://cloud.google.com/blog/products/application-development/introducing-cloud-shell-editor).
> 
> ```
> /usr/local/nvm/versions/node/v12.14.1/lib/node_modules/@google/clasp/build/src/index.js:2
> import why from 'wtfnode'; // should be your first require
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at Module._compile (internal/modules/cjs/loader.js:891:18)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
>     at Module.load (internal/modules/cjs/loader.js:811:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
>     at internal/main/run_main_module.js:17:11
> ```
> 
> @sanjeevdialpad 's workaround was successful

I had that error but it went away when I either upgraded node or npm (I upgraded both with `sudo npm install -g npm@latest && sudo npm install -g node@latest`

Still have the main error in this issue.

**Comment by imthenachoman** [comment]
Any word/update on the fix for the original issue?

**Comment by PopGoesTheWza** [comment]
I was not able to reproduce the issue. Hence I am unsure if/how to fix https://github.com/grant/ts2gas

**Comment by lekseys** [comment]
I got "ENOENT: no such file or directory, open 'package.json'" message after renaming code.gs to code.ts and run "clasp push".


To resolv this problem i have put https://github.com/google/clasp/blob/master/package.json in root of my project.
