### ISSUE TITLE
"library", how to import and referenced in ide?

### ISSUE THREAD

**Issue by peterweb2005** [google/clasp#858]
thanks,
2 questions

## import

for example, i have a class in library
```
export class Testing {
test() {}
```

how should it be imported

## ide reference

when in development, 
how to make "vscode" able to reference to that library?
so that no compile warning?

**Comment by peterweb2005** [comment]
just found that even failed to export a class in libary

```
//
function hello() {
  return "hello";
}
//
class Test {
  static test() {
    return "test";
  }
  test1() {
    return "test1";
  }
}
```

function hello is ok, but class Test is not

**Comment by PopGoesTheWza** [comment]
Modules as well as `import` and `export` statements are not supported by the GAS engine.

For possible workarounds, see https://github.com/google/clasp/blob/master/docs/typescript.md#modules-exports-and-imports and https://github.com/google/clasp/blob/master/docs/esmodules.md

**Comment by peterweb2005** [comment]
thanks, tried before but neither one the one i wanted

first, much coding trouble & complex, although most gas module used
last, single first made product hard to debug in server

anyways thanks,
i just used the "copyfiles" approach, seems little bit simple & elegant
