### ISSUE TITLE
Project arguments are ignored in command line

### ISSUE THREAD

**Issue by Qythyx** [google/clasp#859]
## Expected Behavior

Using the command line arguments `-P` or `--project` should allow you to specify a clasp project file according to the help text: `path to a project file or to a folder with a '.clasp.json' file`.

## Actual Behavior

These arguments are ignored.

## Steps to Reproduce the Problem

1. Move your `.clasp.json` file to a new name like `myClasp.json`
2. Run `clasp -P myClasp.json versions`
3. You will see an error that `.clasp.json` was not found because the `-P` arg did not properly use the provided file

## Specifications

- Version (`clasp -v`): 2.4.0

**Comment by nandito** [comment]
Using the `-P` and `--project` doesn't work for me either. But it seems specifying the project file as environment variable works:

```
$ clasp_config_project=.clasp-test.json yarn clasp versions
```

(I have `clasp` 2.4.0 installed as a dependency in my project, `yarn clasp` simply runs the local `clasp`)
