### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by grant** [google/clasp#87]
## Expected Behavior
- Include Travis CI
- Add badge to repo

## Actual Behavior
No Travis. See other node examples: https://github.com/micromatch/micromatch

```
sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
```

**Comment by campionfellin** [comment]
I agree, I think that in clasp@2.0 there should be some sort of testing.
