### ISSUE TITLE
clasp push appsscript error even thought the file exists

### ISSUE THREAD

**Issue by namelus** [google/clasp#88]
Hi 

Copied over my project files to a new directory.
Entered the clasp push cmd, and received the following error:

```
$ clasp push
Push failed. Errors:
Project contents must include a manifest file named appsscript.
```

clasp pull worked correctly.
```
$ clasp pull
Cloned 2 files.
└─ Code.js
└─ appsscript.json
```

Any ideas here?

**Comment by grant** [comment]
Hmm. What's in your `appsscript.json` file?

**Comment by grant** [comment]
Please provide the details in the issue template so I can reproduce this error.
https://github.com/google/clasp/blob/master/ISSUE_TEMPLATE.md

Can you install the latest version? Does `clasp` work on a new project?

**Comment by namelus** [comment]
Looks like I have a new issue, will use the issue template per your request. My clasp version is 1.1.5

/d/OneDrive/Dev
$ mkdir tmp1

/d/OneDrive/Dev
$ clasp login
You seem to already be logged in. Did you mean to 'logout'?

/d/OneDrive/Dev
$ npm ls | grep clasp

/d/OneDrive/Dev
$ npm ls -g | grep clasp
+-- @google/clasp@1.1.5

/d/OneDrive/Dev
$ clasp clone 1DU_LO9FVY2d-isn0LNSnDZexhHcoxUNInM6Z-nfn2ovLYOD6amfMdEP8
Cloned 2 files.
└─ Code.js
└─ appsscript.json

/d/OneDrive/Dev
$ atom .


/d/OneDrive/Dev
$ clasp push
Push failed. Errors:
(node:19728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at C:\Users\ayahi\AppData\Roaming\nvm\v8.10.0\node_modules\@google\clasp\index.js:695:62
    at C:\Users\ayahi\AppData\Roaming\nvm\v8.10.0\node_modules\@google\clasp\node_modules\google-auth-library\build\src\auth\oauth2client.js:396:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:19728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:19728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

/d/OneDrive/Dev
$

**Comment by namelus** [comment]
Hi Grant

Thanks for your help and direction. I found a workaround here - simply created a new directory and started from scratch instead of copying the files from my other directory.

I'm pushing and pulling now.

Feel free to close this puppy out.

Kind regards,
Suleman

**Comment by namelus** [comment]
Found the issue. My claspignore file had

appscript.json

not 

appsscript.json

**Comment by grant** [comment]
Great. Maybe a `clasp status` (#73) would make debugging this a bit easier.
