### ISSUE TITLE
clasp login fail

### ISSUE THREAD

**Issue by dishcheng** [google/clasp#886]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
`clasp login` will run success  

## Actual Behavior

when I run `clasp login --no-localhost` or `clasp login` both showed like this
```
Logging in globally…
script.google.com ✖
console.developers.google.com ✖
console.cloud.google.com ✖
drive.google.com ✖
Error: Looks like you are offline.
```

I am sure that I can open goole.com in chrome 

Additional,I am in China,so I  must use vpn,and I don't kown how to fix this,thans.

## Specifications

- Node version (`node -v`):v16.13.0
- Version (`clasp -v`):2.4.1
- OS (Mac/Linux/Windows):mac

**Comment by slipperspaimiss** [comment]
me too  in china

**Comment by dishcheng** [comment]
> me too in china

咱俩就别秀英文了...

**Comment by slipperspaimiss** [comment]
拿你弄好了么，我登录可以但是还是没发生成。clasprc.json文件  也就是没法用
