### ISSUE TITLE
Clasp create should (?) check for pre-existing scripts

### ISSUE THREAD

**Issue by campionfellin** [google/clasp#89]
## Expected Behavior

`clasp create helloworld` when you already have a `helloworld` script at https://script.google.com/home should error out, saying a script exists already.

## Actual Behavior

It creates another script named `helloworld`

## Steps to Reproduce the Problem

  1. `clasp create helloworld`
  2. (in another folder) `clasp create helloworld`

## Specifications

  - Node version (`node -v`) v8.9.4
  - Version (`npm list -g | grep clasp`): @google/clasp@1.1.5
  - OS (Mac/Linux/Windows): macOS 10.13.3 High Sierra

**Comment by campionfellin** [comment]
**Note**: this would differ from actual behavior using the website interface, which allows you to create 2 scripts with the same name.

Should Clasp allow it (since the web interface does)? Or should we not?

**Comment by grant** [comment]
Project names aren't unique, the real identifier is the ~50 character `scriptId` hash. The project names are Drive files names, which can be the same name for Drive.

I'm thinking `clasp clone <autocomplete>` in #70 would help with this. And a proper library system for Apps Script.

**Comment by campionfellin** [comment]
That's a good point, I think autocomplete / `clasp list` will help with that. I am working a bit on `clasp list` right now, but looks like I'm getting rate-limited by the Drive API, which is possibly causing other errors.
