### ISSUE TITLE
feature idea: pull or push just a specific file

### ISSUE THREAD

**Issue by imthenachoman** [google/clasp#904]
I think it would be helpful to have a way to pull or push just a specific file.

**Comment by Nu11u5** [comment]
This is actually a limitation of the AppsScript API, which can only retrieve or update all project files at once.  Pushing only one file effectively deletes all other files.

**Comment by imthenachoman** [comment]
Ah. I see. 

A way to hack this would be:
- For `pull`, keep a temp copy of what is pulled and copy/replace just the file(s) requested
- For `push` make a temp copy pull, change the file in question, and push from the temp

As this is a rather unique use-case that probably only I have, it does not seem appropriate for y'all to have to try to solve this. I will find a way around for myself. I may see if I can enhance the `clasp` code myself.

Thank you!

**Comment by imthenachoman** [comment]
I wanted to ask a follow up question to confirm my understanding.

This means that `clasp` doesn't do any kind of `merging` with the tree, right?

For example, say this happens, in this order

1. `User1` pulls code using clasp and makes a change to `fileA`
2. `User2` pulls code using clasp and makes a change to `fileB`
3. `User1` pushes code
4. `User2` pushes code

At this point, `fileA` will **not** reflect the changes that `User1` made, right?

**Comment by Nu11u5** [comment]
Correct, a pull overwrites any existing files.

Clasp should not be used like a repository.  It does not track changes or do merges, only copy files between the cloud-hosted Apps Script project and local.  You should use a Git repository as the master source and push to GAS to test and deploy.
