### ISSUE TITLE
Do you push V2.5.0 to npmjs.com？

### ISSUE THREAD

**Issue by we684123** [google/clasp#929]
hi 030//
just like title, 

I found v2.5.0 at https://github.com/google/clasp/tree/2.5.0, but I don't see it on [npmjs.com](https://www.npmjs.com/package/@google/clasp)
Will you push v2.5.0 to the  npmjs ?
![2022-07-15 02_32_49-@google_clasp - npm — Mozilla Firefox](https://user-images.githubusercontent.com/22027801/179058017-40a6db6c-cf9c-4a79-a98b-712ed3a2538f.png)

**Comment by kospl** [comment]
Is this repo even alive?

**Comment by sqrrrl** [comment]
There is no 2.5.0 release. That was related to a forked version.
