### ISSUE TITLE
error push

### ISSUE THREAD

**Issue by eka05** [google/clasp#930]
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)

## Expected Behavior
can not push

## Steps to Reproduce the Problem
Help me please

PS E:\Clasp Google Script> clasp push

PS E:\Clasp Google Script> clasp push
drive.google.com ✖
Error: Looks like you are offline.

No valid E:\Clasp Google Script.clasp.json project file. You may need to create or clone a project first.
PS E:\Clasp Google Script> clasp push -w
console.cloud.google.com ✖
drive.google.com ✖
Error: Looks like you are offline.

## Specifications

- Node version (`node -v`): v16.16.0
- Version (`clasp -v`): 2.4.1
- OS (Mac/Linux/Windows): windows 10

**Comment by eko-develops** [comment]
@eka05  Try logging in with clasp first if you have not yet.
https://github.com/google/clasp#login

After logging in with clasp, you will need to create/clone the project first before being able to push. 
https://github.com/google/clasp#create
https://github.com/google/clasp#clone
