### ISSUE TITLE
Should throw error when running `clasp create` if there is a `.clasp.json` in a parent directory. 

### ISSUE THREAD

**Issue by diminishedprime** [google/clasp#97]
## Expected Behavior
When running `clasp create` in a child directory of a clasp project, clasp should throw an error explaining that nested projects are not supported. 

## Actual Behavior
Clasp silently uses the `.clasp.json` file of the parent directory, but creates a new project at the `process.cwd()`

## Steps to Reproduce the Problem

  1. create a clasp project in directory `a`
  1. `cd` into `a` and create a new sub-directory `b`
  1. run clasp create again with a new project name
  1. note that there is no `.clasp.json` file created in directory b.

## Specifications

  - Node version (`node -v`)
    - v9.10.1
  - Version (`npm list -g | grep clasp`):
    - latest from using npx
  - OS (Mac/Linux/Windows)
    - linux

**Comment by diminishedprime** [comment]
Likely related to issue #92

**Comment by grant** [comment]
Solution:
- `clasp create` should `getProjectSettings`. [Here](https://github.com/google/clasp/blob/master/index.ts#L579)
  - if getProjectSettings promise resolves, then log an error saying nested `clasp` projects are not supported.

PRs welcome.

**Comment by campionfellin** [comment]
This was fixed in #99
