### ISSUE TITLE
IMPORTANT: Clasp login may fail for new users

### ISSUE THREAD

**Issue by sqrrrl** [google/clasp#978]
Due to changes in OAuth policies clasp's built-in client ID will be temporarily reverted to an unapproved state and new users will not be able to authorize clasp. We're working to get this re-approved with updated privacy policies and terms of service.

Existing logins should continue to work correctly.

**Comment by abhijithcmr** [comment]
Any updates?

**Comment by sqrrrl** [comment]
Situation avoided :)

In the next major version we'll be adding support (and strongly encouraging) users to set up their own GCP project for clasp.
